-- +goose Up

ALTER TABLE storage_objects
    ADD COLUMN storage_key TEXT UNIQUE
        CHECK (storage_key IS NULL OR btrim(storage_key) <> '');

UPDATE storage_objects
SET storage_key = prefix || '/' || id::text || '/' || filename
WHERE available_at IS NOT NULL;

ALTER TABLE storage_objects DROP CONSTRAINT storage_objects_state_check;
ALTER TABLE storage_objects ADD CONSTRAINT storage_objects_state_check CHECK (
    (
        available_at IS NULL
        AND content_type = ''
        AND size_bytes IS NULL
        AND sha256 IS NULL
        AND storage_key IS NULL
    )
    OR (
        available_at IS NOT NULL
        AND content_type <> ''
        AND size_bytes IS NOT NULL
        AND sha256 IS NOT NULL
        AND storage_key IS NOT NULL
        AND multipart_upload_id IS NULL
    )
);

-- The existing table now matches Bloby's initial migration. Its runner owns
-- subsequent schema changes; migration 008 stays in the application ledger.
CREATE TABLE bloby_migrations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    version_id BIGINT NOT NULL,
    is_applied BOOLEAN NOT NULL,
    tstamp TIMESTAMP NOT NULL DEFAULT now()
);
INSERT INTO bloby_migrations (version_id, is_applied) VALUES (0, true), (1, true);
