root = "."
tmp_dir = ".air"
env_files = [".env"]

[build]
cmd = "go build -o ./.air/woodstar ./cmd/woodstar"
entrypoint = ["./.air/woodstar"]
include_dir = ["cmd", "internal"]
include_ext = ["go", "sql"]
include_file = [".env", "go.mod", "go.sum"]
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
send_interrupt = true
kill_delay = "500ms"
stop_on_error = true

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false
keep_scroll = true
