[[remotes]]
git_url = "https://github.com/woodleighschool/.github"
ref = "main"
configs = ["lefthook.common.toml"]

[pre-commit.commands.format-web]
glob = ["web/**/*.{ts,tsx,js,jsx,css}"]
root = "web/"
run = "oxfmt --no-error-on-unmatched-pattern {staged_files}"
stage_fixed = true

[pre-commit.commands.format-docs]
glob = ["docs/**/*.{ts,tsx,js,jsx,css}"]
root = "docs/"
run = "oxfmt --no-error-on-unmatched-pattern {staged_files}"
stage_fixed = true

[commit-msg.commands.commitlint]
run = "commitlint --default-config --edit {1}"
