[[remotes]]
git_url = "https://github.com/woodleighschool/.github"
ref = "main"
configs = ["lefthook.common.toml"]

[pre-commit.commands.format-web]
glob = ["web/**/*.{ts,tsx,js,jsx,css}", "docs/**/*.{ts,tsx,js,jsx,css}"]
root = "web/"
run = "oxfmt {staged_files}"
stage_fixed = true

[pre-commit.commands.format-yaml]
exclude = ["**/pnpm-lock.yaml", "web/openapi.yaml"]

[pre-commit.commands.format-json]
exclude = ["schema/osquery_fleet_schema.json"]
