export const queryKeys = {
  session: ["auth", "session"] as const,
  account: ["account"] as const,
  users: ["users"] as const,
  user: (id: string) => ["users", id] as const,
  osquerySchema: ["osquery-schema"] as const,
  hosts: (params?: unknown) => ["hosts", params ?? {}] as const,
  host: (id: string) => ["hosts", id] as const,
  hostSoftware: (id: string, params?: unknown) => ["hosts", id, "software", params ?? {}] as const,
  hostReports: (id: string) => ["hosts", id, "reports"] as const,
  hostReportResults: (hostId: string, reportId: string) => ["hosts", hostId, "reports", reportId] as const,
  hostChecks: (id: string) => ["hosts", id, "checks"] as const,
  hostSantaEffectiveRules: (id: string, params?: unknown) =>
    ["hosts", id, "santa", "effective-rules", params ?? {}] as const,
  labels: (params?: unknown) => ["labels", params ?? {}] as const,
  label: (id: string) => ["labels", id] as const,
  reports: (params?: unknown) => ["reports", params ?? {}] as const,
  report: (id: string) => ["reports", id] as const,
  reportResults: (id: string) => ["reports", id, "results"] as const,
  checks: (params?: unknown) => ["checks", params ?? {}] as const,
  check: (id: string) => ["checks", id] as const,
  checkHosts: (id: string) => ["checks", id, "hosts"] as const,
  software: (params?: unknown) => ["software", params ?? {}] as const,
  softwareTitle: (id: string) => ["software", id] as const,
  agentSecrets: ["agent-secrets"] as const,
  santaConfigurations: (params?: unknown) => ["santa", "configurations", params ?? {}] as const,
  santaConfiguration: (id: string) => ["santa", "configurations", id] as const,
  santaEvents: (params?: unknown) => ["santa", "events", params ?? {}] as const,
  santaRules: (params?: unknown) => ["santa", "rules", params ?? {}] as const,
  santaRule: (id: string) => ["santa", "rules", id] as const,
};
