export const queryKeys = {
  session: ["auth", "session"] as const,
  account: ["account"] as const,
  users: ["users"] as const,
  osquerySchema: ["osquery-schema"] as const,
  hosts: (params?: unknown) => ["hosts", params ?? {}] as const,
  host: (id: string) => ["hosts", id] as const,
  hostSoftware: (id: string, params?: unknown) => ["hosts", id, "software", params ?? {}] as const,
  hostQueries: (id: string) => ["hosts", id, "queries"] as const,
  hostQueryResults: (hostId: string, queryId: string) => ["hosts", hostId, "queries", queryId] as const,
  hostChecks: (id: string) => ["hosts", id, "checks"] as const,
  labels: (params?: unknown) => ["labels", params ?? {}] as const,
  label: (id: string) => ["labels", id] as const,
  queries: (params?: unknown) => ["queries", params ?? {}] as const,
  query: (id: string) => ["queries", id] as const,
  queryResults: (id: string) => ["queries", id, "results"] as const,
  checks: (params?: unknown) => ["checks", params ?? {}] as const,
  check: (id: string) => ["checks", id] as const,
  checkHosts: (id: string) => ["checks", id, "hosts"] as const,
  software: (params?: unknown) => ["software", params ?? {}] as const,
  softwareTitle: (id: string) => ["software", id] as const,
  enrollSecrets: ["orbit", "enroll-secrets"] as const,
};
