export const queryKeys = {
  session: ["auth", "session"] as const,
  account: ["account"] as const,
  // Root prefixes for invalidation: a list factory key is ["users", params], so the
  // bare prefix matches both the list and its detail/sub-resource keys.
  usersAll: ["users"] as const,
  groupsAll: ["groups"] as const,
  hostsAll: ["hosts"] as const,
  labelsAll: ["labels"] as const,
  checksAll: ["checks"] as const,
  reportsAll: ["reports"] as const,
  munkiSoftwareAll: ["munki", "software"] as const,
  munkiPackagesAll: ["munki", "packages"] as const,
  santaConfigurationsAll: ["santa", "configurations"] as const,
  santaRulesAll: ["santa", "rules"] as const,
  users: (params?: unknown) => ["users", params ?? {}] as const,
  user: (id: number | null) => ["users", id] as const,
  userDepartments: (params?: unknown) => ["users", "departments", params ?? {}] as const,
  groups: (params?: unknown) => ["groups", params ?? {}] as const,
  group: (id: number | null) => ["groups", id] as const,
  osquerySchema: ["osquery-schema"] as const,
  hosts: (params?: unknown) => ["hosts", params ?? {}] as const,
  host: (id: number | null) => ["hosts", id] as const,
  hostSoftware: (id: number | null, params?: unknown) =>
    ["hosts", id, "software", params ?? {}] as const,
  hostReports: (id: number | null) => ["hosts", id, "reports"] as const,
  hostChecks: (id: number | null) => ["hosts", id, "checks"] as const,
  hostSantaRules: (id: number | null, params?: unknown) =>
    ["hosts", id, "santa", "rules", params ?? {}] as const,
  labels: (params?: unknown) => ["labels", params ?? {}] as const,
  label: (id: number | null) => ["labels", id] as const,
  reports: (params?: unknown) => ["reports", params ?? {}] as const,
  report: (id: number | null) => ["reports", id] as const,
  reportResults: (id: number | null) => ["reports", id, "results"] as const,
  checks: (params?: unknown) => ["checks", params ?? {}] as const,
  check: (id: number | null) => ["checks", id] as const,
  checkHosts: (id: number | null) => ["checks", id, "hosts"] as const,
  software: (params?: unknown) => ["software", params ?? {}] as const,
  softwareTitle: (id: number | null) => ["software", id] as const,
  softwareSantaReference: (id: number | null) => ["software", id, "santa"] as const,
  munkiSoftware: (params?: unknown) => ["munki", "software", params ?? {}] as const,
  munkiSoftwareDetail: (id: number | null) => ["munki", "software", id] as const,
  munkiPackages: (params?: unknown) => ["munki", "packages", params ?? {}] as const,
  munkiPackage: (id: number | null) => ["munki", "packages", id] as const,
  storageObjectsAll: ["storage", "objects"] as const,
  storageObjects: (params?: unknown) => ["storage", "objects", params ?? {}] as const,
  agentSecrets: ["agent-secrets"] as const,
  santaConfigurations: (params?: unknown) => ["santa", "configurations", params ?? {}] as const,
  santaConfiguration: (id: number | null) => ["santa", "configurations", id] as const,
  santaEvents: (params?: unknown) => ["santa", "events", params ?? {}] as const,
  santaEvent: (id: number | null) => ["santa", "events", id] as const,
  santaFileAccessEvents: (params?: unknown) =>
    ["santa", "file-access-events", params ?? {}] as const,
  santaFileAccessEvent: (id: number | null) => ["santa", "file-access-events", id] as const,
  santaRules: (params?: unknown) => ["santa", "rules", params ?? {}] as const,
  santaRule: (id: number | null) => ["santa", "rules", id] as const,
  santaRuleReferences: (params?: unknown) => ["santa", "rule-references", params ?? {}] as const,
  liveQueryTargetCount: (params?: unknown) => ["live-query-target-count", params ?? {}] as const,
  appledbManifest: ["appledb-image-manifest"] as const,
  appledbDevice: (model: string | null | undefined) => ["appledb-device", model ?? null] as const,
};
