import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "category",
      label: "Account",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "api/woodstar-api",
          key: "account-api-woodstar-api",
        },
        {
          type: "category",
          label: "Account",
          key: "account-account",
          items: [
            {
              type: "doc",
              id: "api/get-account",
              label: "Get account",
              className: "api-method get",
              key: "account-account-api-get-account",
            },
            {
              type: "doc",
              id: "api/update-account",
              label: "Update account",
              className: "api-method put",
              key: "account-account-api-update-account",
            },
            {
              type: "doc",
              id: "api/revoke-account-api-key",
              label: "Revoke API key",
              className: "api-method delete",
              key: "account-account-api-revoke-account-api-key",
            },
            {
              type: "doc",
              id: "api/rotate-account-api-key",
              label: "Rotate API key",
              className: "api-method post",
              key: "account-account-api-rotate-account-api-key",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Agent secrets",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "api/woodstar-api",
          key: "agent-secrets-api-woodstar-api",
        },
        {
          type: "category",
          label: "Agent secrets",
          key: "agent-secrets-agent-secrets",
          items: [
            {
              type: "doc",
              id: "api/list-agent-secrets",
              label: "List agent secrets",
              className: "api-method get",
              key: "agent-secrets-agent-secrets-api-list-agent-secrets",
            },
            {
              type: "doc",
              id: "api/create-agent-secret",
              label: "Create an agent secret",
              className: "api-method post",
              key: "agent-secrets-agent-secrets-api-create-agent-secret",
            },
            {
              type: "doc",
              id: "api/delete-agent-secret",
              label: "Delete an agent secret",
              className: "api-method delete",
              key: "agent-secrets-agent-secrets-api-delete-agent-secret",
            },
            {
              type: "doc",
              id: "api/update-agent-secret",
              label: "Update an agent secret",
              className: "api-method put",
              key: "agent-secrets-agent-secrets-api-update-agent-secret",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Directory",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "api/woodstar-api",
          key: "directory-api-woodstar-api",
        },
        {
          type: "category",
          label: "Groups",
          key: "directory-groups",
          items: [
            {
              type: "doc",
              id: "api/list-groups",
              label: "List groups",
              className: "api-method get",
              key: "directory-directory-groups-api-list-groups",
            },
            {
              type: "doc",
              id: "api/get-group",
              label: "Get a group",
              className: "api-method get",
              key: "directory-directory-groups-api-get-group",
            },
          ],
        },
        {
          type: "category",
          label: "Users",
          key: "directory-users",
          items: [
            {
              type: "doc",
              id: "api/list-users",
              label: "List users",
              className: "api-method get",
              key: "directory-directory-users-api-list-users",
            },
            {
              type: "doc",
              id: "api/create-user",
              label: "Create a user",
              className: "api-method post",
              key: "directory-directory-users-api-create-user",
            },
            {
              type: "doc",
              id: "api/list-user-departments",
              label: "List user departments",
              className: "api-method get",
              key: "directory-directory-users-api-list-user-departments",
            },
            {
              type: "doc",
              id: "api/delete-user",
              label: "Delete a user",
              className: "api-method delete",
              key: "directory-directory-users-api-delete-user",
            },
            {
              type: "doc",
              id: "api/get-user",
              label: "Get a user",
              className: "api-method get",
              key: "directory-directory-users-api-get-user",
            },
            {
              type: "doc",
              id: "api/update-user",
              label: "Update a user",
              className: "api-method put",
              key: "directory-directory-users-api-update-user",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Hosts",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "api/woodstar-api",
          key: "hosts-api-woodstar-api",
        },
        {
          type: "category",
          label: "Hosts",
          key: "hosts-hosts",
          items: [
            {
              type: "doc",
              id: "api/bulk-delete-hosts",
              label: "Delete hosts",
              className: "api-method delete",
              key: "hosts-hosts-api-bulk-delete-hosts",
            },
            {
              type: "doc",
              id: "api/list-hosts",
              label: "List hosts",
              className: "api-method get",
              key: "hosts-hosts-api-list-hosts",
            },
            {
              type: "doc",
              id: "api/delete-host",
              label: "Delete a host",
              className: "api-method delete",
              key: "hosts-hosts-api-delete-host",
            },
            {
              type: "doc",
              id: "api/get-host",
              label: "Get a host",
              className: "api-method get",
              key: "hosts-hosts-api-get-host",
            },
            {
              type: "doc",
              id: "api/get-host-munki-state",
              label: "Get Munki state for a host",
              className: "api-method get",
              key: "hosts-hosts-api-get-host-munki-state",
            },
            {
              type: "doc",
              id: "api/list-host-osquery-checks",
              label: "List checks for a host",
              className: "api-method get",
              key: "hosts-hosts-api-list-host-osquery-checks",
            },
            {
              type: "doc",
              id: "api/list-host-osquery-reports",
              label: "List reports for a host",
              className: "api-method get",
              key: "hosts-hosts-api-list-host-osquery-reports",
            },
            {
              type: "doc",
              id: "api/clear-host-primary-user",
              label: "Clear primary user for a host",
              className: "api-method delete",
              key: "hosts-hosts-api-clear-host-primary-user",
            },
            {
              type: "doc",
              id: "api/set-host-primary-user",
              label: "Set primary user for a host",
              className: "api-method put",
              key: "hosts-hosts-api-set-host-primary-user",
            },
            {
              type: "doc",
              id: "api/get-host-santa-state",
              label: "Get Santa state for a host",
              className: "api-method get",
              key: "hosts-hosts-api-get-host-santa-state",
            },
            {
              type: "doc",
              id: "api/list-host-santa-rules",
              label: "List Santa rules for a host",
              className: "api-method get",
              key: "hosts-hosts-api-list-host-santa-rules",
            },
            {
              type: "doc",
              id: "api/list-host-software",
              label: "List software for a host",
              className: "api-method get",
              key: "hosts-hosts-api-list-host-software",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Labels",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "api/woodstar-api",
          key: "labels-api-woodstar-api",
        },
        {
          type: "category",
          label: "Labels",
          key: "labels-labels",
          items: [
            {
              type: "doc",
              id: "api/list-labels",
              label: "List labels",
              className: "api-method get",
              key: "labels-labels-api-list-labels",
            },
            {
              type: "doc",
              id: "api/create-label",
              label: "Create a label",
              className: "api-method post",
              key: "labels-labels-api-create-label",
            },
            {
              type: "doc",
              id: "api/delete-label",
              label: "Delete a label",
              className: "api-method delete",
              key: "labels-labels-api-delete-label",
            },
            {
              type: "doc",
              id: "api/get-label",
              label: "Get a label",
              className: "api-method get",
              key: "labels-labels-api-get-label",
            },
            {
              type: "doc",
              id: "api/update-label",
              label: "Update a label",
              className: "api-method put",
              key: "labels-labels-api-update-label",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Munki",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "api/woodstar-api",
          key: "munki-api-woodstar-api",
        },
        {
          type: "category",
          label: "Client resources",
          key: "munki-client-resources",
          items: [
            {
              type: "doc",
              id: "api/delete-munki-client-resources",
              label: "Delete client resources",
              className: "api-method delete",
              key: "munki-munki-client-resources-api-delete-munki-client-resources",
            },
            {
              type: "doc",
              id: "api/get-munki-client-resources",
              label: "Get client resources",
              className: "api-method get",
              key: "munki-munki-client-resources-api-get-munki-client-resources",
            },
            {
              type: "doc",
              id: "api/update-munki-client-resources",
              label: "Update client resources",
              className: "api-method put",
              key: "munki-munki-client-resources-api-update-munki-client-resources",
            },
            {
              type: "doc",
              id: "api/create-munki-client-resources-banner-upload",
              label: "Create a banner upload",
              className: "api-method post",
              key: "munki-munki-client-resources-api-create-munki-client-resources-banner-upload",
            },
            {
              type: "doc",
              id: "api/delete-munki-client-resources-banner-upload",
              label: "Delete a banner upload",
              className: "api-method delete",
              key: "munki-munki-client-resources-api-delete-munki-client-resources-banner-upload",
            },
          ],
        },
        {
          type: "category",
          label: "Distribution points",
          key: "munki-distribution-points",
          items: [
            {
              type: "doc",
              id: "api/list-munki-distribution-points",
              label: "List distribution points",
              className: "api-method get",
              key: "munki-munki-distribution-points-api-list-munki-distribution-points",
            },
            {
              type: "doc",
              id: "api/create-munki-distribution-point",
              label: "Create a distribution point",
              className: "api-method post",
              key: "munki-munki-distribution-points-api-create-munki-distribution-point",
            },
            {
              type: "doc",
              id: "api/reorder-munki-distribution-points",
              label: "Reorder distribution points",
              className: "api-method put",
              key: "munki-munki-distribution-points-api-reorder-munki-distribution-points",
            },
            {
              type: "doc",
              id: "api/delete-munki-distribution-point",
              label: "Delete a distribution point",
              className: "api-method delete",
              key: "munki-munki-distribution-points-api-delete-munki-distribution-point",
            },
            {
              type: "doc",
              id: "api/get-munki-distribution-point",
              label: "Get a distribution point",
              className: "api-method get",
              key: "munki-munki-distribution-points-api-get-munki-distribution-point",
            },
            {
              type: "doc",
              id: "api/update-munki-distribution-point",
              label: "Update a distribution point",
              className: "api-method put",
              key: "munki-munki-distribution-points-api-update-munki-distribution-point",
            },
            {
              type: "doc",
              id: "api/rotate-munki-distribution-point-key",
              label: "Rotate a distribution point key",
              className: "api-method post",
              key: "munki-munki-distribution-points-api-rotate-munki-distribution-point-key",
            },
          ],
        },
        {
          type: "category",
          label: "Icons",
          key: "munki-icons",
          items: [
            {
              type: "doc",
              id: "api/list-munki-icons",
              label: "List icons",
              className: "api-method get",
              key: "munki-munki-icons-api-list-munki-icons",
            },
            {
              type: "doc",
              id: "api/create-munki-icon-upload",
              label: "Create an icon upload",
              className: "api-method post",
              key: "munki-munki-icons-api-create-munki-icon-upload",
            },
            {
              type: "doc",
              id: "api/set-munki-software-icon",
              label: "Set a software icon",
              className: "api-method put",
              key: "munki-munki-icons-api-set-munki-software-icon",
            },
          ],
        },
        {
          type: "category",
          label: "Package installers",
          key: "munki-package-installers",
          items: [
            {
              type: "doc",
              id: "api/create-munki-package-installer-upload",
              label: "Create a package installer upload",
              className: "api-method post",
              key: "munki-munki-package-installers-api-create-munki-package-installer-upload",
            },
            {
              type: "doc",
              id: "api/delete-munki-package-installer-upload",
              label: "Delete a package installer upload",
              className: "api-method delete",
              key: "munki-munki-package-installers-api-delete-munki-package-installer-upload",
            },
            {
              type: "doc",
              id: "api/complete-munki-package-installer-upload",
              label: "Complete a package installer upload",
              className: "api-method put",
              key: "munki-munki-package-installers-api-complete-munki-package-installer-upload",
            },
            {
              type: "doc",
              id: "api/create-munki-package-installer-multipart",
              label: "Create a multipart upload",
              className: "api-method post",
              key: "munki-munki-package-installers-api-create-munki-package-installer-multipart",
            },
            {
              type: "doc",
              id: "api/complete-munki-package-installer-multipart",
              label: "Complete a multipart upload",
              className: "api-method put",
              key: "munki-munki-package-installers-api-complete-munki-package-installer-multipart",
            },
            {
              type: "doc",
              id: "api/sign-munki-package-installer-part",
              label: "Sign a multipart upload part",
              className: "api-method post",
              key: "munki-munki-package-installers-api-sign-munki-package-installer-part",
            },
          ],
        },
        {
          type: "category",
          label: "Packages",
          key: "munki-packages",
          items: [
            {
              type: "doc",
              id: "api/bulk-delete-munki-packages",
              label: "Delete packages",
              className: "api-method delete",
              key: "munki-munki-packages-api-bulk-delete-munki-packages",
            },
            {
              type: "doc",
              id: "api/list-munki-packages",
              label: "List packages",
              className: "api-method get",
              key: "munki-munki-packages-api-list-munki-packages",
            },
            {
              type: "doc",
              id: "api/create-munki-package",
              label: "Create a package",
              className: "api-method post",
              key: "munki-munki-packages-api-create-munki-package",
            },
            {
              type: "doc",
              id: "api/get-munki-package",
              label: "Get a package",
              className: "api-method get",
              key: "munki-munki-packages-api-get-munki-package",
            },
            {
              type: "doc",
              id: "api/update-munki-package",
              label: "Update a package",
              className: "api-method put",
              key: "munki-munki-packages-api-update-munki-package",
            },
          ],
        },
        {
          type: "category",
          label: "Software",
          key: "munki-software",
          items: [
            {
              type: "doc",
              id: "api/bulk-delete-munki-software",
              label: "Delete software titles",
              className: "api-method delete",
              key: "munki-munki-software-api-bulk-delete-munki-software",
            },
            {
              type: "doc",
              id: "api/list-munki-software",
              label: "List software titles",
              className: "api-method get",
              key: "munki-munki-software-api-list-munki-software",
            },
            {
              type: "doc",
              id: "api/create-munki-software",
              label: "Create a software title",
              className: "api-method post",
              key: "munki-munki-software-api-create-munki-software",
            },
            {
              type: "doc",
              id: "api/delete-munki-software",
              label: "Delete a software title",
              className: "api-method delete",
              key: "munki-munki-software-api-delete-munki-software",
            },
            {
              type: "doc",
              id: "api/get-munki-software",
              label: "Get a software title",
              className: "api-method get",
              key: "munki-munki-software-api-get-munki-software",
            },
            {
              type: "doc",
              id: "api/update-munki-software",
              label: "Update a software title",
              className: "api-method put",
              key: "munki-munki-software-api-update-munki-software",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Osquery",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "api/woodstar-api",
          key: "osquery-api-woodstar-api",
        },
        {
          type: "category",
          label: "Checks",
          key: "osquery-checks",
          items: [
            {
              type: "doc",
              id: "api/bulk-delete-osquery-checks",
              label: "Delete checks",
              className: "api-method delete",
              key: "osquery-osquery-checks-api-bulk-delete-osquery-checks",
            },
            {
              type: "doc",
              id: "api/list-osquery-checks",
              label: "List checks",
              className: "api-method get",
              key: "osquery-osquery-checks-api-list-osquery-checks",
            },
            {
              type: "doc",
              id: "api/create-osquery-check",
              label: "Create a check",
              className: "api-method post",
              key: "osquery-osquery-checks-api-create-osquery-check",
            },
            {
              type: "doc",
              id: "api/delete-osquery-check",
              label: "Delete a check",
              className: "api-method delete",
              key: "osquery-osquery-checks-api-delete-osquery-check",
            },
            {
              type: "doc",
              id: "api/get-osquery-check",
              label: "Get a check",
              className: "api-method get",
              key: "osquery-osquery-checks-api-get-osquery-check",
            },
            {
              type: "doc",
              id: "api/update-osquery-check",
              label: "Update a check",
              className: "api-method put",
              key: "osquery-osquery-checks-api-update-osquery-check",
            },
            {
              type: "doc",
              id: "api/list-osquery-check-results",
              label: "List check results",
              className: "api-method get",
              key: "osquery-osquery-checks-api-list-osquery-check-results",
            },
          ],
        },
        {
          type: "category",
          label: "Live queries",
          key: "osquery-live-queries",
          items: [
            {
              type: "doc",
              id: "api/create-live-query",
              label: "Create a live query",
              className: "api-method post",
              key: "osquery-osquery-live-queries-api-create-live-query",
            },
            {
              type: "doc",
              id: "api/count-live-query-targets",
              label: "Count live query targets",
              className: "api-method post",
              key: "osquery-osquery-live-queries-api-count-live-query-targets",
            },
            {
              type: "doc",
              id: "api/delete-live-query",
              label: "Delete a live query",
              className: "api-method delete",
              key: "osquery-osquery-live-queries-api-delete-live-query",
            },
            {
              type: "doc",
              id: "api/stream-live-query",
              label: "Stream live query results",
              className: "api-method get",
              key: "osquery-osquery-live-queries-api-stream-live-query",
            },
          ],
        },
        {
          type: "category",
          label: "Reports",
          key: "osquery-reports",
          items: [
            {
              type: "doc",
              id: "api/bulk-delete-osquery-reports",
              label: "Delete reports",
              className: "api-method delete",
              key: "osquery-osquery-reports-api-bulk-delete-osquery-reports",
            },
            {
              type: "doc",
              id: "api/list-osquery-reports",
              label: "List reports",
              className: "api-method get",
              key: "osquery-osquery-reports-api-list-osquery-reports",
            },
            {
              type: "doc",
              id: "api/create-osquery-report",
              label: "Create a report",
              className: "api-method post",
              key: "osquery-osquery-reports-api-create-osquery-report",
            },
            {
              type: "doc",
              id: "api/delete-osquery-report",
              label: "Delete a report",
              className: "api-method delete",
              key: "osquery-osquery-reports-api-delete-osquery-report",
            },
            {
              type: "doc",
              id: "api/get-osquery-report",
              label: "Get a report",
              className: "api-method get",
              key: "osquery-osquery-reports-api-get-osquery-report",
            },
            {
              type: "doc",
              id: "api/update-osquery-report",
              label: "Update a report",
              className: "api-method put",
              key: "osquery-osquery-reports-api-update-osquery-report",
            },
            {
              type: "doc",
              id: "api/list-osquery-report-results",
              label: "List report results",
              className: "api-method get",
              key: "osquery-osquery-reports-api-list-osquery-report-results",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Santa",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "api/woodstar-api",
          key: "santa-api-woodstar-api",
        },
        {
          type: "category",
          label: "Configurations",
          key: "santa-configurations",
          items: [
            {
              type: "doc",
              id: "api/bulk-delete-santa-configurations",
              label: "Delete configurations",
              className: "api-method delete",
              key: "santa-santa-configurations-api-bulk-delete-santa-configurations",
            },
            {
              type: "doc",
              id: "api/list-santa-configurations",
              label: "List configurations",
              className: "api-method get",
              key: "santa-santa-configurations-api-list-santa-configurations",
            },
            {
              type: "doc",
              id: "api/create-santa-configuration",
              label: "Create a configuration",
              className: "api-method post",
              key: "santa-santa-configurations-api-create-santa-configuration",
            },
            {
              type: "doc",
              id: "api/reorder-santa-configurations",
              label: "Reorder configurations",
              className: "api-method put",
              key: "santa-santa-configurations-api-reorder-santa-configurations",
            },
            {
              type: "doc",
              id: "api/delete-santa-configuration",
              label: "Delete a configuration",
              className: "api-method delete",
              key: "santa-santa-configurations-api-delete-santa-configuration",
            },
            {
              type: "doc",
              id: "api/get-santa-configuration",
              label: "Get a configuration",
              className: "api-method get",
              key: "santa-santa-configurations-api-get-santa-configuration",
            },
            {
              type: "doc",
              id: "api/update-santa-configuration",
              label: "Update a configuration",
              className: "api-method put",
              key: "santa-santa-configurations-api-update-santa-configuration",
            },
          ],
        },
        {
          type: "category",
          label: "Events",
          key: "santa-events",
          items: [
            {
              type: "doc",
              id: "api/list-santa-events",
              label: "List execution events",
              className: "api-method get",
              key: "santa-santa-events-api-list-santa-events",
            },
            {
              type: "doc",
              id: "api/get-santa-event",
              label: "Get an execution event",
              className: "api-method get",
              key: "santa-santa-events-api-get-santa-event",
            },
            {
              type: "doc",
              id: "api/list-santa-file-access-events",
              label: "List file access events",
              className: "api-method get",
              key: "santa-santa-events-api-list-santa-file-access-events",
            },
            {
              type: "doc",
              id: "api/get-santa-file-access-event",
              label: "Get a file access event",
              className: "api-method get",
              key: "santa-santa-events-api-get-santa-file-access-event",
            },
          ],
        },
        {
          type: "category",
          label: "Rules",
          key: "santa-rules",
          items: [
            {
              type: "doc",
              id: "api/bulk-delete-santa-rules",
              label: "Delete rules",
              className: "api-method delete",
              key: "santa-santa-rules-api-bulk-delete-santa-rules",
            },
            {
              type: "doc",
              id: "api/list-santa-rules",
              label: "List rules",
              className: "api-method get",
              key: "santa-santa-rules-api-list-santa-rules",
            },
            {
              type: "doc",
              id: "api/create-santa-rule",
              label: "Create a rule",
              className: "api-method post",
              key: "santa-santa-rules-api-create-santa-rule",
            },
            {
              type: "doc",
              id: "api/delete-santa-rule",
              label: "Delete a rule",
              className: "api-method delete",
              key: "santa-santa-rules-api-delete-santa-rule",
            },
            {
              type: "doc",
              id: "api/get-santa-rule",
              label: "Get a rule",
              className: "api-method get",
              key: "santa-santa-rules-api-get-santa-rule",
            },
            {
              type: "doc",
              id: "api/update-santa-rule",
              label: "Update a rule",
              className: "api-method put",
              key: "santa-santa-rules-api-update-santa-rule",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Session",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "api/woodstar-api",
          key: "session-api-woodstar-api",
        },
        {
          type: "category",
          label: "Session",
          key: "session-session",
          items: [
            {
              type: "doc",
              id: "api/delete-session",
              label: "Delete session",
              className: "api-method delete",
              key: "session-session-api-delete-session",
            },
            {
              type: "doc",
              id: "api/get-session",
              label: "Get session",
              className: "api-method get",
              key: "session-session-api-get-session",
            },
            {
              type: "doc",
              id: "api/create-session",
              label: "Create a session",
              className: "api-method post",
              key: "session-session-api-create-session",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Software",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "api/woodstar-api",
          key: "software-api-woodstar-api",
        },
        {
          type: "category",
          label: "Software",
          key: "software-software",
          items: [
            {
              type: "doc",
              id: "api/list-software",
              label: "List software titles",
              className: "api-method get",
              key: "software-software-api-list-software",
            },
            {
              type: "doc",
              id: "api/get-software",
              label: "Get a software title",
              className: "api-method get",
              key: "software-software-api-get-software",
            },
            {
              type: "doc",
              id: "api/get-software-santa-reference",
              label: "Get Santa reference for a software title",
              className: "api-method get",
              key: "software-software-api-get-software-santa-reference",
            },
          ],
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
