// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checks.sql

package sqlc

import (
	"context"
	"time"
)

const createCheck = `-- name: CreateCheck :one
INSERT INTO checks (
    name,
    description,
    query,
    platform,
    created_by_user_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING
    id,
    name,
    description,
    query,
    platform,
    label_scope_mode,
    created_by_user_id,
    created_at,
    updated_at
`

type CreateCheckParams struct {
	Name            string    `json:"name"`
	Description     string    `json:"description"`
	Query           string    `json:"query"`
	Platform        *Platform `json:"platform"`
	CreatedByUserID *int64    `json:"created_by_user_id"`
}

func (q *Queries) CreateCheck(ctx context.Context, arg CreateCheckParams) (Check, error) {
	row := q.db.QueryRow(ctx, createCheck,
		arg.Name,
		arg.Description,
		arg.Query,
		arg.Platform,
		arg.CreatedByUserID,
	)
	var i Check
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Query,
		&i.Platform,
		&i.LabelScopeMode,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCheck = `-- name: DeleteCheck :one
DELETE FROM checks
WHERE id = $1
RETURNING id
`

type DeleteCheckParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) DeleteCheck(ctx context.Context, arg DeleteCheckParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteCheck, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteChecks = `-- name: DeleteChecks :many
DELETE FROM checks
WHERE id = ANY($1::bigint[])
RETURNING id
`

type DeleteChecksParams struct {
	Ids []int64 `json:"ids"`
}

func (q *Queries) DeleteChecks(ctx context.Context, arg DeleteChecksParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, deleteChecks, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCheckByID = `-- name: GetCheckByID :one
SELECT
    id,
    name,
    description,
    query,
    platform,
    label_scope_mode,
    created_by_user_id,
    created_at,
    updated_at
FROM checks
WHERE id = $1
`

type GetCheckByIDParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) GetCheckByID(ctx context.Context, arg GetCheckByIDParams) (Check, error) {
	row := q.db.QueryRow(ctx, getCheckByID, arg.ID)
	var i Check
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Query,
		&i.Platform,
		&i.LabelScopeMode,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApplicableChecksForHost = `-- name: ListApplicableChecksForHost :many
WITH host_row AS (
    SELECT
        id,
        lower(platform) AS platform
    FROM hosts h
    WHERE h.id = $1 AND h.deleted_at IS NULL
)
SELECT
    c.id,
    c.name,
    c.description,
    c.query,
    c.platform,
    c.label_scope_mode,
    c.created_by_user_id,
    c.created_at,
    c.updated_at
FROM checks c
JOIN host_row h ON true
WHERE (
      c.platform IS NULL
      OR c.platform::text = h.platform
      OR (c.platform = 'darwin' AND h.platform = 'macos')
      OR (c.platform = 'linux' AND h.platform <> '' AND h.platform NOT IN ('darwin', 'macos', 'windows', 'chrome'))
  )
  AND (
      c.label_scope_mode = 'none'
      OR (
          c.label_scope_mode = 'include_any'
          AND EXISTS (
              SELECT 1
              FROM check_labels cl
              JOIN label_membership lm ON lm.label_id = cl.label_id AND lm.host_id = h.id
              WHERE cl.check_id = c.id
          )
      )
      OR (
          c.label_scope_mode = 'include_all'
          AND NOT EXISTS (
              SELECT 1
              FROM check_labels cl
              WHERE cl.check_id = c.id
                AND NOT EXISTS (
                    SELECT 1
                    FROM label_membership lm
                    WHERE lm.label_id = cl.label_id AND lm.host_id = h.id
                )
          )
      )
      OR (
          c.label_scope_mode = 'exclude_any'
          AND NOT EXISTS (
              SELECT 1
              FROM check_labels cl
              JOIN label_membership lm ON lm.label_id = cl.label_id AND lm.host_id = h.id
              WHERE cl.check_id = c.id
          )
      )
  )
ORDER BY c.id
`

type ListApplicableChecksForHostParams struct {
	HostID int64 `json:"host_id"`
}

func (q *Queries) ListApplicableChecksForHost(ctx context.Context, arg ListApplicableChecksForHostParams) ([]Check, error) {
	rows, err := q.db.Query(ctx, listApplicableChecksForHost, arg.HostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Check{}
	for rows.Next() {
		var i Check
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Query,
			&i.Platform,
			&i.LabelScopeMode,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckHostStatuses = `-- name: ListCheckHostStatuses :many
WITH check_row AS (
    SELECT id, name, description, query, platform, label_scope_mode, created_by_user_id, created_at, updated_at
    FROM checks c
    WHERE c.id = $1
),
host_rows AS (
    SELECT
        id,
        display_name,
        lower(platform) AS platform
    FROM hosts
    WHERE deleted_at IS NULL
)
SELECT
    c.id AS check_id,
    c.name AS check_name,
    h.id AS host_id,
    h.display_name AS host_name,
    m.passes,
    m.updated_at
FROM check_row c
JOIN host_rows h ON true
LEFT JOIN check_membership m ON m.host_id = h.id AND m.check_id = c.id
WHERE (
      c.platform IS NULL
      OR c.platform::text = h.platform
      OR (c.platform = 'darwin' AND h.platform = 'macos')
      OR (c.platform = 'linux' AND h.platform <> '' AND h.platform NOT IN ('darwin', 'macos', 'windows', 'chrome'))
  )
  AND (
      c.label_scope_mode = 'none'
      OR (
          c.label_scope_mode = 'include_any'
          AND EXISTS (
              SELECT 1
              FROM check_labels cl
              JOIN label_membership lm ON lm.label_id = cl.label_id AND lm.host_id = h.id
              WHERE cl.check_id = c.id
          )
      )
      OR (
          c.label_scope_mode = 'include_all'
          AND NOT EXISTS (
              SELECT 1
              FROM check_labels cl
              WHERE cl.check_id = c.id
                AND NOT EXISTS (
                    SELECT 1
                    FROM label_membership lm
                    WHERE lm.label_id = cl.label_id AND lm.host_id = h.id
                )
          )
      )
      OR (
          c.label_scope_mode = 'exclude_any'
          AND NOT EXISTS (
              SELECT 1
              FROM check_labels cl
              JOIN label_membership lm ON lm.label_id = cl.label_id AND lm.host_id = h.id
              WHERE cl.check_id = c.id
          )
      )
  )
ORDER BY
    CASE
        WHEN m.passes IS FALSE THEN 0
        WHEN m.passes IS NULL THEN 1
        ELSE 2
    END,
    lower(h.display_name),
    h.id
`

type ListCheckHostStatusesParams struct {
	CheckID int64 `json:"check_id"`
}

type ListCheckHostStatusesRow struct {
	CheckID   int64      `json:"check_id"`
	CheckName string     `json:"check_name"`
	HostID    int64      `json:"host_id"`
	HostName  string     `json:"host_name"`
	Passes    *bool      `json:"passes"`
	UpdatedAt *time.Time `json:"updated_at"`
}

func (q *Queries) ListCheckHostStatuses(ctx context.Context, arg ListCheckHostStatusesParams) ([]ListCheckHostStatusesRow, error) {
	rows, err := q.db.Query(ctx, listCheckHostStatuses, arg.CheckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCheckHostStatusesRow{}
	for rows.Next() {
		var i ListCheckHostStatusesRow
		if err := rows.Scan(
			&i.CheckID,
			&i.CheckName,
			&i.HostID,
			&i.HostName,
			&i.Passes,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostCheckStatusesForHost = `-- name: ListHostCheckStatusesForHost :many
WITH host_row AS (
    SELECT
        id,
        display_name,
        lower(platform) AS platform
    FROM hosts h
    WHERE h.id = $1 AND h.deleted_at IS NULL
)
SELECT
    c.id AS check_id,
    c.name AS check_name,
    h.id AS host_id,
    h.display_name AS host_name,
    m.passes,
    m.updated_at
FROM checks c
JOIN host_row h ON true
LEFT JOIN check_membership m ON m.host_id = h.id AND m.check_id = c.id
WHERE (
      c.platform IS NULL
      OR c.platform::text = h.platform
      OR (c.platform = 'darwin' AND h.platform = 'macos')
      OR (c.platform = 'linux' AND h.platform <> '' AND h.platform NOT IN ('darwin', 'macos', 'windows', 'chrome'))
  )
  AND (
      c.label_scope_mode = 'none'
      OR (
          c.label_scope_mode = 'include_any'
          AND EXISTS (
              SELECT 1
              FROM check_labels cl
              JOIN label_membership lm ON lm.label_id = cl.label_id AND lm.host_id = h.id
              WHERE cl.check_id = c.id
          )
      )
      OR (
          c.label_scope_mode = 'include_all'
          AND NOT EXISTS (
              SELECT 1
              FROM check_labels cl
              WHERE cl.check_id = c.id
                AND NOT EXISTS (
                    SELECT 1
                    FROM label_membership lm
                    WHERE lm.label_id = cl.label_id AND lm.host_id = h.id
                )
          )
      )
      OR (
          c.label_scope_mode = 'exclude_any'
          AND NOT EXISTS (
              SELECT 1
              FROM check_labels cl
              JOIN label_membership lm ON lm.label_id = cl.label_id AND lm.host_id = h.id
              WHERE cl.check_id = c.id
          )
      )
  )
ORDER BY
    CASE
        WHEN m.passes IS FALSE THEN 0
        WHEN m.passes IS NULL THEN 1
        ELSE 2
    END,
    lower(c.name),
    c.id
`

type ListHostCheckStatusesForHostParams struct {
	HostID int64 `json:"host_id"`
}

type ListHostCheckStatusesForHostRow struct {
	CheckID   int64      `json:"check_id"`
	CheckName string     `json:"check_name"`
	HostID    int64      `json:"host_id"`
	HostName  string     `json:"host_name"`
	Passes    *bool      `json:"passes"`
	UpdatedAt *time.Time `json:"updated_at"`
}

func (q *Queries) ListHostCheckStatusesForHost(ctx context.Context, arg ListHostCheckStatusesForHostParams) ([]ListHostCheckStatusesForHostRow, error) {
	rows, err := q.db.Query(ctx, listHostCheckStatusesForHost, arg.HostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHostCheckStatusesForHostRow{}
	for rows.Next() {
		var i ListHostCheckStatusesForHostRow
		if err := rows.Scan(
			&i.CheckID,
			&i.CheckName,
			&i.HostID,
			&i.HostName,
			&i.Passes,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCheck = `-- name: UpdateCheck :one
UPDATE checks
SET
    name = $1,
    description = $2,
    query = $3,
    platform = $4,
    updated_at = now()
WHERE id = $5
RETURNING
    id,
    name,
    description,
    query,
    platform,
    label_scope_mode,
    created_by_user_id,
    created_at,
    updated_at
`

type UpdateCheckParams struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Query       string    `json:"query"`
	Platform    *Platform `json:"platform"`
	ID          int64     `json:"id"`
}

func (q *Queries) UpdateCheck(ctx context.Context, arg UpdateCheckParams) (Check, error) {
	row := q.db.QueryRow(ctx, updateCheck,
		arg.Name,
		arg.Description,
		arg.Query,
		arg.Platform,
		arg.ID,
	)
	var i Check
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Query,
		&i.Platform,
		&i.LabelScopeMode,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCheckMembership = `-- name: UpsertCheckMembership :exec
INSERT INTO check_membership (
    check_id,
    host_id,
    passes,
    updated_at
)
VALUES (
    $1,
    $2,
    $3,
    now()
)
ON CONFLICT (check_id, host_id) DO UPDATE SET
    passes = EXCLUDED.passes,
    updated_at = now()
`

type UpsertCheckMembershipParams struct {
	CheckID int64 `json:"check_id"`
	HostID  int64 `json:"host_id"`
	Passes  *bool `json:"passes"`
}

func (q *Queries) UpsertCheckMembership(ctx context.Context, arg UpsertCheckMembershipParams) error {
	_, err := q.db.Exec(ctx, upsertCheckMembership, arg.CheckID, arg.HostID, arg.Passes)
	return err
}
