// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_mappings.sql

package sqlc

import (
	"context"
)

const listHostDeviceMappings = `-- name: ListHostDeviceMappings :many
SELECT id, host_id, email, source, created_at, updated_at
FROM host_emails
WHERE host_id = $1
ORDER BY source
`

type ListHostDeviceMappingsParams struct {
	HostID int64 `json:"host_id"`
}

func (q *Queries) ListHostDeviceMappings(ctx context.Context, arg ListHostDeviceMappingsParams) ([]HostEmail, error) {
	rows, err := q.db.Query(ctx, listHostDeviceMappings, arg.HostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostEmail{}
	for rows.Next() {
		var i HostEmail
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Email,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHostDeviceMapping = `-- name: UpsertHostDeviceMapping :exec
INSERT INTO host_emails (
    host_id,
    email,
    source
)
VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (host_id, source) DO UPDATE SET
    email = EXCLUDED.email,
    updated_at = now()
`

type UpsertHostDeviceMappingParams struct {
	HostID int64  `json:"host_id"`
	Email  string `json:"email"`
	Source string `json:"source"`
}

func (q *Queries) UpsertHostDeviceMapping(ctx context.Context, arg UpsertHostDeviceMappingParams) error {
	_, err := q.db.Exec(ctx, upsertHostDeviceMapping, arg.HostID, arg.Email, arg.Source)
	return err
}
