// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: directory.sql

package sqlc

import (
	"context"
	"time"
)

const deleteDirectoryGroupsNotIn = `-- name: DeleteDirectoryGroupsNotIn :exec
DELETE FROM directory_groups
WHERE external_id <> ALL($1::text[])
`

type DeleteDirectoryGroupsNotInParams struct {
	ExternalIds []string `json:"external_ids"`
}

func (q *Queries) DeleteDirectoryGroupsNotIn(ctx context.Context, arg DeleteDirectoryGroupsNotInParams) error {
	_, err := q.db.Exec(ctx, deleteDirectoryGroupsNotIn, arg.ExternalIds)
	return err
}

const deleteDirectoryUserGroups = `-- name: DeleteDirectoryUserGroups :exec
DELETE FROM directory_user_groups
WHERE directory_user_id = $1
`

type DeleteDirectoryUserGroupsParams struct {
	DirectoryUserID int64 `json:"directory_user_id"`
}

func (q *Queries) DeleteDirectoryUserGroups(ctx context.Context, arg DeleteDirectoryUserGroupsParams) error {
	_, err := q.db.Exec(ctx, deleteDirectoryUserGroups, arg.DirectoryUserID)
	return err
}

const deleteDirectoryUsersNotIn = `-- name: DeleteDirectoryUsersNotIn :exec
DELETE FROM directory_users
WHERE external_id <> ALL($1::text[])
`

type DeleteDirectoryUsersNotInParams struct {
	ExternalIds []string `json:"external_ids"`
}

func (q *Queries) DeleteDirectoryUsersNotIn(ctx context.Context, arg DeleteDirectoryUsersNotInParams) error {
	_, err := q.db.Exec(ctx, deleteDirectoryUsersNotIn, arg.ExternalIds)
	return err
}

const insertDirectoryUserGroups = `-- name: InsertDirectoryUserGroups :exec
INSERT INTO directory_user_groups (directory_user_id, directory_group_id)
SELECT $1, g.id
FROM directory_groups g
WHERE g.external_id = ANY($2::text[])
ON CONFLICT DO NOTHING
`

type InsertDirectoryUserGroupsParams struct {
	DirectoryUserID  int64    `json:"directory_user_id"`
	GroupExternalIds []string `json:"group_external_ids"`
}

func (q *Queries) InsertDirectoryUserGroups(ctx context.Context, arg InsertDirectoryUserGroupsParams) error {
	_, err := q.db.Exec(ctx, insertDirectoryUserGroups, arg.DirectoryUserID, arg.GroupExternalIds)
	return err
}

const upsertDirectoryGroup = `-- name: UpsertDirectoryGroup :one
INSERT INTO directory_groups (
    external_id,
    display_name,
    mail_nickname,
    last_synced_at
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (external_id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    mail_nickname = EXCLUDED.mail_nickname,
    last_synced_at = EXCLUDED.last_synced_at,
    updated_at = now()
RETURNING id, external_id, display_name, mail_nickname, last_synced_at, created_at, updated_at
`

type UpsertDirectoryGroupParams struct {
	ExternalID   string    `json:"external_id"`
	DisplayName  string    `json:"display_name"`
	MailNickname *string   `json:"mail_nickname"`
	LastSyncedAt time.Time `json:"last_synced_at"`
}

func (q *Queries) UpsertDirectoryGroup(ctx context.Context, arg UpsertDirectoryGroupParams) (DirectoryGroup, error) {
	row := q.db.QueryRow(ctx, upsertDirectoryGroup,
		arg.ExternalID,
		arg.DisplayName,
		arg.MailNickname,
		arg.LastSyncedAt,
	)
	var i DirectoryGroup
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.DisplayName,
		&i.MailNickname,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDirectoryUser = `-- name: UpsertDirectoryUser :one
INSERT INTO directory_users (
    external_id,
    user_principal_name,
    mail,
    mail_nickname,
    display_name,
    given_name,
    family_name,
    department,
    active,
    last_synced_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
ON CONFLICT (external_id) DO UPDATE SET
    user_principal_name = EXCLUDED.user_principal_name,
    mail = EXCLUDED.mail,
    mail_nickname = EXCLUDED.mail_nickname,
    display_name = EXCLUDED.display_name,
    given_name = EXCLUDED.given_name,
    family_name = EXCLUDED.family_name,
    department = EXCLUDED.department,
    active = EXCLUDED.active,
    last_synced_at = EXCLUDED.last_synced_at,
    updated_at = now()
RETURNING id, external_id, user_principal_name, mail, mail_nickname, display_name, given_name, family_name, department, active, last_synced_at, created_at, updated_at
`

type UpsertDirectoryUserParams struct {
	ExternalID        string    `json:"external_id"`
	UserPrincipalName string    `json:"user_principal_name"`
	Mail              *string   `json:"mail"`
	MailNickname      *string   `json:"mail_nickname"`
	DisplayName       string    `json:"display_name"`
	GivenName         *string   `json:"given_name"`
	FamilyName        *string   `json:"family_name"`
	Department        *string   `json:"department"`
	Active            bool      `json:"active"`
	LastSyncedAt      time.Time `json:"last_synced_at"`
}

func (q *Queries) UpsertDirectoryUser(ctx context.Context, arg UpsertDirectoryUserParams) (DirectoryUser, error) {
	row := q.db.QueryRow(ctx, upsertDirectoryUser,
		arg.ExternalID,
		arg.UserPrincipalName,
		arg.Mail,
		arg.MailNickname,
		arg.DisplayName,
		arg.GivenName,
		arg.FamilyName,
		arg.Department,
		arg.Active,
		arg.LastSyncedAt,
	)
	var i DirectoryUser
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.UserPrincipalName,
		&i.Mail,
		&i.MailNickname,
		&i.DisplayName,
		&i.GivenName,
		&i.FamilyName,
		&i.Department,
		&i.Active,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
