// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: directory.sql

package sqlc

import (
	"context"
)

const deleteDirectoryGroupMembershipsForUser = `-- name: DeleteDirectoryGroupMembershipsForUser :exec
DELETE FROM directory_group_memberships
WHERE user_id = $1
`

type DeleteDirectoryGroupMembershipsForUserParams struct {
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteDirectoryGroupMembershipsForUser(ctx context.Context, arg DeleteDirectoryGroupMembershipsForUserParams) error {
	_, err := q.db.Exec(ctx, deleteDirectoryGroupMembershipsForUser, arg.UserID)
	return err
}

const deleteDirectoryGroupsNotIn = `-- name: DeleteDirectoryGroupsNotIn :exec
DELETE FROM directory_groups
WHERE source = $1::directory_source
  AND external_id <> ALL($2::text[])
`

type DeleteDirectoryGroupsNotInParams struct {
	Source      DirectorySource `json:"source"`
	ExternalIds []string        `json:"external_ids"`
}

func (q *Queries) DeleteDirectoryGroupsNotIn(ctx context.Context, arg DeleteDirectoryGroupsNotInParams) error {
	_, err := q.db.Exec(ctx, deleteDirectoryGroupsNotIn, arg.Source, arg.ExternalIds)
	return err
}

const deleteHostUserAffinityMapping = `-- name: DeleteHostUserAffinityMapping :exec
DELETE FROM host_user_affinity_mappings
WHERE host_id = $1
  AND source = $2
`

type DeleteHostUserAffinityMappingParams struct {
	HostID int64                  `json:"host_id"`
	Source HostUserAffinitySource `json:"source"`
}

func (q *Queries) DeleteHostUserAffinityMapping(ctx context.Context, arg DeleteHostUserAffinityMappingParams) error {
	_, err := q.db.Exec(ctx, deleteHostUserAffinityMapping, arg.HostID, arg.Source)
	return err
}

const insertDirectoryGroupMemberships = `-- name: InsertDirectoryGroupMemberships :exec
INSERT INTO directory_group_memberships (user_id, group_id)
SELECT $1, g.id
FROM directory_groups g
WHERE g.source = $2::directory_source
  AND g.external_id = ANY($3::text[])
ON CONFLICT DO NOTHING
`

type InsertDirectoryGroupMembershipsParams struct {
	UserID           int64           `json:"user_id"`
	Source           DirectorySource `json:"source"`
	GroupExternalIds []string        `json:"group_external_ids"`
}

func (q *Queries) InsertDirectoryGroupMemberships(ctx context.Context, arg InsertDirectoryGroupMembershipsParams) error {
	_, err := q.db.Exec(ctx, insertDirectoryGroupMemberships, arg.UserID, arg.Source, arg.GroupExternalIds)
	return err
}

const listHostUserAffinityMappings = `-- name: ListHostUserAffinityMappings :many
SELECT id, host_id, email, source, created_at, updated_at
FROM host_user_affinity_mappings
WHERE host_id = $1
ORDER BY CASE source
    WHEN 'manual' THEN 0
    WHEN 'orbit_profile' THEN 1
    WHEN 'santa_primary_user' THEN 1
    ELSE 10
END, source
`

type ListHostUserAffinityMappingsParams struct {
	HostID int64 `json:"host_id"`
}

func (q *Queries) ListHostUserAffinityMappings(ctx context.Context, arg ListHostUserAffinityMappingsParams) ([]HostUserAffinityMapping, error) {
	rows, err := q.db.Query(ctx, listHostUserAffinityMappings, arg.HostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostUserAffinityMapping{}
	for rows.Next() {
		var i HostUserAffinityMapping
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Email,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostUserAffinityMappingsForHosts = `-- name: ListHostUserAffinityMappingsForHosts :many
SELECT id, host_id, email, source, created_at, updated_at
FROM host_user_affinity_mappings
WHERE host_id = ANY($1::bigint[])
ORDER BY host_id, CASE source
    WHEN 'manual' THEN 0
    WHEN 'orbit_profile' THEN 1
    WHEN 'santa_primary_user' THEN 1
    ELSE 10
END, source
`

type ListHostUserAffinityMappingsForHostsParams struct {
	HostIds []int64 `json:"host_ids"`
}

func (q *Queries) ListHostUserAffinityMappingsForHosts(ctx context.Context, arg ListHostUserAffinityMappingsForHostsParams) ([]HostUserAffinityMapping, error) {
	rows, err := q.db.Query(ctx, listHostUserAffinityMappingsForHosts, arg.HostIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostUserAffinityMapping{}
	for rows.Next() {
		var i HostUserAffinityMapping
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Email,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostUserAffinityPrimaries = `-- name: ListHostUserAffinityPrimaries :many
WITH primary_mapping AS (
    SELECT DISTINCT ON (he.host_id) he.host_id, he.email, he.source::text AS source
    FROM host_user_affinity_mappings he
    WHERE he.host_id = ANY($1::bigint[])
    ORDER BY he.host_id, CASE he.source
        WHEN 'manual' THEN 0
        WHEN 'orbit_profile' THEN 1
        WHEN 'santa_primary_user' THEN 1
        ELSE 10
    END, he.source
)
SELECT
    pm.host_id,
    pm.email,
    pm.source,
    COALESCE(u.mail_nickname, '') AS username,
    COALESCE(u.name, '') AS name,
    COALESCE(u.department, '') AS department,
    COALESCE(
        array_agg(eg.display_name ORDER BY lower(eg.display_name)) FILTER (WHERE eg.id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS groups
FROM primary_mapping pm
LEFT JOIN host_user_links hul ON hul.host_id = pm.host_id
LEFT JOIN users u ON u.id = hul.user_id AND u.deleted_at IS NULL
LEFT JOIN directory_group_memberships egm ON egm.user_id = u.id
LEFT JOIN directory_groups eg ON eg.id = egm.group_id
GROUP BY pm.host_id, pm.email, pm.source, u.mail_nickname, u.name, u.department
ORDER BY pm.host_id
`

type ListHostUserAffinityPrimariesParams struct {
	HostIds []int64 `json:"host_ids"`
}

type ListHostUserAffinityPrimariesRow struct {
	HostID     int64    `json:"host_id"`
	Email      string   `json:"email"`
	Source     string   `json:"source"`
	Username   string   `json:"username"`
	Name       string   `json:"name"`
	Department string   `json:"department"`
	Groups     []string `json:"groups"`
}

func (q *Queries) ListHostUserAffinityPrimaries(ctx context.Context, arg ListHostUserAffinityPrimariesParams) ([]ListHostUserAffinityPrimariesRow, error) {
	rows, err := q.db.Query(ctx, listHostUserAffinityPrimaries, arg.HostIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHostUserAffinityPrimariesRow{}
	for rows.Next() {
		var i ListHostUserAffinityPrimariesRow
		if err := rows.Scan(
			&i.HostID,
			&i.Email,
			&i.Source,
			&i.Username,
			&i.Name,
			&i.Department,
			&i.Groups,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadHostUserAffinityPrimary = `-- name: LoadHostUserAffinityPrimary :one
WITH primary_mapping AS (
    SELECT he.host_id, he.email, he.source::text AS source
    FROM host_user_affinity_mappings he
    WHERE he.host_id = $1
    ORDER BY CASE he.source
        WHEN 'manual' THEN 0
        WHEN 'orbit_profile' THEN 1
        WHEN 'santa_primary_user' THEN 1
        ELSE 10
    END, he.source
    LIMIT 1
)
SELECT
    pm.email,
    pm.source,
    COALESCE(u.mail_nickname, '') AS username,
    COALESCE(u.name, '') AS name,
    COALESCE(u.department, '') AS department,
    COALESCE(
        array_agg(eg.display_name ORDER BY lower(eg.display_name)) FILTER (WHERE eg.id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS groups
FROM primary_mapping pm
LEFT JOIN host_user_links hul ON hul.host_id = pm.host_id
LEFT JOIN users u ON u.id = hul.user_id AND u.deleted_at IS NULL
LEFT JOIN directory_group_memberships egm ON egm.user_id = u.id
LEFT JOIN directory_groups eg ON eg.id = egm.group_id
GROUP BY pm.email, pm.source, u.mail_nickname, u.name, u.department
`

type LoadHostUserAffinityPrimaryParams struct {
	AffinityHostID int64 `json:"affinity_host_id"`
}

type LoadHostUserAffinityPrimaryRow struct {
	Email      string   `json:"email"`
	Source     string   `json:"source"`
	Username   string   `json:"username"`
	Name       string   `json:"name"`
	Department string   `json:"department"`
	Groups     []string `json:"groups"`
}

func (q *Queries) LoadHostUserAffinityPrimary(ctx context.Context, arg LoadHostUserAffinityPrimaryParams) (LoadHostUserAffinityPrimaryRow, error) {
	row := q.db.QueryRow(ctx, loadHostUserAffinityPrimary, arg.AffinityHostID)
	var i LoadHostUserAffinityPrimaryRow
	err := row.Scan(
		&i.Email,
		&i.Source,
		&i.Username,
		&i.Name,
		&i.Department,
		&i.Groups,
	)
	return i, err
}

const reconcileHostUserLinks = `-- name: ReconcileHostUserLinks :exec
INSERT INTO host_user_links (host_id, user_id, source)
SELECT host_id, user_id, 'reported_user_affinity'::host_user_link_source
FROM (
    SELECT DISTINCT ON (he.host_id)
        he.host_id,
        u.id AS user_id
    FROM host_user_affinity_mappings he
    INNER JOIN users u
        ON lower(u.email) = lower(he.email)
        OR lower(COALESCE(u.user_principal_name, '')) = lower(he.email)
    WHERE he.source::text = ANY($1::text[])
      AND u.deleted_at IS NULL
    ORDER BY he.host_id, CASE he.source
        WHEN 'orbit_profile' THEN 0
        WHEN 'santa_primary_user' THEN 0
        ELSE 10
    END, he.source
) preferred
ON CONFLICT (host_id) DO UPDATE SET
    user_id = EXCLUDED.user_id,
    source = 'reported_user_affinity',
    updated_at = now()
WHERE host_user_links.source <> 'manual'
`

type ReconcileHostUserLinksParams struct {
	AffinitySources []string `json:"affinity_sources"`
}

func (q *Queries) ReconcileHostUserLinks(ctx context.Context, arg ReconcileHostUserLinksParams) error {
	_, err := q.db.Exec(ctx, reconcileHostUserLinks, arg.AffinitySources)
	return err
}

const upsertDirectoryGroup = `-- name: UpsertDirectoryGroup :one
INSERT INTO directory_groups (
    source,
    external_id,
    display_name,
    mail_nickname
)
VALUES (
    $1::directory_source,
    $2,
    $3,
    $4
)
ON CONFLICT (source, external_id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    mail_nickname = EXCLUDED.mail_nickname,
    updated_at = now()
RETURNING id, source, external_id, display_name, mail_nickname, created_at, updated_at
`

type UpsertDirectoryGroupParams struct {
	Source       DirectorySource `json:"source"`
	ExternalID   string          `json:"external_id"`
	DisplayName  string          `json:"display_name"`
	MailNickname *string         `json:"mail_nickname"`
}

func (q *Queries) UpsertDirectoryGroup(ctx context.Context, arg UpsertDirectoryGroupParams) (DirectoryGroup, error) {
	row := q.db.QueryRow(ctx, upsertDirectoryGroup,
		arg.Source,
		arg.ExternalID,
		arg.DisplayName,
		arg.MailNickname,
	)
	var i DirectoryGroup
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.DisplayName,
		&i.MailNickname,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertHostUserAffinityMapping = `-- name: UpsertHostUserAffinityMapping :exec
INSERT INTO host_user_affinity_mappings (
    host_id,
    email,
    source
)
VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (host_id, source) DO UPDATE SET
    email = EXCLUDED.email,
    updated_at = now()
`

type UpsertHostUserAffinityMappingParams struct {
	HostID int64                  `json:"host_id"`
	Email  string                 `json:"email"`
	Source HostUserAffinitySource `json:"source"`
}

func (q *Queries) UpsertHostUserAffinityMapping(ctx context.Context, arg UpsertHostUserAffinityMappingParams) error {
	_, err := q.db.Exec(ctx, upsertHostUserAffinityMapping, arg.HostID, arg.Email, arg.Source)
	return err
}
