// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enroll_secrets.sql

package sqlc

import (
	"context"
)

const createEnrollSecret = `-- name: CreateEnrollSecret :one
INSERT INTO enroll_secrets (
    value
)
VALUES (
    $1
)
RETURNING id, value, created_at, deleted_at
`

type CreateEnrollSecretParams struct {
	Value string `json:"value"`
}

func (q *Queries) CreateEnrollSecret(ctx context.Context, arg CreateEnrollSecretParams) (EnrollSecret, error) {
	row := q.db.QueryRow(ctx, createEnrollSecret, arg.Value)
	var i EnrollSecret
	err := row.Scan(
		&i.ID,
		&i.Value,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteEnrollSecret = `-- name: DeleteEnrollSecret :one
UPDATE enroll_secrets
SET deleted_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id
`

type DeleteEnrollSecretParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) DeleteEnrollSecret(ctx context.Context, arg DeleteEnrollSecretParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteEnrollSecret, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const hasActiveEnrollSecret = `-- name: HasActiveEnrollSecret :one
SELECT EXISTS (
    SELECT 1
    FROM enroll_secrets
    WHERE value = $1
      AND deleted_at IS NULL
)
`

type HasActiveEnrollSecretParams struct {
	Value string `json:"value"`
}

func (q *Queries) HasActiveEnrollSecret(ctx context.Context, arg HasActiveEnrollSecretParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveEnrollSecret, arg.Value)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listEnrollSecrets = `-- name: ListEnrollSecrets :many
SELECT id, value, created_at, deleted_at
FROM enroll_secrets
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListEnrollSecrets(ctx context.Context) ([]EnrollSecret, error) {
	rows, err := q.db.Query(ctx, listEnrollSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnrollSecret{}
	for rows.Next() {
		var i EnrollSecret
		if err := rows.Scan(
			&i.ID,
			&i.Value,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
