// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: host_user_affinity.sql

package sqlc

import (
	"context"
)

const deleteHostUserAffinityMapping = `-- name: DeleteHostUserAffinityMapping :exec
DELETE FROM host_user_affinity_mappings
WHERE host_id = $1
  AND source = $2
`

type DeleteHostUserAffinityMappingParams struct {
	HostID int64                  `json:"host_id"`
	Source HostUserAffinitySource `json:"source"`
}

func (q *Queries) DeleteHostUserAffinityMapping(ctx context.Context, arg DeleteHostUserAffinityMappingParams) error {
	_, err := q.db.Exec(ctx, deleteHostUserAffinityMapping, arg.HostID, arg.Source)
	return err
}

const listHostUserAffinityMappings = `-- name: ListHostUserAffinityMappings :many
SELECT id, host_id, email, source, created_at, updated_at
FROM host_user_affinity_mappings
WHERE host_id = $1
ORDER BY CASE source
    WHEN 'manual' THEN 0
    WHEN 'orbit_profile' THEN 1
    WHEN 'santa_primary_user' THEN 1
    ELSE 10
END, source
`

type ListHostUserAffinityMappingsParams struct {
	HostID int64 `json:"host_id"`
}

func (q *Queries) ListHostUserAffinityMappings(ctx context.Context, arg ListHostUserAffinityMappingsParams) ([]HostUserAffinityMapping, error) {
	rows, err := q.db.Query(ctx, listHostUserAffinityMappings, arg.HostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostUserAffinityMapping{}
	for rows.Next() {
		var i HostUserAffinityMapping
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Email,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostUserAffinityMappingsForHosts = `-- name: ListHostUserAffinityMappingsForHosts :many
SELECT id, host_id, email, source, created_at, updated_at
FROM host_user_affinity_mappings
WHERE host_id = ANY($1::bigint[])
ORDER BY host_id, CASE source
    WHEN 'manual' THEN 0
    WHEN 'orbit_profile' THEN 1
    WHEN 'santa_primary_user' THEN 1
    ELSE 10
END, source
`

type ListHostUserAffinityMappingsForHostsParams struct {
	HostIds []int64 `json:"host_ids"`
}

func (q *Queries) ListHostUserAffinityMappingsForHosts(ctx context.Context, arg ListHostUserAffinityMappingsForHostsParams) ([]HostUserAffinityMapping, error) {
	rows, err := q.db.Query(ctx, listHostUserAffinityMappingsForHosts, arg.HostIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostUserAffinityMapping{}
	for rows.Next() {
		var i HostUserAffinityMapping
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Email,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadHostUserAffinityPrimary = `-- name: LoadHostUserAffinityPrimary :one
WITH primary_mapping AS (
    SELECT he.host_id, he.email, he.source::text AS source
    FROM host_user_affinity_mappings he
    WHERE he.host_id = $1
    ORDER BY CASE he.source
        WHEN 'manual' THEN 0
        WHEN 'orbit_profile' THEN 1
        WHEN 'santa_primary_user' THEN 1
        ELSE 10
    END, he.source
    LIMIT 1
)
SELECT
    pm.email,
    pm.source,
    COALESCE(du.mail_nickname, '') AS username,
    COALESCE(du.display_name, '') AS name,
    COALESCE(du.department, '') AS department,
    COALESCE(
        array_agg(dg.display_name ORDER BY lower(dg.display_name)) FILTER (WHERE dg.id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS groups
FROM primary_mapping pm
LEFT JOIN host_directory_user hdu ON hdu.host_id = pm.host_id
LEFT JOIN directory_users du ON du.id = hdu.directory_user_id AND du.active
LEFT JOIN directory_user_groups dug ON dug.directory_user_id = du.id
LEFT JOIN directory_groups dg ON dg.id = dug.directory_group_id
GROUP BY pm.email, pm.source, du.mail_nickname, du.display_name, du.department
`

type LoadHostUserAffinityPrimaryParams struct {
	AffinityHostID int64 `json:"affinity_host_id"`
}

type LoadHostUserAffinityPrimaryRow struct {
	Email      string   `json:"email"`
	Source     string   `json:"source"`
	Username   string   `json:"username"`
	Name       string   `json:"name"`
	Department string   `json:"department"`
	Groups     []string `json:"groups"`
}

func (q *Queries) LoadHostUserAffinityPrimary(ctx context.Context, arg LoadHostUserAffinityPrimaryParams) (LoadHostUserAffinityPrimaryRow, error) {
	row := q.db.QueryRow(ctx, loadHostUserAffinityPrimary, arg.AffinityHostID)
	var i LoadHostUserAffinityPrimaryRow
	err := row.Scan(
		&i.Email,
		&i.Source,
		&i.Username,
		&i.Name,
		&i.Department,
		&i.Groups,
	)
	return i, err
}

const upsertHostUserAffinityMapping = `-- name: UpsertHostUserAffinityMapping :exec
INSERT INTO host_user_affinity_mappings (
    host_id,
    email,
    source
)
VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (host_id, source) DO UPDATE SET
    email = EXCLUDED.email,
    updated_at = now()
`

type UpsertHostUserAffinityMappingParams struct {
	HostID int64                  `json:"host_id"`
	Email  string                 `json:"email"`
	Source HostUserAffinitySource `json:"source"`
}

func (q *Queries) UpsertHostUserAffinityMapping(ctx context.Context, arg UpsertHostUserAffinityMappingParams) error {
	_, err := q.db.Exec(ctx, upsertHostUserAffinityMapping, arg.HostID, arg.Email, arg.Source)
	return err
}
