// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: labels.sql

package sqlc

import (
	"context"
)

const countLabels = `-- name: CountLabels :one
SELECT count(*)::integer
FROM labels l
WHERE
    ($1::text = '' OR l.name ILIKE '%' || $1::text || '%' OR l.description ILIKE '%' || $1::text || '%')
    AND ($2::text = '' OR l.kind = $2::text)
    AND ($3::text = '' OR l.membership_type = $3::text)
    AND ($4::text = '' OR l.platform = $4::text)
`

type CountLabelsParams struct {
	Q              string `json:"q"`
	Kind           string `json:"kind"`
	MembershipType string `json:"membership_type"`
	Platform       string `json:"platform"`
}

func (q *Queries) CountLabels(ctx context.Context, arg CountLabelsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countLabels,
		arg.Q,
		arg.Kind,
		arg.MembershipType,
		arg.Platform,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createLabel = `-- name: CreateLabel :one
INSERT INTO labels (
    name,
    description,
    query,
    kind,
    membership_type,
    platform
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, name, description, query, kind, membership_type, platform, created_at, updated_at
`

type CreateLabelParams struct {
	Name           string  `json:"name"`
	Description    string  `json:"description"`
	Query          *string `json:"query"`
	Kind           string  `json:"kind"`
	MembershipType string  `json:"membership_type"`
	Platform       *string `json:"platform"`
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error) {
	row := q.db.QueryRow(ctx, createLabel,
		arg.Name,
		arg.Description,
		arg.Query,
		arg.Kind,
		arg.MembershipType,
		arg.Platform,
	)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Query,
		&i.Kind,
		&i.MembershipType,
		&i.Platform,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLabelMembership = `-- name: DeleteLabelMembership :exec
DELETE FROM label_membership
WHERE label_id = $1 AND host_id = $2
`

type DeleteLabelMembershipParams struct {
	LabelID int64 `json:"label_id"`
	HostID  int64 `json:"host_id"`
}

func (q *Queries) DeleteLabelMembership(ctx context.Context, arg DeleteLabelMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteLabelMembership, arg.LabelID, arg.HostID)
	return err
}

const deleteRegularLabel = `-- name: DeleteRegularLabel :one
DELETE FROM labels
WHERE id = $1 AND kind = 'regular'
RETURNING id
`

type DeleteRegularLabelParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) DeleteRegularLabel(ctx context.Context, arg DeleteRegularLabelParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteRegularLabel, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getLabelByID = `-- name: GetLabelByID :one
SELECT
    l.id, l.name, l.description, l.query, l.kind, l.membership_type, l.platform, l.created_at, l.updated_at,
    count(lm.host_id)::integer AS hosts_count
FROM labels l
LEFT JOIN label_membership lm ON lm.label_id = l.id
WHERE l.id = $1
GROUP BY l.id
`

type GetLabelByIDParams struct {
	ID int64 `json:"id"`
}

type GetLabelByIDRow struct {
	Label      Label `json:"label"`
	HostsCount int32 `json:"hosts_count"`
}

func (q *Queries) GetLabelByID(ctx context.Context, arg GetLabelByIDParams) (GetLabelByIDRow, error) {
	row := q.db.QueryRow(ctx, getLabelByID, arg.ID)
	var i GetLabelByIDRow
	err := row.Scan(
		&i.Label.ID,
		&i.Label.Name,
		&i.Label.Description,
		&i.Label.Query,
		&i.Label.Kind,
		&i.Label.MembershipType,
		&i.Label.Platform,
		&i.Label.CreatedAt,
		&i.Label.UpdatedAt,
		&i.HostsCount,
	)
	return i, err
}

const listApplicableDynamicLabelIDs = `-- name: ListApplicableDynamicLabelIDs :many
SELECT id
FROM labels
WHERE
    id = ANY($1::bigint[])
    AND membership_type = 'dynamic'
    AND (platform IS NULL OR platform = '' OR platform = $2::text)
ORDER BY id
`

type ListApplicableDynamicLabelIDsParams struct {
	Ids      []int64 `json:"ids"`
	Platform string  `json:"platform"`
}

func (q *Queries) ListApplicableDynamicLabelIDs(ctx context.Context, arg ListApplicableDynamicLabelIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listApplicableDynamicLabelIDs, arg.Ids, arg.Platform)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicableDynamicLabels = `-- name: ListApplicableDynamicLabels :many
SELECT id, name, description, query, kind, membership_type, platform, created_at, updated_at
FROM labels
WHERE
    membership_type = 'dynamic'
    AND (platform IS NULL OR platform = '' OR platform = $1::text)
ORDER BY id
`

type ListApplicableDynamicLabelsParams struct {
	Platform string `json:"platform"`
}

func (q *Queries) ListApplicableDynamicLabels(ctx context.Context, arg ListApplicableDynamicLabelsParams) ([]Label, error) {
	rows, err := q.db.Query(ctx, listApplicableDynamicLabels, arg.Platform)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Label{}
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Query,
			&i.Kind,
			&i.MembershipType,
			&i.Platform,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabels = `-- name: ListLabels :many
SELECT
    l.id, l.name, l.description, l.query, l.kind, l.membership_type, l.platform, l.created_at, l.updated_at,
    count(lm.host_id)::integer AS hosts_count
FROM labels l
LEFT JOIN label_membership lm ON lm.label_id = l.id
WHERE
    ($1::text = '' OR l.name ILIKE '%' || $1::text || '%' OR l.description ILIKE '%' || $1::text || '%')
    AND ($2::text = '' OR l.kind = $2::text)
    AND ($3::text = '' OR l.membership_type = $3::text)
    AND ($4::text = '' OR l.platform = $4::text)
GROUP BY l.id
ORDER BY
    CASE WHEN $5::text = 'name' AND $6::text = 'desc' THEN lower(l.name) END DESC,
    CASE WHEN $5::text = 'kind' AND $6::text = 'asc' THEN l.kind END ASC,
    CASE WHEN $5::text = 'kind' AND $6::text = 'desc' THEN l.kind END DESC,
    CASE WHEN $5::text = 'membership_type' AND $6::text = 'asc' THEN l.membership_type END ASC,
    CASE WHEN $5::text = 'membership_type' AND $6::text = 'desc' THEN l.membership_type END DESC,
    CASE WHEN $5::text = 'platform' AND $6::text = 'asc' THEN l.platform END ASC NULLS LAST,
    CASE WHEN $5::text = 'platform' AND $6::text = 'desc' THEN l.platform END DESC NULLS LAST,
    CASE WHEN $5::text = 'hosts_count' AND $6::text = 'asc' THEN count(lm.host_id) END ASC,
    CASE WHEN $5::text = 'hosts_count' AND $6::text = 'desc' THEN count(lm.host_id) END DESC,
    CASE WHEN $5::text = 'updated_at' AND $6::text = 'asc' THEN l.updated_at END ASC,
    CASE WHEN $5::text = 'updated_at' AND $6::text = 'desc' THEN l.updated_at END DESC,
    lower(l.name),
    l.id
LIMIT $8 OFFSET $7
`

type ListLabelsParams struct {
	Q              string `json:"q"`
	Kind           string `json:"kind"`
	MembershipType string `json:"membership_type"`
	Platform       string `json:"platform"`
	OrderKey       string `json:"order_key"`
	OrderDirection string `json:"order_direction"`
	OffsetRows     int32  `json:"offset_rows"`
	LimitRows      int32  `json:"limit_rows"`
}

type ListLabelsRow struct {
	Label      Label `json:"label"`
	HostsCount int32 `json:"hosts_count"`
}

func (q *Queries) ListLabels(ctx context.Context, arg ListLabelsParams) ([]ListLabelsRow, error) {
	rows, err := q.db.Query(ctx, listLabels,
		arg.Q,
		arg.Kind,
		arg.MembershipType,
		arg.Platform,
		arg.OrderKey,
		arg.OrderDirection,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLabelsRow{}
	for rows.Next() {
		var i ListLabelsRow
		if err := rows.Scan(
			&i.Label.ID,
			&i.Label.Name,
			&i.Label.Description,
			&i.Label.Query,
			&i.Label.Kind,
			&i.Label.MembershipType,
			&i.Label.Platform,
			&i.Label.CreatedAt,
			&i.Label.UpdatedAt,
			&i.HostsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabelsForHost = `-- name: ListLabelsForHost :many
SELECT
    l.id, l.name, l.description, l.query, l.kind, l.membership_type, l.platform, l.created_at, l.updated_at,
    count(lm_all.host_id)::integer AS hosts_count
FROM labels l
JOIN label_membership lm_host ON lm_host.label_id = l.id AND lm_host.host_id = $1
LEFT JOIN label_membership lm_all ON lm_all.label_id = l.id
GROUP BY l.id
ORDER BY lower(l.name), l.id
`

type ListLabelsForHostParams struct {
	HostID int64 `json:"host_id"`
}

type ListLabelsForHostRow struct {
	Label      Label `json:"label"`
	HostsCount int32 `json:"hosts_count"`
}

func (q *Queries) ListLabelsForHost(ctx context.Context, arg ListLabelsForHostParams) ([]ListLabelsForHostRow, error) {
	rows, err := q.db.Query(ctx, listLabelsForHost, arg.HostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLabelsForHostRow{}
	for rows.Next() {
		var i ListLabelsForHostRow
		if err := rows.Scan(
			&i.Label.ID,
			&i.Label.Name,
			&i.Label.Description,
			&i.Label.Query,
			&i.Label.Kind,
			&i.Label.MembershipType,
			&i.Label.Platform,
			&i.Label.CreatedAt,
			&i.Label.UpdatedAt,
			&i.HostsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markHostLabelsFresh = `-- name: MarkHostLabelsFresh :exec
UPDATE hosts
SET label_updated_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type MarkHostLabelsFreshParams struct {
	HostID int64 `json:"host_id"`
}

func (q *Queries) MarkHostLabelsFresh(ctx context.Context, arg MarkHostLabelsFreshParams) error {
	_, err := q.db.Exec(ctx, markHostLabelsFresh, arg.HostID)
	return err
}

const updateLabel = `-- name: UpdateLabel :one
UPDATE labels
SET
    name = $1,
    description = $2,
    query = $3,
    membership_type = $4,
    platform = $5,
    updated_at = now()
WHERE id = $6 AND kind = 'regular'
RETURNING id, name, description, query, kind, membership_type, platform, created_at, updated_at
`

type UpdateLabelParams struct {
	Name           string  `json:"name"`
	Description    string  `json:"description"`
	Query          *string `json:"query"`
	MembershipType string  `json:"membership_type"`
	Platform       *string `json:"platform"`
	ID             int64   `json:"id"`
}

func (q *Queries) UpdateLabel(ctx context.Context, arg UpdateLabelParams) (Label, error) {
	row := q.db.QueryRow(ctx, updateLabel,
		arg.Name,
		arg.Description,
		arg.Query,
		arg.MembershipType,
		arg.Platform,
		arg.ID,
	)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Query,
		&i.Kind,
		&i.MembershipType,
		&i.Platform,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertLabelMembership = `-- name: UpsertLabelMembership :exec
INSERT INTO label_membership (label_id, host_id)
VALUES ($1, $2)
ON CONFLICT (label_id, host_id) DO UPDATE SET
    updated_at = now()
`

type UpsertLabelMembershipParams struct {
	LabelID int64 `json:"label_id"`
	HostID  int64 `json:"host_id"`
}

func (q *Queries) UpsertLabelMembership(ctx context.Context, arg UpsertLabelMembershipParams) error {
	_, err := q.db.Exec(ctx, upsertLabelMembership, arg.LabelID, arg.HostID)
	return err
}
