// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: munki_software.sql

package sqlc

import (
	"context"
	"time"
)

const countMunkiSoftware = `-- name: CountMunkiSoftware :one
SELECT COUNT(*)::integer
FROM munki_software
`

func (q *Queries) CountMunkiSoftware(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countMunkiSoftware)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createMunkiSoftware = `-- name: CreateMunkiSoftware :one
INSERT INTO munki_software (
    name,
    description,
    category,
    developer,
    icon_name,
    icon_hash,
    icon_artifact_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7::bigint
)
RETURNING id, name, description, category, developer, icon_name, icon_hash, icon_artifact_id, created_at, updated_at
`

type CreateMunkiSoftwareParams struct {
	Name           string `json:"name"`
	Description    string `json:"description"`
	Category       string `json:"category"`
	Developer      string `json:"developer"`
	IconName       string `json:"icon_name"`
	IconHash       string `json:"icon_hash"`
	IconArtifactID *int64 `json:"icon_artifact_id"`
}

func (q *Queries) CreateMunkiSoftware(ctx context.Context, arg CreateMunkiSoftwareParams) (MunkiSoftware, error) {
	row := q.db.QueryRow(ctx, createMunkiSoftware,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Developer,
		arg.IconName,
		arg.IconHash,
		arg.IconArtifactID,
	)
	var i MunkiSoftware
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Developer,
		&i.IconName,
		&i.IconHash,
		&i.IconArtifactID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMunkiSoftwareInclude = `-- name: CreateMunkiSoftwareInclude :one
INSERT INTO munki_software_targets (
    software_id,
    direction,
    position,
    label_id,
    action,
    optional_install,
    featured_item,
    package_selection,
    pinned_package_id
)
VALUES (
    $1,
    'include',
    ($2)::integer - 1,
    $3,
    $4::munki_software_action,
    $5::boolean,
    $6::boolean,
    $7::munki_package_selection,
    $8::bigint
)
RETURNING software_id, direction, position, label_id, action, optional_install, featured_item, package_selection, pinned_package_id, created_at, updated_at
`

type CreateMunkiSoftwareIncludeParams struct {
	SoftwareID       int64                 `json:"software_id"`
	Priority         int32                 `json:"priority"`
	LabelID          int64                 `json:"label_id"`
	Action           MunkiSoftwareAction   `json:"action"`
	OptionalInstall  bool                  `json:"optional_install"`
	FeaturedItem     bool                  `json:"featured_item"`
	PackageSelection MunkiPackageSelection `json:"package_selection"`
	PinnedPackageID  *int64                `json:"pinned_package_id"`
}

func (q *Queries) CreateMunkiSoftwareInclude(ctx context.Context, arg CreateMunkiSoftwareIncludeParams) (MunkiSoftwareTarget, error) {
	row := q.db.QueryRow(ctx, createMunkiSoftwareInclude,
		arg.SoftwareID,
		arg.Priority,
		arg.LabelID,
		arg.Action,
		arg.OptionalInstall,
		arg.FeaturedItem,
		arg.PackageSelection,
		arg.PinnedPackageID,
	)
	var i MunkiSoftwareTarget
	err := row.Scan(
		&i.SoftwareID,
		&i.Direction,
		&i.Position,
		&i.LabelID,
		&i.Action,
		&i.OptionalInstall,
		&i.FeaturedItem,
		&i.PackageSelection,
		&i.PinnedPackageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMunkiSoftwareByID = `-- name: DeleteMunkiSoftwareByID :one
DELETE FROM munki_software
WHERE id = $1
RETURNING id
`

type DeleteMunkiSoftwareByIDParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) DeleteMunkiSoftwareByID(ctx context.Context, arg DeleteMunkiSoftwareByIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteMunkiSoftwareByID, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteMunkiSoftwareByIDs = `-- name: DeleteMunkiSoftwareByIDs :many
DELETE FROM munki_software
WHERE id = ANY($1::bigint[])
RETURNING id
`

type DeleteMunkiSoftwareByIDsParams struct {
	Ids []int64 `json:"ids"`
}

func (q *Queries) DeleteMunkiSoftwareByIDs(ctx context.Context, arg DeleteMunkiSoftwareByIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, deleteMunkiSoftwareByIDs, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteMunkiSoftwareExcludeLabels = `-- name: DeleteMunkiSoftwareExcludeLabels :exec
DELETE FROM munki_software_targets
WHERE software_id = $1
  AND direction = 'exclude'
`

type DeleteMunkiSoftwareExcludeLabelsParams struct {
	SoftwareID int64 `json:"software_id"`
}

func (q *Queries) DeleteMunkiSoftwareExcludeLabels(ctx context.Context, arg DeleteMunkiSoftwareExcludeLabelsParams) error {
	_, err := q.db.Exec(ctx, deleteMunkiSoftwareExcludeLabels, arg.SoftwareID)
	return err
}

const deleteMunkiSoftwareTargetsBySoftware = `-- name: DeleteMunkiSoftwareTargetsBySoftware :exec
DELETE FROM munki_software_targets
WHERE software_id = $1
`

type DeleteMunkiSoftwareTargetsBySoftwareParams struct {
	SoftwareID int64 `json:"software_id"`
}

func (q *Queries) DeleteMunkiSoftwareTargetsBySoftware(ctx context.Context, arg DeleteMunkiSoftwareTargetsBySoftwareParams) error {
	_, err := q.db.Exec(ctx, deleteMunkiSoftwareTargetsBySoftware, arg.SoftwareID)
	return err
}

const deleteMunkiSoftwareTargetsBySoftwareIDs = `-- name: DeleteMunkiSoftwareTargetsBySoftwareIDs :exec
DELETE FROM munki_software_targets
WHERE software_id = ANY($1::bigint[])
`

type DeleteMunkiSoftwareTargetsBySoftwareIDsParams struct {
	Ids []int64 `json:"ids"`
}

func (q *Queries) DeleteMunkiSoftwareTargetsBySoftwareIDs(ctx context.Context, arg DeleteMunkiSoftwareTargetsBySoftwareIDsParams) error {
	_, err := q.db.Exec(ctx, deleteMunkiSoftwareTargetsBySoftwareIDs, arg.Ids)
	return err
}

const getMunkiSoftwareByID = `-- name: GetMunkiSoftwareByID :one
SELECT id, name, description, category, developer, icon_name, icon_hash, icon_artifact_id, created_at, updated_at
FROM munki_software
WHERE id = $1
`

type GetMunkiSoftwareByIDParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) GetMunkiSoftwareByID(ctx context.Context, arg GetMunkiSoftwareByIDParams) (MunkiSoftware, error) {
	row := q.db.QueryRow(ctx, getMunkiSoftwareByID, arg.ID)
	var i MunkiSoftware
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Developer,
		&i.IconName,
		&i.IconHash,
		&i.IconArtifactID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMunkiSoftwareExcludeLabels = `-- name: InsertMunkiSoftwareExcludeLabels :exec
INSERT INTO munki_software_targets (software_id, direction, position, label_id)
SELECT $1, 'exclude', labels.position - 1, labels.label_id
FROM unnest($2::bigint[]) WITH ORDINALITY AS labels(label_id, position)
`

type InsertMunkiSoftwareExcludeLabelsParams struct {
	SoftwareID int64   `json:"software_id"`
	LabelIds   []int64 `json:"label_ids"`
}

func (q *Queries) InsertMunkiSoftwareExcludeLabels(ctx context.Context, arg InsertMunkiSoftwareExcludeLabelsParams) error {
	_, err := q.db.Exec(ctx, insertMunkiSoftwareExcludeLabels, arg.SoftwareID, arg.LabelIds)
	return err
}

const listEffectiveMunkiPackagesForHost = `-- name: ListEffectiveMunkiPackagesForHost :many
SELECT
    (a.position + 1)::bigint AS target_id,
    a.software_id AS target_software_id,
    a.action::munki_software_action AS action,
    a.optional_install::boolean AS optional_install,
    a.featured_item::boolean AS featured_item,
    a.package_selection::munki_package_selection AS package_selection,
    a.pinned_package_id,
    (a.position + 1)::integer AS priority,
    COALESCE(p.id, 0)::bigint AS package_id,
    COALESCE(p.software_id, a.software_id)::bigint AS software_id,
    s.name AS software_name,
    s.description AS software_description,
    s.category AS software_category,
    s.developer AS software_developer,
    s.icon_name AS software_icon_name,
    s.icon_hash AS software_icon_hash,
    s.icon_artifact_id AS software_icon_artifact_id,
    COALESCE(p.version, '') AS version,
    COALESCE(p.installer_type, 'pkg') AS installer_type,
    COALESCE(p.uninstall_method, '') AS uninstall_method,
    COALESCE(p.restart_action, '') AS restart_action,
    COALESCE(p.minimum_munki_version, '') AS minimum_munki_version,
    COALESCE(p.minimum_os_version, '') AS minimum_os_version,
    COALESCE(p.maximum_os_version, '') AS maximum_os_version,
    COALESCE(p.supported_architectures, ARRAY[]::text[]) AS supported_architectures,
    COALESCE(p.blocking_applications, ARRAY[]::text[]) AS blocking_applications,
    COALESCE(p.unattended_install, false) AS unattended_install,
    COALESCE(p.unattended_uninstall, false) AS unattended_uninstall,
    COALESCE(p.on_demand, false) AS on_demand,
    COALESCE(p.precache, false) AS precache,
    COALESCE(p.autoremove, false) AS autoremove,
    COALESCE(p.apple_item, false) AS apple_item,
    COALESCE(p.suppress_bundle_relocation, false) AS suppress_bundle_relocation,
    p.force_install_after_date,
    COALESCE(p.installed_size, 0)::bigint AS installed_size,
    COALESCE(p.package_path, '') AS package_path,
    COALESCE(p.installer_choices_xml, '') AS installer_choices_xml,
    COALESCE(p.installer_environment, '[]'::jsonb) AS installer_environment,
    COALESCE(p.installs, '[]'::jsonb) AS installs,
    COALESCE(p.receipts, '[]'::jsonb) AS receipts,
    COALESCE(p.items_to_copy, '[]'::jsonb) AS items_to_copy,
    COALESCE(p.notes, '') AS notes,
    COALESCE(p.installcheck_script, '') AS installcheck_script,
    COALESCE(p.uninstallcheck_script, '') AS uninstallcheck_script,
    COALESCE(p.preinstall_script, '') AS preinstall_script,
    COALESCE(p.postinstall_script, '') AS postinstall_script,
    COALESCE(p.preuninstall_script, '') AS preuninstall_script,
    COALESCE(p.postuninstall_script, '') AS postuninstall_script,
    COALESCE(p.uninstall_script, '') AS uninstall_script,
    COALESCE(p.version_script, '') AS version_script,
    COALESCE(p.preinstall_alert_enabled, false) AS preinstall_alert_enabled,
    COALESCE(p.preinstall_alert_title, '') AS preinstall_alert_title,
    COALESCE(p.preinstall_alert_detail, '') AS preinstall_alert_detail,
    COALESCE(p.preinstall_alert_ok_label, '') AS preinstall_alert_ok_label,
    COALESCE(p.preinstall_alert_cancel_label, '') AS preinstall_alert_cancel_label,
    COALESCE(p.preuninstall_alert_enabled, false) AS preuninstall_alert_enabled,
    COALESCE(p.preuninstall_alert_title, '') AS preuninstall_alert_title,
    COALESCE(p.preuninstall_alert_detail, '') AS preuninstall_alert_detail,
    COALESCE(p.preuninstall_alert_ok_label, '') AS preuninstall_alert_ok_label,
    COALESCE(p.preuninstall_alert_cancel_label, '') AS preuninstall_alert_cancel_label,
    COALESCE(p.icon_name, '') AS icon_name,
    COALESCE(p.icon_hash, '') AS icon_hash,
    p.installer_artifact_id,
    art.location AS installer_artifact_location,
    p.uninstaller_artifact_id,
    uninstaller.location AS uninstaller_artifact_location,
    p.icon_artifact_id,
    icon.location AS icon_artifact_location,
    software_icon.location AS software_icon_artifact_location
FROM munki_software_targets a
JOIN label_membership lm ON lm.label_id = a.label_id AND lm.host_id = $1
JOIN munki_software s ON s.id = a.software_id
JOIN munki_packages p ON p.software_id = a.software_id
    AND (
        (a.package_selection = 'latest_eligible' AND a.pinned_package_id IS NULL)
        OR (a.package_selection = 'specific_package' AND p.id = a.pinned_package_id)
    )
LEFT JOIN munki_artifacts art ON art.id = p.installer_artifact_id
LEFT JOIN munki_artifacts uninstaller ON uninstaller.id = p.uninstaller_artifact_id
LEFT JOIN munki_artifacts icon ON icon.id = p.icon_artifact_id
LEFT JOIN munki_artifacts software_icon ON software_icon.id = s.icon_artifact_id
WHERE a.direction = 'include'
  AND p.eligible
  AND NOT EXISTS (
      SELECT 1
      FROM munki_software_targets excluded
      JOIN label_membership excluded_lm
        ON excluded_lm.label_id = excluded.label_id
       AND excluded_lm.host_id = $1
      WHERE excluded.software_id = a.software_id
        AND excluded.direction = 'exclude'
  )
ORDER BY a.software_id, a.position, p.id
`

type ListEffectiveMunkiPackagesForHostParams struct {
	HostID int64 `json:"host_id"`
}

type ListEffectiveMunkiPackagesForHostRow struct {
	TargetID                     int64                 `json:"target_id"`
	TargetSoftwareID             int64                 `json:"target_software_id"`
	Action                       MunkiSoftwareAction   `json:"action"`
	OptionalInstall              bool                  `json:"optional_install"`
	FeaturedItem                 bool                  `json:"featured_item"`
	PackageSelection             MunkiPackageSelection `json:"package_selection"`
	PinnedPackageID              *int64                `json:"pinned_package_id"`
	Priority                     int32                 `json:"priority"`
	PackageID                    int64                 `json:"package_id"`
	SoftwareID                   int64                 `json:"software_id"`
	SoftwareName                 string                `json:"software_name"`
	SoftwareDescription          string                `json:"software_description"`
	SoftwareCategory             string                `json:"software_category"`
	SoftwareDeveloper            string                `json:"software_developer"`
	SoftwareIconName             string                `json:"software_icon_name"`
	SoftwareIconHash             string                `json:"software_icon_hash"`
	SoftwareIconArtifactID       *int64                `json:"software_icon_artifact_id"`
	Version                      string                `json:"version"`
	InstallerType                string                `json:"installer_type"`
	UninstallMethod              string                `json:"uninstall_method"`
	RestartAction                string                `json:"restart_action"`
	MinimumMunkiVersion          string                `json:"minimum_munki_version"`
	MinimumOSVersion             string                `json:"minimum_os_version"`
	MaximumOSVersion             string                `json:"maximum_os_version"`
	SupportedArchitectures       []string              `json:"supported_architectures"`
	BlockingApplications         []string              `json:"blocking_applications"`
	UnattendedInstall            bool                  `json:"unattended_install"`
	UnattendedUninstall          bool                  `json:"unattended_uninstall"`
	OnDemand                     bool                  `json:"on_demand"`
	Precache                     bool                  `json:"precache"`
	Autoremove                   bool                  `json:"autoremove"`
	AppleItem                    bool                  `json:"apple_item"`
	SuppressBundleRelocation     bool                  `json:"suppress_bundle_relocation"`
	ForceInstallAfterDate        *time.Time            `json:"force_install_after_date"`
	InstalledSize                int64                 `json:"installed_size"`
	PackagePath                  string                `json:"package_path"`
	InstallerChoicesXml          string                `json:"installer_choices_xml"`
	InstallerEnvironment         []byte                `json:"installer_environment"`
	Installs                     []byte                `json:"installs"`
	Receipts                     []byte                `json:"receipts"`
	ItemsToCopy                  []byte                `json:"items_to_copy"`
	Notes                        string                `json:"notes"`
	InstallcheckScript           string                `json:"installcheck_script"`
	UninstallcheckScript         string                `json:"uninstallcheck_script"`
	PreinstallScript             string                `json:"preinstall_script"`
	PostinstallScript            string                `json:"postinstall_script"`
	PreuninstallScript           string                `json:"preuninstall_script"`
	PostuninstallScript          string                `json:"postuninstall_script"`
	UninstallScript              string                `json:"uninstall_script"`
	VersionScript                string                `json:"version_script"`
	PreinstallAlertEnabled       bool                  `json:"preinstall_alert_enabled"`
	PreinstallAlertTitle         string                `json:"preinstall_alert_title"`
	PreinstallAlertDetail        string                `json:"preinstall_alert_detail"`
	PreinstallAlertOkLabel       string                `json:"preinstall_alert_ok_label"`
	PreinstallAlertCancelLabel   string                `json:"preinstall_alert_cancel_label"`
	PreuninstallAlertEnabled     bool                  `json:"preuninstall_alert_enabled"`
	PreuninstallAlertTitle       string                `json:"preuninstall_alert_title"`
	PreuninstallAlertDetail      string                `json:"preuninstall_alert_detail"`
	PreuninstallAlertOkLabel     string                `json:"preuninstall_alert_ok_label"`
	PreuninstallAlertCancelLabel string                `json:"preuninstall_alert_cancel_label"`
	IconName                     string                `json:"icon_name"`
	IconHash                     string                `json:"icon_hash"`
	InstallerArtifactID          *int64                `json:"installer_artifact_id"`
	InstallerArtifactLocation    *string               `json:"installer_artifact_location"`
	UninstallerArtifactID        *int64                `json:"uninstaller_artifact_id"`
	UninstallerArtifactLocation  *string               `json:"uninstaller_artifact_location"`
	IconArtifactID               *int64                `json:"icon_artifact_id"`
	IconArtifactLocation         *string               `json:"icon_artifact_location"`
	SoftwareIconArtifactLocation *string               `json:"software_icon_artifact_location"`
}

func (q *Queries) ListEffectiveMunkiPackagesForHost(ctx context.Context, arg ListEffectiveMunkiPackagesForHostParams) ([]ListEffectiveMunkiPackagesForHostRow, error) {
	rows, err := q.db.Query(ctx, listEffectiveMunkiPackagesForHost, arg.HostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEffectiveMunkiPackagesForHostRow{}
	for rows.Next() {
		var i ListEffectiveMunkiPackagesForHostRow
		if err := rows.Scan(
			&i.TargetID,
			&i.TargetSoftwareID,
			&i.Action,
			&i.OptionalInstall,
			&i.FeaturedItem,
			&i.PackageSelection,
			&i.PinnedPackageID,
			&i.Priority,
			&i.PackageID,
			&i.SoftwareID,
			&i.SoftwareName,
			&i.SoftwareDescription,
			&i.SoftwareCategory,
			&i.SoftwareDeveloper,
			&i.SoftwareIconName,
			&i.SoftwareIconHash,
			&i.SoftwareIconArtifactID,
			&i.Version,
			&i.InstallerType,
			&i.UninstallMethod,
			&i.RestartAction,
			&i.MinimumMunkiVersion,
			&i.MinimumOSVersion,
			&i.MaximumOSVersion,
			&i.SupportedArchitectures,
			&i.BlockingApplications,
			&i.UnattendedInstall,
			&i.UnattendedUninstall,
			&i.OnDemand,
			&i.Precache,
			&i.Autoremove,
			&i.AppleItem,
			&i.SuppressBundleRelocation,
			&i.ForceInstallAfterDate,
			&i.InstalledSize,
			&i.PackagePath,
			&i.InstallerChoicesXml,
			&i.InstallerEnvironment,
			&i.Installs,
			&i.Receipts,
			&i.ItemsToCopy,
			&i.Notes,
			&i.InstallcheckScript,
			&i.UninstallcheckScript,
			&i.PreinstallScript,
			&i.PostinstallScript,
			&i.PreuninstallScript,
			&i.PostuninstallScript,
			&i.UninstallScript,
			&i.VersionScript,
			&i.PreinstallAlertEnabled,
			&i.PreinstallAlertTitle,
			&i.PreinstallAlertDetail,
			&i.PreinstallAlertOkLabel,
			&i.PreinstallAlertCancelLabel,
			&i.PreuninstallAlertEnabled,
			&i.PreuninstallAlertTitle,
			&i.PreuninstallAlertDetail,
			&i.PreuninstallAlertOkLabel,
			&i.PreuninstallAlertCancelLabel,
			&i.IconName,
			&i.IconHash,
			&i.InstallerArtifactID,
			&i.InstallerArtifactLocation,
			&i.UninstallerArtifactID,
			&i.UninstallerArtifactLocation,
			&i.IconArtifactID,
			&i.IconArtifactLocation,
			&i.SoftwareIconArtifactLocation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMunkiSoftware = `-- name: ListMunkiSoftware :many
SELECT id, name, description, category, developer, icon_name, icon_hash, icon_artifact_id, created_at, updated_at
FROM munki_software
ORDER BY lower(name), id
LIMIT $2 OFFSET $1
`

type ListMunkiSoftwareParams struct {
	OffsetRows int32 `json:"offset_rows"`
	LimitRows  int32 `json:"limit_rows"`
}

func (q *Queries) ListMunkiSoftware(ctx context.Context, arg ListMunkiSoftwareParams) ([]MunkiSoftware, error) {
	rows, err := q.db.Query(ctx, listMunkiSoftware, arg.OffsetRows, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MunkiSoftware{}
	for rows.Next() {
		var i MunkiSoftware
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Developer,
			&i.IconName,
			&i.IconHash,
			&i.IconArtifactID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMunkiSoftwareExcludeLabels = `-- name: ListMunkiSoftwareExcludeLabels :many
SELECT software_id, label_id
FROM munki_software_targets
WHERE software_id = ANY($1::bigint[])
  AND direction = 'exclude'
ORDER BY software_id, position
`

type ListMunkiSoftwareExcludeLabelsParams struct {
	SoftwareIds []int64 `json:"software_ids"`
}

type ListMunkiSoftwareExcludeLabelsRow struct {
	SoftwareID int64 `json:"software_id"`
	LabelID    int64 `json:"label_id"`
}

func (q *Queries) ListMunkiSoftwareExcludeLabels(ctx context.Context, arg ListMunkiSoftwareExcludeLabelsParams) ([]ListMunkiSoftwareExcludeLabelsRow, error) {
	rows, err := q.db.Query(ctx, listMunkiSoftwareExcludeLabels, arg.SoftwareIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMunkiSoftwareExcludeLabelsRow{}
	for rows.Next() {
		var i ListMunkiSoftwareExcludeLabelsRow
		if err := rows.Scan(&i.SoftwareID, &i.LabelID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMunkiSoftware = `-- name: UpdateMunkiSoftware :one
UPDATE munki_software
SET
    name = $1,
    description = $2,
    category = $3,
    developer = $4,
    icon_name = $5,
    icon_hash = $6,
    icon_artifact_id = $7::bigint,
    updated_at = now()
WHERE id = $8
RETURNING id, name, description, category, developer, icon_name, icon_hash, icon_artifact_id, created_at, updated_at
`

type UpdateMunkiSoftwareParams struct {
	Name           string `json:"name"`
	Description    string `json:"description"`
	Category       string `json:"category"`
	Developer      string `json:"developer"`
	IconName       string `json:"icon_name"`
	IconHash       string `json:"icon_hash"`
	IconArtifactID *int64 `json:"icon_artifact_id"`
	ID             int64  `json:"id"`
}

func (q *Queries) UpdateMunkiSoftware(ctx context.Context, arg UpdateMunkiSoftwareParams) (MunkiSoftware, error) {
	row := q.db.QueryRow(ctx, updateMunkiSoftware,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Developer,
		arg.IconName,
		arg.IconHash,
		arg.IconArtifactID,
		arg.ID,
	)
	var i MunkiSoftware
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Developer,
		&i.IconName,
		&i.IconHash,
		&i.IconArtifactID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
