// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: munki_packages.sql

package sqlc

import (
	"context"
	"time"
)

const createMunkiPackage = `-- name: CreateMunkiPackage :one
INSERT INTO munki_packages (
    software_id,
    version,
    installer_type,
    uninstall_method,
    restart_action,
    minimum_munki_version,
    minimum_os_version,
    maximum_os_version,
    supported_architectures,
    blocking_applications,
    installable_condition,
    blocking_applications_manual_quit_only,
    blocking_applications_quit_script,
    unattended_install,
    unattended_uninstall,
    on_demand,
    precache,
    autoremove,
    apple_item,
    suppress_bundle_relocation,
    force_install_after_date,
    installed_size,
    package_path,
    installer_choices_xml,
    installer_environment,
    installs,
    receipts,
    items_to_copy,
    notes,
    installcheck_script,
    uninstallcheck_script,
    preinstall_script,
    postinstall_script,
    preuninstall_script,
    postuninstall_script,
    uninstall_script,
    version_script,
    preinstall_alert_enabled,
    preinstall_alert_title,
    preinstall_alert_detail,
    preinstall_alert_ok_label,
    preinstall_alert_cancel_label,
    preuninstall_alert_enabled,
    preuninstall_alert_title,
    preuninstall_alert_detail,
    preuninstall_alert_ok_label,
    preuninstall_alert_cancel_label,
    installer_object_id,
    uninstaller_object_id,
    eligible
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9::text[],
    $10::text[],
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21::timestamptz,
    $22,
    $23,
    $24::jsonb,
    $25::jsonb,
    $26::jsonb,
    $27::jsonb,
    $28::jsonb,
    $29,
    $30,
    $31,
    $32,
    $33,
    $34,
    $35,
    $36,
    $37,
    $38,
    $39,
    $40,
    $41,
    $42,
    $43,
    $44,
    $45,
    $46,
    $47,
    $48::bigint,
    $49::bigint,
    $50
)
RETURNING id, software_id, version, installer_type, uninstall_method, restart_action, minimum_munki_version, minimum_os_version, maximum_os_version, supported_architectures, blocking_applications, installable_condition, blocking_applications_manual_quit_only, blocking_applications_quit_script, unattended_install, unattended_uninstall, on_demand, precache, autoremove, apple_item, suppress_bundle_relocation, force_install_after_date, installed_size, package_path, installer_choices_xml, installer_environment, installs, receipts, items_to_copy, notes, installcheck_script, uninstallcheck_script, preinstall_script, postinstall_script, preuninstall_script, postuninstall_script, uninstall_script, version_script, preinstall_alert_enabled, preinstall_alert_title, preinstall_alert_detail, preinstall_alert_ok_label, preinstall_alert_cancel_label, preuninstall_alert_enabled, preuninstall_alert_title, preuninstall_alert_detail, preuninstall_alert_ok_label, preuninstall_alert_cancel_label, installer_object_id, uninstaller_object_id, eligible, created_at, updated_at
`

type CreateMunkiPackageParams struct {
	SoftwareID                         int64      `json:"software_id"`
	Version                            string     `json:"version"`
	InstallerType                      string     `json:"installer_type"`
	UninstallMethod                    string     `json:"uninstall_method"`
	RestartAction                      string     `json:"restart_action"`
	MinimumMunkiVersion                string     `json:"minimum_munki_version"`
	MinimumOSVersion                   string     `json:"minimum_os_version"`
	MaximumOSVersion                   string     `json:"maximum_os_version"`
	SupportedArchitectures             []string   `json:"supported_architectures"`
	BlockingApplications               []string   `json:"blocking_applications"`
	InstallableCondition               string     `json:"installable_condition"`
	BlockingApplicationsManualQuitOnly bool       `json:"blocking_applications_manual_quit_only"`
	BlockingApplicationsQuitScript     string     `json:"blocking_applications_quit_script"`
	UnattendedInstall                  bool       `json:"unattended_install"`
	UnattendedUninstall                bool       `json:"unattended_uninstall"`
	OnDemand                           bool       `json:"on_demand"`
	Precache                           bool       `json:"precache"`
	Autoremove                         bool       `json:"autoremove"`
	AppleItem                          bool       `json:"apple_item"`
	SuppressBundleRelocation           bool       `json:"suppress_bundle_relocation"`
	ForceInstallAfterDate              *time.Time `json:"force_install_after_date"`
	InstalledSize                      int64      `json:"installed_size"`
	PackagePath                        string     `json:"package_path"`
	InstallerChoicesXml                []byte     `json:"installer_choices_xml"`
	InstallerEnvironment               []byte     `json:"installer_environment"`
	Installs                           []byte     `json:"installs"`
	Receipts                           []byte     `json:"receipts"`
	ItemsToCopy                        []byte     `json:"items_to_copy"`
	Notes                              string     `json:"notes"`
	InstallcheckScript                 string     `json:"installcheck_script"`
	UninstallcheckScript               string     `json:"uninstallcheck_script"`
	PreinstallScript                   string     `json:"preinstall_script"`
	PostinstallScript                  string     `json:"postinstall_script"`
	PreuninstallScript                 string     `json:"preuninstall_script"`
	PostuninstallScript                string     `json:"postuninstall_script"`
	UninstallScript                    string     `json:"uninstall_script"`
	VersionScript                      string     `json:"version_script"`
	PreinstallAlertEnabled             bool       `json:"preinstall_alert_enabled"`
	PreinstallAlertTitle               string     `json:"preinstall_alert_title"`
	PreinstallAlertDetail              string     `json:"preinstall_alert_detail"`
	PreinstallAlertOkLabel             string     `json:"preinstall_alert_ok_label"`
	PreinstallAlertCancelLabel         string     `json:"preinstall_alert_cancel_label"`
	PreuninstallAlertEnabled           bool       `json:"preuninstall_alert_enabled"`
	PreuninstallAlertTitle             string     `json:"preuninstall_alert_title"`
	PreuninstallAlertDetail            string     `json:"preuninstall_alert_detail"`
	PreuninstallAlertOkLabel           string     `json:"preuninstall_alert_ok_label"`
	PreuninstallAlertCancelLabel       string     `json:"preuninstall_alert_cancel_label"`
	InstallerObjectID                  *int64     `json:"installer_object_id"`
	UninstallerObjectID                *int64     `json:"uninstaller_object_id"`
	Eligible                           bool       `json:"eligible"`
}

func (q *Queries) CreateMunkiPackage(ctx context.Context, arg CreateMunkiPackageParams) (MunkiPackage, error) {
	row := q.db.QueryRow(ctx, createMunkiPackage,
		arg.SoftwareID,
		arg.Version,
		arg.InstallerType,
		arg.UninstallMethod,
		arg.RestartAction,
		arg.MinimumMunkiVersion,
		arg.MinimumOSVersion,
		arg.MaximumOSVersion,
		arg.SupportedArchitectures,
		arg.BlockingApplications,
		arg.InstallableCondition,
		arg.BlockingApplicationsManualQuitOnly,
		arg.BlockingApplicationsQuitScript,
		arg.UnattendedInstall,
		arg.UnattendedUninstall,
		arg.OnDemand,
		arg.Precache,
		arg.Autoremove,
		arg.AppleItem,
		arg.SuppressBundleRelocation,
		arg.ForceInstallAfterDate,
		arg.InstalledSize,
		arg.PackagePath,
		arg.InstallerChoicesXml,
		arg.InstallerEnvironment,
		arg.Installs,
		arg.Receipts,
		arg.ItemsToCopy,
		arg.Notes,
		arg.InstallcheckScript,
		arg.UninstallcheckScript,
		arg.PreinstallScript,
		arg.PostinstallScript,
		arg.PreuninstallScript,
		arg.PostuninstallScript,
		arg.UninstallScript,
		arg.VersionScript,
		arg.PreinstallAlertEnabled,
		arg.PreinstallAlertTitle,
		arg.PreinstallAlertDetail,
		arg.PreinstallAlertOkLabel,
		arg.PreinstallAlertCancelLabel,
		arg.PreuninstallAlertEnabled,
		arg.PreuninstallAlertTitle,
		arg.PreuninstallAlertDetail,
		arg.PreuninstallAlertOkLabel,
		arg.PreuninstallAlertCancelLabel,
		arg.InstallerObjectID,
		arg.UninstallerObjectID,
		arg.Eligible,
	)
	var i MunkiPackage
	err := row.Scan(
		&i.ID,
		&i.SoftwareID,
		&i.Version,
		&i.InstallerType,
		&i.UninstallMethod,
		&i.RestartAction,
		&i.MinimumMunkiVersion,
		&i.MinimumOSVersion,
		&i.MaximumOSVersion,
		&i.SupportedArchitectures,
		&i.BlockingApplications,
		&i.InstallableCondition,
		&i.BlockingApplicationsManualQuitOnly,
		&i.BlockingApplicationsQuitScript,
		&i.UnattendedInstall,
		&i.UnattendedUninstall,
		&i.OnDemand,
		&i.Precache,
		&i.Autoremove,
		&i.AppleItem,
		&i.SuppressBundleRelocation,
		&i.ForceInstallAfterDate,
		&i.InstalledSize,
		&i.PackagePath,
		&i.InstallerChoicesXml,
		&i.InstallerEnvironment,
		&i.Installs,
		&i.Receipts,
		&i.ItemsToCopy,
		&i.Notes,
		&i.InstallcheckScript,
		&i.UninstallcheckScript,
		&i.PreinstallScript,
		&i.PostinstallScript,
		&i.PreuninstallScript,
		&i.PostuninstallScript,
		&i.UninstallScript,
		&i.VersionScript,
		&i.PreinstallAlertEnabled,
		&i.PreinstallAlertTitle,
		&i.PreinstallAlertDetail,
		&i.PreinstallAlertOkLabel,
		&i.PreinstallAlertCancelLabel,
		&i.PreuninstallAlertEnabled,
		&i.PreuninstallAlertTitle,
		&i.PreuninstallAlertDetail,
		&i.PreuninstallAlertOkLabel,
		&i.PreuninstallAlertCancelLabel,
		&i.InstallerObjectID,
		&i.UninstallerObjectID,
		&i.Eligible,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMunkiPackageRelation = `-- name: CreateMunkiPackageRelation :exec
INSERT INTO munki_package_relations (
    package_id,
    relation_kind,
    target_software_id,
    target_package_id,
    position
)
VALUES (
    $1,
    $2::munki_package_relation_kind,
    $3,
    $4::bigint,
    $5::integer
)
`

type CreateMunkiPackageRelationParams struct {
	PackageID        int64                    `json:"package_id"`
	RelationKind     MunkiPackageRelationKind `json:"relation_kind"`
	TargetSoftwareID int64                    `json:"target_software_id"`
	TargetPackageID  *int64                   `json:"target_package_id"`
	Position         int32                    `json:"position"`
}

func (q *Queries) CreateMunkiPackageRelation(ctx context.Context, arg CreateMunkiPackageRelationParams) error {
	_, err := q.db.Exec(ctx, createMunkiPackageRelation,
		arg.PackageID,
		arg.RelationKind,
		arg.TargetSoftwareID,
		arg.TargetPackageID,
		arg.Position,
	)
	return err
}

const deleteMunkiPackage = `-- name: DeleteMunkiPackage :execrows
DELETE FROM munki_packages
WHERE id = $1
`

type DeleteMunkiPackageParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) DeleteMunkiPackage(ctx context.Context, arg DeleteMunkiPackageParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMunkiPackage, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMunkiPackageRelationsByKind = `-- name: DeleteMunkiPackageRelationsByKind :exec
DELETE FROM munki_package_relations
WHERE package_id = $1
  AND relation_kind = $2::munki_package_relation_kind
`

type DeleteMunkiPackageRelationsByKindParams struct {
	PackageID    int64                    `json:"package_id"`
	RelationKind MunkiPackageRelationKind `json:"relation_kind"`
}

func (q *Queries) DeleteMunkiPackageRelationsByKind(ctx context.Context, arg DeleteMunkiPackageRelationsByKindParams) error {
	_, err := q.db.Exec(ctx, deleteMunkiPackageRelationsByKind, arg.PackageID, arg.RelationKind)
	return err
}

const deleteMunkiPackageRelationsByPackageIDs = `-- name: DeleteMunkiPackageRelationsByPackageIDs :exec
DELETE FROM munki_package_relations
WHERE package_id = ANY($1::bigint[])
`

type DeleteMunkiPackageRelationsByPackageIDsParams struct {
	Ids []int64 `json:"ids"`
}

func (q *Queries) DeleteMunkiPackageRelationsByPackageIDs(ctx context.Context, arg DeleteMunkiPackageRelationsByPackageIDsParams) error {
	_, err := q.db.Exec(ctx, deleteMunkiPackageRelationsByPackageIDs, arg.Ids)
	return err
}

const deleteMunkiPackages = `-- name: DeleteMunkiPackages :many
DELETE FROM munki_packages
WHERE id = ANY($1::bigint[])
RETURNING id
`

type DeleteMunkiPackagesParams struct {
	Ids []int64 `json:"ids"`
}

func (q *Queries) DeleteMunkiPackages(ctx context.Context, arg DeleteMunkiPackagesParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, deleteMunkiPackages, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMunkiPackageByID = `-- name: GetMunkiPackageByID :one
SELECT
    p.id, p.software_id, p.version, p.installer_type, p.uninstall_method, p.restart_action, p.minimum_munki_version, p.minimum_os_version, p.maximum_os_version, p.supported_architectures, p.blocking_applications, p.installable_condition, p.blocking_applications_manual_quit_only, p.blocking_applications_quit_script, p.unattended_install, p.unattended_uninstall, p.on_demand, p.precache, p.autoremove, p.apple_item, p.suppress_bundle_relocation, p.force_install_after_date, p.installed_size, p.package_path, p.installer_choices_xml, p.installer_environment, p.installs, p.receipts, p.items_to_copy, p.notes, p.installcheck_script, p.uninstallcheck_script, p.preinstall_script, p.postinstall_script, p.preuninstall_script, p.postuninstall_script, p.uninstall_script, p.version_script, p.preinstall_alert_enabled, p.preinstall_alert_title, p.preinstall_alert_detail, p.preinstall_alert_ok_label, p.preinstall_alert_cancel_label, p.preuninstall_alert_enabled, p.preuninstall_alert_title, p.preuninstall_alert_detail, p.preuninstall_alert_ok_label, p.preuninstall_alert_cancel_label, p.installer_object_id, p.uninstaller_object_id, p.eligible, p.created_at, p.updated_at,
    s.name AS software_name,
    s.description AS software_description,
    s.category AS software_category,
    s.developer AS software_developer,
    s.icon_object_id AS software_icon_object_id,
    installer_obj.filename AS installer_filename,
    installer_obj.size_bytes AS installer_size_bytes,
    installer_obj.sha256 AS installer_sha256
FROM munki_packages p
JOIN munki_software s ON s.id = p.software_id
LEFT JOIN storage_objects installer_obj ON installer_obj.id = p.installer_object_id
WHERE p.id = $1
`

type GetMunkiPackageByIDParams struct {
	ID int64 `json:"id"`
}

type GetMunkiPackageByIDRow struct {
	ID                                 int64      `json:"id"`
	SoftwareID                         int64      `json:"software_id"`
	Version                            string     `json:"version"`
	InstallerType                      string     `json:"installer_type"`
	UninstallMethod                    string     `json:"uninstall_method"`
	RestartAction                      string     `json:"restart_action"`
	MinimumMunkiVersion                string     `json:"minimum_munki_version"`
	MinimumOSVersion                   string     `json:"minimum_os_version"`
	MaximumOSVersion                   string     `json:"maximum_os_version"`
	SupportedArchitectures             []string   `json:"supported_architectures"`
	BlockingApplications               []string   `json:"blocking_applications"`
	InstallableCondition               string     `json:"installable_condition"`
	BlockingApplicationsManualQuitOnly bool       `json:"blocking_applications_manual_quit_only"`
	BlockingApplicationsQuitScript     string     `json:"blocking_applications_quit_script"`
	UnattendedInstall                  bool       `json:"unattended_install"`
	UnattendedUninstall                bool       `json:"unattended_uninstall"`
	OnDemand                           bool       `json:"on_demand"`
	Precache                           bool       `json:"precache"`
	Autoremove                         bool       `json:"autoremove"`
	AppleItem                          bool       `json:"apple_item"`
	SuppressBundleRelocation           bool       `json:"suppress_bundle_relocation"`
	ForceInstallAfterDate              *time.Time `json:"force_install_after_date"`
	InstalledSize                      int64      `json:"installed_size"`
	PackagePath                        string     `json:"package_path"`
	InstallerChoicesXml                []byte     `json:"installer_choices_xml"`
	InstallerEnvironment               []byte     `json:"installer_environment"`
	Installs                           []byte     `json:"installs"`
	Receipts                           []byte     `json:"receipts"`
	ItemsToCopy                        []byte     `json:"items_to_copy"`
	Notes                              string     `json:"notes"`
	InstallcheckScript                 string     `json:"installcheck_script"`
	UninstallcheckScript               string     `json:"uninstallcheck_script"`
	PreinstallScript                   string     `json:"preinstall_script"`
	PostinstallScript                  string     `json:"postinstall_script"`
	PreuninstallScript                 string     `json:"preuninstall_script"`
	PostuninstallScript                string     `json:"postuninstall_script"`
	UninstallScript                    string     `json:"uninstall_script"`
	VersionScript                      string     `json:"version_script"`
	PreinstallAlertEnabled             bool       `json:"preinstall_alert_enabled"`
	PreinstallAlertTitle               string     `json:"preinstall_alert_title"`
	PreinstallAlertDetail              string     `json:"preinstall_alert_detail"`
	PreinstallAlertOkLabel             string     `json:"preinstall_alert_ok_label"`
	PreinstallAlertCancelLabel         string     `json:"preinstall_alert_cancel_label"`
	PreuninstallAlertEnabled           bool       `json:"preuninstall_alert_enabled"`
	PreuninstallAlertTitle             string     `json:"preuninstall_alert_title"`
	PreuninstallAlertDetail            string     `json:"preuninstall_alert_detail"`
	PreuninstallAlertOkLabel           string     `json:"preuninstall_alert_ok_label"`
	PreuninstallAlertCancelLabel       string     `json:"preuninstall_alert_cancel_label"`
	InstallerObjectID                  *int64     `json:"installer_object_id"`
	UninstallerObjectID                *int64     `json:"uninstaller_object_id"`
	Eligible                           bool       `json:"eligible"`
	CreatedAt                          time.Time  `json:"created_at"`
	UpdatedAt                          time.Time  `json:"updated_at"`
	SoftwareName                       string     `json:"software_name"`
	SoftwareDescription                string     `json:"software_description"`
	SoftwareCategory                   string     `json:"software_category"`
	SoftwareDeveloper                  string     `json:"software_developer"`
	SoftwareIconObjectID               *int64     `json:"software_icon_object_id"`
	InstallerFilename                  *string    `json:"installer_filename"`
	InstallerSizeBytes                 *int64     `json:"installer_size_bytes"`
	InstallerSha256                    *string    `json:"installer_sha256"`
}

func (q *Queries) GetMunkiPackageByID(ctx context.Context, arg GetMunkiPackageByIDParams) (GetMunkiPackageByIDRow, error) {
	row := q.db.QueryRow(ctx, getMunkiPackageByID, arg.ID)
	var i GetMunkiPackageByIDRow
	err := row.Scan(
		&i.ID,
		&i.SoftwareID,
		&i.Version,
		&i.InstallerType,
		&i.UninstallMethod,
		&i.RestartAction,
		&i.MinimumMunkiVersion,
		&i.MinimumOSVersion,
		&i.MaximumOSVersion,
		&i.SupportedArchitectures,
		&i.BlockingApplications,
		&i.InstallableCondition,
		&i.BlockingApplicationsManualQuitOnly,
		&i.BlockingApplicationsQuitScript,
		&i.UnattendedInstall,
		&i.UnattendedUninstall,
		&i.OnDemand,
		&i.Precache,
		&i.Autoremove,
		&i.AppleItem,
		&i.SuppressBundleRelocation,
		&i.ForceInstallAfterDate,
		&i.InstalledSize,
		&i.PackagePath,
		&i.InstallerChoicesXml,
		&i.InstallerEnvironment,
		&i.Installs,
		&i.Receipts,
		&i.ItemsToCopy,
		&i.Notes,
		&i.InstallcheckScript,
		&i.UninstallcheckScript,
		&i.PreinstallScript,
		&i.PostinstallScript,
		&i.PreuninstallScript,
		&i.PostuninstallScript,
		&i.UninstallScript,
		&i.VersionScript,
		&i.PreinstallAlertEnabled,
		&i.PreinstallAlertTitle,
		&i.PreinstallAlertDetail,
		&i.PreinstallAlertOkLabel,
		&i.PreinstallAlertCancelLabel,
		&i.PreuninstallAlertEnabled,
		&i.PreuninstallAlertTitle,
		&i.PreuninstallAlertDetail,
		&i.PreuninstallAlertOkLabel,
		&i.PreuninstallAlertCancelLabel,
		&i.InstallerObjectID,
		&i.UninstallerObjectID,
		&i.Eligible,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SoftwareName,
		&i.SoftwareDescription,
		&i.SoftwareCategory,
		&i.SoftwareDeveloper,
		&i.SoftwareIconObjectID,
		&i.InstallerFilename,
		&i.InstallerSizeBytes,
		&i.InstallerSha256,
	)
	return i, err
}

const listMunkiPackageObjectIDsByIDs = `-- name: ListMunkiPackageObjectIDsByIDs :many
SELECT refs.object_id::bigint AS object_id
FROM munki_packages p
CROSS JOIN LATERAL unnest(
    array_remove(ARRAY[p.installer_object_id, p.uninstaller_object_id], NULL)::bigint[]
) AS refs(object_id)
WHERE p.id = ANY($1::bigint[])
`

type ListMunkiPackageObjectIDsByIDsParams struct {
	Ids []int64 `json:"ids"`
}

func (q *Queries) ListMunkiPackageObjectIDsByIDs(ctx context.Context, arg ListMunkiPackageObjectIDsByIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listMunkiPackageObjectIDsByIDs, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var object_id int64
		if err := rows.Scan(&object_id); err != nil {
			return nil, err
		}
		items = append(items, object_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMunkiPackageInstallerObject = `-- name: SetMunkiPackageInstallerObject :execrows
UPDATE munki_packages
SET installer_object_id = $1,
    updated_at = now()
WHERE id = $2
`

type SetMunkiPackageInstallerObjectParams struct {
	ObjectID *int64 `json:"object_id"`
	ID       int64  `json:"id"`
}

func (q *Queries) SetMunkiPackageInstallerObject(ctx context.Context, arg SetMunkiPackageInstallerObjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMunkiPackageInstallerObject, arg.ObjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMunkiPackageUninstallerObject = `-- name: SetMunkiPackageUninstallerObject :execrows
UPDATE munki_packages
SET uninstaller_object_id = $1,
    updated_at = now()
WHERE id = $2
`

type SetMunkiPackageUninstallerObjectParams struct {
	ObjectID *int64 `json:"object_id"`
	ID       int64  `json:"id"`
}

func (q *Queries) SetMunkiPackageUninstallerObject(ctx context.Context, arg SetMunkiPackageUninstallerObjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMunkiPackageUninstallerObject, arg.ObjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMunkiPackage = `-- name: UpdateMunkiPackage :one
UPDATE munki_packages
SET
    version = $1,
    installer_type = $2,
    uninstall_method = $3,
    restart_action = $4,
    minimum_munki_version = $5,
    minimum_os_version = $6,
    maximum_os_version = $7,
    supported_architectures = $8::text[],
    blocking_applications = $9::text[],
    installable_condition = $10,
    blocking_applications_manual_quit_only = $11,
    blocking_applications_quit_script = $12,
    unattended_install = $13,
    unattended_uninstall = $14,
    on_demand = $15,
    precache = $16,
    autoremove = $17,
    apple_item = $18,
    suppress_bundle_relocation = $19,
    force_install_after_date = $20::timestamptz,
    installed_size = $21,
    package_path = $22,
    installer_choices_xml = $23::jsonb,
    installer_environment = $24::jsonb,
    installs = $25::jsonb,
    receipts = $26::jsonb,
    items_to_copy = $27::jsonb,
    notes = $28,
    installcheck_script = $29,
    uninstallcheck_script = $30,
    preinstall_script = $31,
    postinstall_script = $32,
    preuninstall_script = $33,
    postuninstall_script = $34,
    uninstall_script = $35,
    version_script = $36,
    preinstall_alert_enabled = $37,
    preinstall_alert_title = $38,
    preinstall_alert_detail = $39,
    preinstall_alert_ok_label = $40,
    preinstall_alert_cancel_label = $41,
    preuninstall_alert_enabled = $42,
    preuninstall_alert_title = $43,
    preuninstall_alert_detail = $44,
    preuninstall_alert_ok_label = $45,
    preuninstall_alert_cancel_label = $46,
    installer_object_id = $47::bigint,
    uninstaller_object_id = $48::bigint,
    eligible = $49,
    updated_at = now()
WHERE id = $50
RETURNING id, software_id, version, installer_type, uninstall_method, restart_action, minimum_munki_version, minimum_os_version, maximum_os_version, supported_architectures, blocking_applications, installable_condition, blocking_applications_manual_quit_only, blocking_applications_quit_script, unattended_install, unattended_uninstall, on_demand, precache, autoremove, apple_item, suppress_bundle_relocation, force_install_after_date, installed_size, package_path, installer_choices_xml, installer_environment, installs, receipts, items_to_copy, notes, installcheck_script, uninstallcheck_script, preinstall_script, postinstall_script, preuninstall_script, postuninstall_script, uninstall_script, version_script, preinstall_alert_enabled, preinstall_alert_title, preinstall_alert_detail, preinstall_alert_ok_label, preinstall_alert_cancel_label, preuninstall_alert_enabled, preuninstall_alert_title, preuninstall_alert_detail, preuninstall_alert_ok_label, preuninstall_alert_cancel_label, installer_object_id, uninstaller_object_id, eligible, created_at, updated_at
`

type UpdateMunkiPackageParams struct {
	Version                            string     `json:"version"`
	InstallerType                      string     `json:"installer_type"`
	UninstallMethod                    string     `json:"uninstall_method"`
	RestartAction                      string     `json:"restart_action"`
	MinimumMunkiVersion                string     `json:"minimum_munki_version"`
	MinimumOSVersion                   string     `json:"minimum_os_version"`
	MaximumOSVersion                   string     `json:"maximum_os_version"`
	SupportedArchitectures             []string   `json:"supported_architectures"`
	BlockingApplications               []string   `json:"blocking_applications"`
	InstallableCondition               string     `json:"installable_condition"`
	BlockingApplicationsManualQuitOnly bool       `json:"blocking_applications_manual_quit_only"`
	BlockingApplicationsQuitScript     string     `json:"blocking_applications_quit_script"`
	UnattendedInstall                  bool       `json:"unattended_install"`
	UnattendedUninstall                bool       `json:"unattended_uninstall"`
	OnDemand                           bool       `json:"on_demand"`
	Precache                           bool       `json:"precache"`
	Autoremove                         bool       `json:"autoremove"`
	AppleItem                          bool       `json:"apple_item"`
	SuppressBundleRelocation           bool       `json:"suppress_bundle_relocation"`
	ForceInstallAfterDate              *time.Time `json:"force_install_after_date"`
	InstalledSize                      int64      `json:"installed_size"`
	PackagePath                        string     `json:"package_path"`
	InstallerChoicesXml                []byte     `json:"installer_choices_xml"`
	InstallerEnvironment               []byte     `json:"installer_environment"`
	Installs                           []byte     `json:"installs"`
	Receipts                           []byte     `json:"receipts"`
	ItemsToCopy                        []byte     `json:"items_to_copy"`
	Notes                              string     `json:"notes"`
	InstallcheckScript                 string     `json:"installcheck_script"`
	UninstallcheckScript               string     `json:"uninstallcheck_script"`
	PreinstallScript                   string     `json:"preinstall_script"`
	PostinstallScript                  string     `json:"postinstall_script"`
	PreuninstallScript                 string     `json:"preuninstall_script"`
	PostuninstallScript                string     `json:"postuninstall_script"`
	UninstallScript                    string     `json:"uninstall_script"`
	VersionScript                      string     `json:"version_script"`
	PreinstallAlertEnabled             bool       `json:"preinstall_alert_enabled"`
	PreinstallAlertTitle               string     `json:"preinstall_alert_title"`
	PreinstallAlertDetail              string     `json:"preinstall_alert_detail"`
	PreinstallAlertOkLabel             string     `json:"preinstall_alert_ok_label"`
	PreinstallAlertCancelLabel         string     `json:"preinstall_alert_cancel_label"`
	PreuninstallAlertEnabled           bool       `json:"preuninstall_alert_enabled"`
	PreuninstallAlertTitle             string     `json:"preuninstall_alert_title"`
	PreuninstallAlertDetail            string     `json:"preuninstall_alert_detail"`
	PreuninstallAlertOkLabel           string     `json:"preuninstall_alert_ok_label"`
	PreuninstallAlertCancelLabel       string     `json:"preuninstall_alert_cancel_label"`
	InstallerObjectID                  *int64     `json:"installer_object_id"`
	UninstallerObjectID                *int64     `json:"uninstaller_object_id"`
	Eligible                           bool       `json:"eligible"`
	ID                                 int64      `json:"id"`
}

func (q *Queries) UpdateMunkiPackage(ctx context.Context, arg UpdateMunkiPackageParams) (MunkiPackage, error) {
	row := q.db.QueryRow(ctx, updateMunkiPackage,
		arg.Version,
		arg.InstallerType,
		arg.UninstallMethod,
		arg.RestartAction,
		arg.MinimumMunkiVersion,
		arg.MinimumOSVersion,
		arg.MaximumOSVersion,
		arg.SupportedArchitectures,
		arg.BlockingApplications,
		arg.InstallableCondition,
		arg.BlockingApplicationsManualQuitOnly,
		arg.BlockingApplicationsQuitScript,
		arg.UnattendedInstall,
		arg.UnattendedUninstall,
		arg.OnDemand,
		arg.Precache,
		arg.Autoremove,
		arg.AppleItem,
		arg.SuppressBundleRelocation,
		arg.ForceInstallAfterDate,
		arg.InstalledSize,
		arg.PackagePath,
		arg.InstallerChoicesXml,
		arg.InstallerEnvironment,
		arg.Installs,
		arg.Receipts,
		arg.ItemsToCopy,
		arg.Notes,
		arg.InstallcheckScript,
		arg.UninstallcheckScript,
		arg.PreinstallScript,
		arg.PostinstallScript,
		arg.PreuninstallScript,
		arg.PostuninstallScript,
		arg.UninstallScript,
		arg.VersionScript,
		arg.PreinstallAlertEnabled,
		arg.PreinstallAlertTitle,
		arg.PreinstallAlertDetail,
		arg.PreinstallAlertOkLabel,
		arg.PreinstallAlertCancelLabel,
		arg.PreuninstallAlertEnabled,
		arg.PreuninstallAlertTitle,
		arg.PreuninstallAlertDetail,
		arg.PreuninstallAlertOkLabel,
		arg.PreuninstallAlertCancelLabel,
		arg.InstallerObjectID,
		arg.UninstallerObjectID,
		arg.Eligible,
		arg.ID,
	)
	var i MunkiPackage
	err := row.Scan(
		&i.ID,
		&i.SoftwareID,
		&i.Version,
		&i.InstallerType,
		&i.UninstallMethod,
		&i.RestartAction,
		&i.MinimumMunkiVersion,
		&i.MinimumOSVersion,
		&i.MaximumOSVersion,
		&i.SupportedArchitectures,
		&i.BlockingApplications,
		&i.InstallableCondition,
		&i.BlockingApplicationsManualQuitOnly,
		&i.BlockingApplicationsQuitScript,
		&i.UnattendedInstall,
		&i.UnattendedUninstall,
		&i.OnDemand,
		&i.Precache,
		&i.Autoremove,
		&i.AppleItem,
		&i.SuppressBundleRelocation,
		&i.ForceInstallAfterDate,
		&i.InstalledSize,
		&i.PackagePath,
		&i.InstallerChoicesXml,
		&i.InstallerEnvironment,
		&i.Installs,
		&i.Receipts,
		&i.ItemsToCopy,
		&i.Notes,
		&i.InstallcheckScript,
		&i.UninstallcheckScript,
		&i.PreinstallScript,
		&i.PostinstallScript,
		&i.PreuninstallScript,
		&i.PostuninstallScript,
		&i.UninstallScript,
		&i.VersionScript,
		&i.PreinstallAlertEnabled,
		&i.PreinstallAlertTitle,
		&i.PreinstallAlertDetail,
		&i.PreinstallAlertOkLabel,
		&i.PreinstallAlertCancelLabel,
		&i.PreuninstallAlertEnabled,
		&i.PreuninstallAlertTitle,
		&i.PreuninstallAlertDetail,
		&i.PreuninstallAlertOkLabel,
		&i.PreuninstallAlertCancelLabel,
		&i.InstallerObjectID,
		&i.UninstallerObjectID,
		&i.Eligible,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
