// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: santa.sql

package sqlc

import (
	"context"
	"time"
)

const countSantaRulesForHost = `-- name: CountSantaRulesForHost :one
WITH host_labels AS (
    SELECT label_id
    FROM label_membership
    WHERE host_id = $1
),
matching_includes AS (
    SELECT
        r.id AS rule_id,
        r.rule_type,
        r.identifier,
        r.name,
        r.description,
        i.policy,
        COALESCE(i.cel_expression, '') AS cel_expression,
        r.custom_message,
        r.custom_url,
        i.id AS matched_include_id,
        CASE r.rule_type
            WHEN 'cdhash' THEN 1
            WHEN 'binary' THEN 2
            WHEN 'signingid' THEN 3
            WHEN 'certificate' THEN 4
            WHEN 'teamid' THEN 5
            WHEN 'bundle' THEN 6
            ELSE 7
        END AS rule_type_sort,
        row_number() OVER (PARTITION BY r.id ORDER BY i.position, i.id) AS include_rank
    FROM santa_rules r
    JOIN santa_rule_includes i ON i.rule_id = r.id
    JOIN host_labels include_hl ON include_hl.label_id = i.label_id
    WHERE NOT EXISTS (
        SELECT 1
        FROM santa_rule_exclude_labels el
        JOIN host_labels hl ON hl.label_id = el.label_id
        WHERE el.rule_id = r.id
    )
),
selected_includes AS (
    SELECT rule_id, rule_type, identifier, name, description, policy, cel_expression, custom_message, custom_url, matched_include_id, rule_type_sort, include_rank
    FROM matching_includes
    WHERE include_rank = 1
),
expanded_rules AS (
    SELECT
        rule_id,
        rule_type,
        identifier,
        name,
        description,
        policy,
        cel_expression,
        custom_message,
        custom_url,
        ''::text AS notification_app_name,
        matched_include_id,
        rule_type_sort
    FROM selected_includes
    WHERE rule_type <> 'bundle'
    UNION ALL
    SELECT
        si.rule_id,
        'binary'::santa_rule_type AS rule_type,
        e.sha256 AS identifier,
        si.name,
        si.description,
        si.policy,
        si.cel_expression,
        si.custom_message,
        si.custom_url,
        COALESCE(NULLIF(b.name, ''), NULLIF(b.bundle_id, ''), b.sha256) AS notification_app_name,
        si.matched_include_id,
        2 AS rule_type_sort
    FROM selected_includes si
    JOIN santa_bundles b ON b.sha256 = si.identifier AND b.uploaded_at IS NOT NULL
    JOIN santa_bundle_executables be ON be.bundle_id = b.id
    JOIN santa_executables e ON e.id = be.executable_id
    WHERE si.rule_type = 'bundle'
      AND e.sha256 <> ''
)
SELECT count(*)::integer
FROM expanded_rules
`

type CountSantaRulesForHostParams struct {
	HostID int64 `json:"host_id"`
}

func (q *Queries) CountSantaRulesForHost(ctx context.Context, arg CountSantaRulesForHostParams) (int32, error) {
	row := q.db.QueryRow(ctx, countSantaRulesForHost, arg.HostID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createSantaConfiguration = `-- name: CreateSantaConfiguration :one
INSERT INTO santa_configurations (
    name,
    description,
    position,
    client_mode,
    enable_bundles,
    enable_transitive_rules,
    enable_all_event_upload,
    full_sync_interval_seconds,
    batch_size,
    allowed_path_regex,
    blocked_path_regex,
    removable_media_action,
    removable_media_remount_flags,
    encrypted_removable_media_action,
    encrypted_removable_media_remount_flags,
    event_detail_url,
    event_detail_text
)
VALUES (
    $1,
    $2,
    (SELECT COALESCE(MAX(position) + 1, 0) FROM santa_configurations),
    $3::santa_client_mode,
    $4,
    $5,
    $6,
    $7::integer,
    $8::integer,
    $9,
    $10,
    $11::santa_removable_media_action,
    $12::text[],
    $13::santa_removable_media_action,
    $14::text[],
    $15,
    $16
)
RETURNING id, name, description, position, client_mode, enable_bundles, enable_transitive_rules, enable_all_event_upload, full_sync_interval_seconds, batch_size, allowed_path_regex, blocked_path_regex, removable_media_action, removable_media_remount_flags, encrypted_removable_media_action, encrypted_removable_media_remount_flags, event_detail_url, event_detail_text, created_at, updated_at
`

type CreateSantaConfigurationParams struct {
	Name                                string                     `json:"name"`
	Description                         string                     `json:"description"`
	ClientMode                          SantaClientMode            `json:"client_mode"`
	EnableBundles                       bool                       `json:"enable_bundles"`
	EnableTransitiveRules               bool                       `json:"enable_transitive_rules"`
	EnableAllEventUpload                bool                       `json:"enable_all_event_upload"`
	FullSyncIntervalSeconds             int32                      `json:"full_sync_interval_seconds"`
	BatchSize                           int32                      `json:"batch_size"`
	AllowedPathRegex                    string                     `json:"allowed_path_regex"`
	BlockedPathRegex                    string                     `json:"blocked_path_regex"`
	RemovableMediaAction                *SantaRemovableMediaAction `json:"removable_media_action"`
	RemovableMediaRemountFlags          []string                   `json:"removable_media_remount_flags"`
	EncryptedRemovableMediaAction       *SantaRemovableMediaAction `json:"encrypted_removable_media_action"`
	EncryptedRemovableMediaRemountFlags []string                   `json:"encrypted_removable_media_remount_flags"`
	EventDetailURL                      string                     `json:"event_detail_url"`
	EventDetailText                     string                     `json:"event_detail_text"`
}

func (q *Queries) CreateSantaConfiguration(ctx context.Context, arg CreateSantaConfigurationParams) (SantaConfiguration, error) {
	row := q.db.QueryRow(ctx, createSantaConfiguration,
		arg.Name,
		arg.Description,
		arg.ClientMode,
		arg.EnableBundles,
		arg.EnableTransitiveRules,
		arg.EnableAllEventUpload,
		arg.FullSyncIntervalSeconds,
		arg.BatchSize,
		arg.AllowedPathRegex,
		arg.BlockedPathRegex,
		arg.RemovableMediaAction,
		arg.RemovableMediaRemountFlags,
		arg.EncryptedRemovableMediaAction,
		arg.EncryptedRemovableMediaRemountFlags,
		arg.EventDetailURL,
		arg.EventDetailText,
	)
	var i SantaConfiguration
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.ClientMode,
		&i.EnableBundles,
		&i.EnableTransitiveRules,
		&i.EnableAllEventUpload,
		&i.FullSyncIntervalSeconds,
		&i.BatchSize,
		&i.AllowedPathRegex,
		&i.BlockedPathRegex,
		&i.RemovableMediaAction,
		&i.RemovableMediaRemountFlags,
		&i.EncryptedRemovableMediaAction,
		&i.EncryptedRemovableMediaRemountFlags,
		&i.EventDetailURL,
		&i.EventDetailText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSantaRule = `-- name: CreateSantaRule :one
INSERT INTO santa_rules (
    rule_type,
    identifier,
    name,
    description,
    custom_message,
    custom_url
)
VALUES (
    $1::santa_rule_type,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, rule_type, identifier, name, description, custom_message, custom_url, created_at, updated_at
`

type CreateSantaRuleParams struct {
	RuleType      SantaRuleType `json:"rule_type"`
	Identifier    string        `json:"identifier"`
	Name          string        `json:"name"`
	Description   string        `json:"description"`
	CustomMessage string        `json:"custom_message"`
	CustomURL     string        `json:"custom_url"`
}

func (q *Queries) CreateSantaRule(ctx context.Context, arg CreateSantaRuleParams) (SantaRule, error) {
	row := q.db.QueryRow(ctx, createSantaRule,
		arg.RuleType,
		arg.Identifier,
		arg.Name,
		arg.Description,
		arg.CustomMessage,
		arg.CustomURL,
	)
	var i SantaRule
	err := row.Scan(
		&i.ID,
		&i.RuleType,
		&i.Identifier,
		&i.Name,
		&i.Description,
		&i.CustomMessage,
		&i.CustomURL,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSantaConfiguration = `-- name: DeleteSantaConfiguration :one
DELETE FROM santa_configurations
WHERE id = $1
RETURNING id
`

type DeleteSantaConfigurationParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) DeleteSantaConfiguration(ctx context.Context, arg DeleteSantaConfigurationParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteSantaConfiguration, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteSantaConfigurationTargets = `-- name: DeleteSantaConfigurationTargets :exec
DELETE FROM santa_configuration_targets
WHERE configuration_id = $1
`

type DeleteSantaConfigurationTargetsParams struct {
	ConfigurationID int64 `json:"configuration_id"`
}

func (q *Queries) DeleteSantaConfigurationTargets(ctx context.Context, arg DeleteSantaConfigurationTargetsParams) error {
	_, err := q.db.Exec(ctx, deleteSantaConfigurationTargets, arg.ConfigurationID)
	return err
}

const deleteSantaConfigurations = `-- name: DeleteSantaConfigurations :many
DELETE FROM santa_configurations
WHERE id = ANY($1::bigint[])
RETURNING id
`

type DeleteSantaConfigurationsParams struct {
	Ids []int64 `json:"ids"`
}

func (q *Queries) DeleteSantaConfigurations(ctx context.Context, arg DeleteSantaConfigurationsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, deleteSantaConfigurations, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteSantaRule = `-- name: DeleteSantaRule :one
DELETE FROM santa_rules
WHERE id = $1
RETURNING id
`

type DeleteSantaRuleParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) DeleteSantaRule(ctx context.Context, arg DeleteSantaRuleParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteSantaRule, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteSantaRuleExcludeLabels = `-- name: DeleteSantaRuleExcludeLabels :exec
DELETE FROM santa_rule_exclude_labels
WHERE rule_id = $1
`

type DeleteSantaRuleExcludeLabelsParams struct {
	RuleID int64 `json:"rule_id"`
}

func (q *Queries) DeleteSantaRuleExcludeLabels(ctx context.Context, arg DeleteSantaRuleExcludeLabelsParams) error {
	_, err := q.db.Exec(ctx, deleteSantaRuleExcludeLabels, arg.RuleID)
	return err
}

const deleteSantaRuleIncludes = `-- name: DeleteSantaRuleIncludes :exec
DELETE FROM santa_rule_includes
WHERE rule_id = $1
`

type DeleteSantaRuleIncludesParams struct {
	RuleID int64 `json:"rule_id"`
}

func (q *Queries) DeleteSantaRuleIncludes(ctx context.Context, arg DeleteSantaRuleIncludesParams) error {
	_, err := q.db.Exec(ctx, deleteSantaRuleIncludes, arg.RuleID)
	return err
}

const deleteSantaRules = `-- name: DeleteSantaRules :many
DELETE FROM santa_rules
WHERE id = ANY($1::bigint[])
RETURNING id
`

type DeleteSantaRulesParams struct {
	Ids []int64 `json:"ids"`
}

func (q *Queries) DeleteSantaRules(ctx context.Context, arg DeleteSantaRulesParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, deleteSantaRules, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHostIDByMachineID = `-- name: GetHostIDByMachineID :one
SELECT id
FROM hosts
WHERE hardware_uuid = $1
`

type GetHostIDByMachineIDParams struct {
	MachineID string `json:"machine_id"`
}

func (q *Queries) GetHostIDByMachineID(ctx context.Context, arg GetHostIDByMachineIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getHostIDByMachineID, arg.MachineID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getObservedSantaHostState = `-- name: GetObservedSantaHostState :one
SELECT
    sh.santa_version,
    sh.client_mode_reported,
    sh.last_seen_at,
    ss.last_clean_sync_at
FROM santa_hosts sh
LEFT JOIN santa_sync_state ss ON ss.host_id = sh.host_id
WHERE sh.host_id = $1
`

type GetObservedSantaHostStateParams struct {
	HostID int64 `json:"host_id"`
}

type GetObservedSantaHostStateRow struct {
	SantaVersion       string          `json:"santa_version"`
	ClientModeReported SantaClientMode `json:"client_mode_reported"`
	LastSeenAt         *time.Time      `json:"last_seen_at"`
	LastCleanSyncAt    *time.Time      `json:"last_clean_sync_at"`
}

func (q *Queries) GetObservedSantaHostState(ctx context.Context, arg GetObservedSantaHostStateParams) (GetObservedSantaHostStateRow, error) {
	row := q.db.QueryRow(ctx, getObservedSantaHostState, arg.HostID)
	var i GetObservedSantaHostStateRow
	err := row.Scan(
		&i.SantaVersion,
		&i.ClientModeReported,
		&i.LastSeenAt,
		&i.LastCleanSyncAt,
	)
	return i, err
}

const getSantaConfigurationByID = `-- name: GetSantaConfigurationByID :one
SELECT id, name, description, position, client_mode, enable_bundles, enable_transitive_rules, enable_all_event_upload, full_sync_interval_seconds, batch_size, allowed_path_regex, blocked_path_regex, removable_media_action, removable_media_remount_flags, encrypted_removable_media_action, encrypted_removable_media_remount_flags, event_detail_url, event_detail_text, created_at, updated_at
FROM santa_configurations
WHERE id = $1
`

type GetSantaConfigurationByIDParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) GetSantaConfigurationByID(ctx context.Context, arg GetSantaConfigurationByIDParams) (SantaConfiguration, error) {
	row := q.db.QueryRow(ctx, getSantaConfigurationByID, arg.ID)
	var i SantaConfiguration
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.ClientMode,
		&i.EnableBundles,
		&i.EnableTransitiveRules,
		&i.EnableAllEventUpload,
		&i.FullSyncIntervalSeconds,
		&i.BatchSize,
		&i.AllowedPathRegex,
		&i.BlockedPathRegex,
		&i.RemovableMediaAction,
		&i.RemovableMediaRemountFlags,
		&i.EncryptedRemovableMediaAction,
		&i.EncryptedRemovableMediaRemountFlags,
		&i.EventDetailURL,
		&i.EventDetailText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSantaRuleByID = `-- name: GetSantaRuleByID :one
SELECT id, rule_type, identifier, name, description, custom_message, custom_url, created_at, updated_at
FROM santa_rules
WHERE id = $1
`

type GetSantaRuleByIDParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) GetSantaRuleByID(ctx context.Context, arg GetSantaRuleByIDParams) (SantaRule, error) {
	row := q.db.QueryRow(ctx, getSantaRuleByID, arg.ID)
	var i SantaRule
	err := row.Scan(
		&i.ID,
		&i.RuleType,
		&i.Identifier,
		&i.Name,
		&i.Description,
		&i.CustomMessage,
		&i.CustomURL,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSantaSyncSummary = `-- name: GetSantaSyncSummary :one
SELECT
    (SELECT count(*)::integer FROM santa_sync_targets st WHERE st.host_id = $1 AND st.phase = 'desired') AS desired_count,
    (SELECT count(*)::integer FROM santa_sync_targets st WHERE st.host_id = $1 AND st.phase = 'applied') AS applied_count,
    (SELECT count(*)::integer FROM santa_sync_pending_rules pr WHERE pr.host_id = $1) AS pending_count
`

type GetSantaSyncSummaryParams struct {
	SummaryHostID int64 `json:"summary_host_id"`
}

type GetSantaSyncSummaryRow struct {
	DesiredCount int32 `json:"desired_count"`
	AppliedCount int32 `json:"applied_count"`
	PendingCount int32 `json:"pending_count"`
}

func (q *Queries) GetSantaSyncSummary(ctx context.Context, arg GetSantaSyncSummaryParams) (GetSantaSyncSummaryRow, error) {
	row := q.db.QueryRow(ctx, getSantaSyncSummary, arg.SummaryHostID)
	var i GetSantaSyncSummaryRow
	err := row.Scan(&i.DesiredCount, &i.AppliedCount, &i.PendingCount)
	return i, err
}

const insertSantaConfigurationTargets = `-- name: InsertSantaConfigurationTargets :exec
INSERT INTO santa_configuration_targets (configuration_id, label_id, effect)
SELECT $1, labels.label_id, effects.effect
FROM unnest($2::bigint[]) WITH ORDINALITY AS labels(label_id, ord)
JOIN unnest($3::text[]) WITH ORDINALITY AS effects(effect, ord) USING (ord)
`

type InsertSantaConfigurationTargetsParams struct {
	ConfigurationID int64    `json:"configuration_id"`
	LabelIds        []int64  `json:"label_ids"`
	Effects         []string `json:"effects"`
}

func (q *Queries) InsertSantaConfigurationTargets(ctx context.Context, arg InsertSantaConfigurationTargetsParams) error {
	_, err := q.db.Exec(ctx, insertSantaConfigurationTargets, arg.ConfigurationID, arg.LabelIds, arg.Effects)
	return err
}

const insertSantaRuleExcludeLabels = `-- name: InsertSantaRuleExcludeLabels :exec
INSERT INTO santa_rule_exclude_labels (rule_id, label_id)
SELECT $1, label_id
FROM unnest($2::bigint[]) AS label_id
`

type InsertSantaRuleExcludeLabelsParams struct {
	RuleID   int64   `json:"rule_id"`
	LabelIds []int64 `json:"label_ids"`
}

func (q *Queries) InsertSantaRuleExcludeLabels(ctx context.Context, arg InsertSantaRuleExcludeLabelsParams) error {
	_, err := q.db.Exec(ctx, insertSantaRuleExcludeLabels, arg.RuleID, arg.LabelIds)
	return err
}

const insertSantaRuleIncludes = `-- name: InsertSantaRuleIncludes :exec
WITH input AS (
    SELECT
        p.policy,
        ce.cel_expression,
        l.label_id,
        p.position
    FROM unnest($2::text[]) WITH ORDINALITY AS p(policy, position)
    JOIN unnest($3::text[]) WITH ORDINALITY AS ce(cel_expression, position) USING (position)
    JOIN unnest($4::bigint[]) WITH ORDINALITY AS l(label_id, position) USING (position)
)
INSERT INTO santa_rule_includes (rule_id, position, policy, cel_expression, label_id)
SELECT
    $1,
    position - 1,
    policy::santa_policy,
    NULLIF(cel_expression, ''),
    label_id
FROM input
ORDER BY position
`

type InsertSantaRuleIncludesParams struct {
	RuleID         int64    `json:"rule_id"`
	Policies       []string `json:"policies"`
	CelExpressions []string `json:"cel_expressions"`
	LabelIds       []int64  `json:"label_ids"`
}

func (q *Queries) InsertSantaRuleIncludes(ctx context.Context, arg InsertSantaRuleIncludesParams) error {
	_, err := q.db.Exec(ctx, insertSantaRuleIncludes,
		arg.RuleID,
		arg.Policies,
		arg.CelExpressions,
		arg.LabelIds,
	)
	return err
}

const isSantaBundleComplete = `-- name: IsSantaBundleComplete :one
SELECT (uploaded_at IS NOT NULL)::boolean AS complete
FROM santa_bundles
WHERE sha256 = $1
`

type IsSantaBundleCompleteParams struct {
	Sha256 string `json:"sha256"`
}

func (q *Queries) IsSantaBundleComplete(ctx context.Context, arg IsSantaBundleCompleteParams) (bool, error) {
	row := q.db.QueryRow(ctx, isSantaBundleComplete, arg.Sha256)
	var complete bool
	err := row.Scan(&complete)
	return complete, err
}

const listAppliedSantaSyncTargets = `-- name: ListAppliedSantaSyncTargets :many
SELECT
    rule_type::text,
    identifier,
    policy::text,
    cel_expression,
    custom_message,
    custom_url,
    notification_app_name,
    payload_hash
FROM santa_sync_targets
WHERE host_id = $1 AND phase = 'applied'
`

type ListAppliedSantaSyncTargetsParams struct {
	HostID int64 `json:"host_id"`
}

type ListAppliedSantaSyncTargetsRow struct {
	RuleType            string `json:"rule_type"`
	Identifier          string `json:"identifier"`
	Policy              string `json:"policy"`
	CelExpression       string `json:"cel_expression"`
	CustomMessage       string `json:"custom_message"`
	CustomURL           string `json:"custom_url"`
	NotificationAppName string `json:"notification_app_name"`
	PayloadHash         string `json:"payload_hash"`
}

func (q *Queries) ListAppliedSantaSyncTargets(ctx context.Context, arg ListAppliedSantaSyncTargetsParams) ([]ListAppliedSantaSyncTargetsRow, error) {
	rows, err := q.db.Query(ctx, listAppliedSantaSyncTargets, arg.HostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppliedSantaSyncTargetsRow{}
	for rows.Next() {
		var i ListAppliedSantaSyncTargetsRow
		if err := rows.Scan(
			&i.RuleType,
			&i.Identifier,
			&i.Policy,
			&i.CelExpression,
			&i.CustomMessage,
			&i.CustomURL,
			&i.NotificationAppName,
			&i.PayloadHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSantaConfigurationIDsByPosition = `-- name: ListSantaConfigurationIDsByPosition :many
SELECT id
FROM santa_configurations
ORDER BY position, id
`

func (q *Queries) ListSantaConfigurationIDsByPosition(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, listSantaConfigurationIDsByPosition)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSantaConfigurationTargets = `-- name: ListSantaConfigurationTargets :many
SELECT configuration_id, label_id, effect
FROM santa_configuration_targets
WHERE configuration_id = ANY($1::bigint[])
ORDER BY configuration_id, effect, label_id
`

type ListSantaConfigurationTargetsParams struct {
	ConfigurationIds []int64 `json:"configuration_ids"`
}

func (q *Queries) ListSantaConfigurationTargets(ctx context.Context, arg ListSantaConfigurationTargetsParams) ([]SantaConfigurationTarget, error) {
	rows, err := q.db.Query(ctx, listSantaConfigurationTargets, arg.ConfigurationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SantaConfigurationTarget{}
	for rows.Next() {
		var i SantaConfigurationTarget
		if err := rows.Scan(&i.ConfigurationID, &i.LabelID, &i.Effect); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSantaRuleExcludeLabels = `-- name: ListSantaRuleExcludeLabels :many
SELECT rule_id, label_id
FROM santa_rule_exclude_labels
WHERE rule_id = ANY($1::bigint[])
ORDER BY rule_id, label_id
`

type ListSantaRuleExcludeLabelsParams struct {
	RuleIds []int64 `json:"rule_ids"`
}

func (q *Queries) ListSantaRuleExcludeLabels(ctx context.Context, arg ListSantaRuleExcludeLabelsParams) ([]SantaRuleExcludeLabel, error) {
	rows, err := q.db.Query(ctx, listSantaRuleExcludeLabels, arg.RuleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SantaRuleExcludeLabel{}
	for rows.Next() {
		var i SantaRuleExcludeLabel
		if err := rows.Scan(&i.RuleID, &i.LabelID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSantaRuleIncludeIDs = `-- name: ListSantaRuleIncludeIDs :many
SELECT id
FROM santa_rule_includes
WHERE rule_id = $1
ORDER BY position, id
`

type ListSantaRuleIncludeIDsParams struct {
	RuleID int64 `json:"rule_id"`
}

func (q *Queries) ListSantaRuleIncludeIDs(ctx context.Context, arg ListSantaRuleIncludeIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listSantaRuleIncludeIDs, arg.RuleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSantaRuleIncludes = `-- name: ListSantaRuleIncludes :many
SELECT
    rule_id,
    id,
    position,
    policy::text,
    COALESCE(cel_expression, '') AS cel_expression,
    label_id
FROM santa_rule_includes
WHERE rule_id = ANY($1::bigint[])
ORDER BY rule_id, position, id
`

type ListSantaRuleIncludesParams struct {
	RuleIds []int64 `json:"rule_ids"`
}

type ListSantaRuleIncludesRow struct {
	RuleID        int64  `json:"rule_id"`
	ID            int64  `json:"id"`
	Position      int32  `json:"position"`
	Policy        string `json:"policy"`
	CelExpression string `json:"cel_expression"`
	LabelID       int64  `json:"label_id"`
}

func (q *Queries) ListSantaRuleIncludes(ctx context.Context, arg ListSantaRuleIncludesParams) ([]ListSantaRuleIncludesRow, error) {
	rows, err := q.db.Query(ctx, listSantaRuleIncludes, arg.RuleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSantaRuleIncludesRow{}
	for rows.Next() {
		var i ListSantaRuleIncludesRow
		if err := rows.Scan(
			&i.RuleID,
			&i.ID,
			&i.Position,
			&i.Policy,
			&i.CelExpression,
			&i.LabelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSantaRuleTargets = `-- name: ListSantaRuleTargets :many
WITH candidate_sources AS (
    SELECT
        'binary'::text AS target_type,
        e.sha256 AS identifier,
        NULLIF(e.file_bundle_name, '') AS display_name,
        NULL::text AS certificate_common_name,
        NULL::text AS certificate_organization,
        NULL::text AS certificate_organizational_unit,
        NULLIF(e.file_name, '') AS file_name,
        NULLIF(e.file_bundle_id, '') AS bundle_identifier,
        NULLIF(e.file_bundle_path, '') AS path,
        COALESCE(NULLIF(e.file_bundle_version_string, ''), NULLIF(e.file_bundle_version, '')) AS version,
        0::integer AS binary_count,
        0::integer AS collected_binary_count,
        true AS complete
    FROM santa_executables e
    WHERE e.sha256 <> ''
    UNION ALL
    SELECT
        'binary'::text,
        p.executable_sha256,
        COALESCE(NULLIF(st.display_name, ''), NULLIF(st.name, '')),
        NULL::text,
        NULL::text,
        NULL::text,
        NULL::text,
        NULLIF(s.bundle_identifier, ''),
        COALESCE(NULLIF(p.executable_path, ''), NULLIF(p.installed_path, '')),
        NULLIF(s.version, ''),
        0::integer,
        0::integer,
        true
    FROM host_software_installed_paths p
    JOIN software s ON s.id = p.software_id
    JOIN software_titles st ON st.id = s.title_id
    WHERE p.executable_sha256 IS NOT NULL AND p.executable_sha256 <> ''
    UNION ALL
    SELECT
        'certificate'::text,
        c.sha256,
        NULL::text,
        NULLIF(c.common_name, ''),
        NULLIF(c.organization, ''),
        NULLIF(c.organizational_unit, ''),
        NULL::text,
        NULL::text,
        NULL::text,
        NULL::text,
        0::integer,
        0::integer,
        true
    FROM santa_certificates c
    WHERE c.sha256 <> ''
    UNION ALL
    SELECT
        'teamid'::text,
        e.team_id,
        NULL::text,
        NULL::text,
        NULLIF(c.organization, ''),
        NULLIF(c.organizational_unit, ''),
        NULLIF(e.file_name, ''),
        NULLIF(e.file_bundle_id, ''),
        NULLIF(e.file_bundle_path, ''),
        COALESCE(NULLIF(e.file_bundle_version_string, ''), NULLIF(e.file_bundle_version, '')),
        0::integer,
        0::integer,
        true
    FROM santa_executables e
    LEFT JOIN santa_executable_signing_chains esc ON esc.executable_id = e.id
    LEFT JOIN santa_signing_chain_entries sce ON sce.signing_chain_id = esc.signing_chain_id
    LEFT JOIN santa_certificates c ON c.id = sce.certificate_id AND c.organizational_unit = e.team_id
    WHERE e.team_id <> ''
    UNION ALL
    SELECT
        'teamid'::text,
        p.team_identifier,
        NULL::text,
        NULL::text,
        NULL::text,
        NULL::text,
        NULL::text,
        NULLIF(s.bundle_identifier, ''),
        COALESCE(NULLIF(p.executable_path, ''), NULLIF(p.installed_path, '')),
        NULLIF(s.version, ''),
        0::integer,
        0::integer,
        true
    FROM host_software_installed_paths p
    JOIN software s ON s.id = p.software_id
    JOIN software_titles st ON st.id = s.title_id
    WHERE p.team_identifier <> ''
    UNION ALL
    SELECT
        'signingid'::text,
        e.signing_id,
        NULLIF(e.file_bundle_name, ''),
        NULL::text,
        NULL::text,
        NULL::text,
        NULLIF(e.file_name, ''),
        NULLIF(e.file_bundle_id, ''),
        NULLIF(e.file_bundle_path, ''),
        COALESCE(NULLIF(e.file_bundle_version_string, ''), NULLIF(e.file_bundle_version, '')),
        0::integer,
        0::integer,
        true
    FROM santa_executables e
    WHERE e.signing_id <> ''
    UNION ALL
    SELECT
        'signingid'::text,
        p.team_identifier || ':' || s.bundle_identifier,
        COALESCE(NULLIF(st.display_name, ''), NULLIF(st.name, '')),
        NULL::text,
        NULL::text,
        NULL::text,
        NULL::text,
        NULLIF(s.bundle_identifier, ''),
        COALESCE(NULLIF(p.executable_path, ''), NULLIF(p.installed_path, '')),
        NULLIF(s.version, ''),
        0::integer,
        0::integer,
        true
    FROM host_software_installed_paths p
    JOIN software s ON s.id = p.software_id
    JOIN software_titles st ON st.id = s.title_id
    WHERE p.team_identifier <> '' AND s.bundle_identifier <> ''
    UNION ALL
    SELECT
        'cdhash'::text,
        e.cdhash,
        NULLIF(e.file_bundle_name, ''),
        NULL::text,
        NULL::text,
        NULL::text,
        NULLIF(e.file_name, ''),
        NULLIF(e.file_bundle_id, ''),
        NULLIF(e.file_bundle_path, ''),
        COALESCE(NULLIF(e.file_bundle_version_string, ''), NULLIF(e.file_bundle_version, '')),
        0::integer,
        0::integer,
        true
    FROM santa_executables e
    WHERE e.cdhash <> ''
    UNION ALL
    SELECT
        'cdhash'::text,
        p.cdhash_sha256,
        COALESCE(NULLIF(st.display_name, ''), NULLIF(st.name, '')),
        NULL::text,
        NULL::text,
        NULL::text,
        NULL::text,
        NULLIF(s.bundle_identifier, ''),
        COALESCE(NULLIF(p.executable_path, ''), NULLIF(p.installed_path, '')),
        NULLIF(s.version, ''),
        0::integer,
        0::integer,
        true
    FROM host_software_installed_paths p
    JOIN software s ON s.id = p.software_id
    JOIN software_titles st ON st.id = s.title_id
    WHERE p.cdhash_sha256 IS NOT NULL AND p.cdhash_sha256 <> ''
    UNION ALL
    SELECT
        'bundle'::text,
        b.sha256,
        NULLIF(b.name, ''),
        NULL::text,
        NULL::text,
        NULL::text,
        NULL::text,
        NULLIF(b.bundle_id, ''),
        NULLIF(b.path, ''),
        COALESCE(NULLIF(b.version_string, ''), NULLIF(b.version, '')),
        b.binary_count,
        COUNT(be.executable_id)::integer,
        b.uploaded_at IS NOT NULL
    FROM santa_bundles b
    LEFT JOIN santa_bundle_executables be ON be.bundle_id = b.id
    WHERE b.sha256 <> ''
    GROUP BY b.id
),
targets AS (
    SELECT
        target_type,
        identifier,
        COALESCE(
            CASE WHEN COUNT(DISTINCT NULLIF(display_name, '')) = 1 THEN MIN(NULLIF(display_name, '')) END,
            ''
        )::text AS display_name,
        COALESCE(
            CASE
                WHEN COUNT(DISTINCT NULLIF(certificate_common_name, '')) = 1
                THEN MIN(NULLIF(certificate_common_name, ''))
            END,
            ''
        )::text AS certificate_common_name,
        COALESCE(
            CASE
                WHEN COUNT(DISTINCT NULLIF(certificate_organization, '')) = 1
                THEN MIN(NULLIF(certificate_organization, ''))
            END,
            ''
        )::text AS certificate_organization,
        COALESCE(
            CASE
                WHEN COUNT(DISTINCT NULLIF(certificate_organizational_unit, '')) = 1
                THEN MIN(NULLIF(certificate_organizational_unit, ''))
            END,
            ''
        )::text AS certificate_organizational_unit,
        COALESCE(
            CASE WHEN COUNT(DISTINCT NULLIF(file_name, '')) = 1 THEN MIN(NULLIF(file_name, '')) END,
            ''
        )::text AS file_name,
        COALESCE(
            CASE
                WHEN COUNT(DISTINCT NULLIF(bundle_identifier, '')) = 1
                THEN MIN(NULLIF(bundle_identifier, ''))
            END,
            ''
        )::text AS bundle_identifier,
        COALESCE(
            CASE WHEN COUNT(DISTINCT NULLIF(path, '')) = 1 THEN MIN(NULLIF(path, '')) END,
            ''
        )::text AS path,
        COALESCE(
            CASE WHEN COUNT(DISTINCT NULLIF(version, '')) = 1 THEN MIN(NULLIF(version, '')) END,
            ''
        )::text AS version,
        max(binary_count)::integer AS binary_count,
        max(collected_binary_count)::integer AS collected_binary_count,
        bool_or(complete) AS complete,
        COALESCE(
            string_agg(
                DISTINCT concat_ws(
                    ' ',
                    NULLIF(display_name, ''),
                    NULLIF(certificate_common_name, ''),
                    NULLIF(certificate_organization, ''),
                    NULLIF(certificate_organizational_unit, ''),
                    NULLIF(file_name, ''),
                    NULLIF(bundle_identifier, ''),
                    NULLIF(path, ''),
                    NULLIF(version, '')
                ),
                ' '
            ),
            ''
        )::text AS search_text
    FROM candidate_sources
    WHERE identifier <> ''
    GROUP BY target_type, identifier
)
SELECT
    t.target_type,
    t.identifier,
    t.display_name,
    t.certificate_common_name,
    t.certificate_organization,
    t.certificate_organizational_unit,
    t.file_name,
    t.bundle_identifier,
    t.path,
    t.version,
    t.binary_count,
    t.collected_binary_count,
    COUNT(r.id)::integer AS rule_count,
    t.complete
FROM targets t
LEFT JOIN santa_rules r
    ON r.rule_type::text = t.target_type AND r.identifier = t.identifier
WHERE
    ($1::text = ''
        OR t.identifier ILIKE '%' || $1::text || '%'
        OR t.display_name ILIKE '%' || $1::text || '%'
        OR t.certificate_common_name ILIKE '%' || $1::text || '%'
        OR t.certificate_organization ILIKE '%' || $1::text || '%'
        OR t.certificate_organizational_unit ILIKE '%' || $1::text || '%'
        OR t.file_name ILIKE '%' || $1::text || '%'
        OR t.bundle_identifier ILIKE '%' || $1::text || '%'
        OR t.path ILIKE '%' || $1::text || '%'
        OR t.version ILIKE '%' || $1::text || '%'
        OR t.search_text ILIKE '%' || $1::text || '%')
    AND ($2::text = '' OR t.target_type = $2::text)
GROUP BY
    t.target_type,
    t.identifier,
    t.display_name,
    t.certificate_common_name,
    t.certificate_organization,
    t.certificate_organizational_unit,
    t.file_name,
    t.bundle_identifier,
    t.path,
    t.version,
    t.binary_count,
    t.collected_binary_count,
    t.complete
ORDER BY
    CASE t.target_type
        WHEN 'bundle' THEN 1
        WHEN 'signingid' THEN 2
        WHEN 'teamid' THEN 3
        WHEN 'certificate' THEN 4
        WHEN 'binary' THEN 5
        WHEN 'cdhash' THEN 6
        ELSE 7
    END,
    lower(COALESCE(NULLIF(t.display_name, ''), NULLIF(t.certificate_common_name, ''), t.identifier)),
    t.identifier
LIMIT $3
`

type ListSantaRuleTargetsParams struct {
	Q          string `json:"q"`
	TargetType string `json:"target_type"`
	LimitCount int32  `json:"limit_count"`
}

type ListSantaRuleTargetsRow struct {
	TargetType                    string `json:"target_type"`
	Identifier                    string `json:"identifier"`
	DisplayName                   string `json:"display_name"`
	CertificateCommonName         string `json:"certificate_common_name"`
	CertificateOrganization       string `json:"certificate_organization"`
	CertificateOrganizationalUnit string `json:"certificate_organizational_unit"`
	FileName                      string `json:"file_name"`
	BundleIdentifier              string `json:"bundle_identifier"`
	Path                          string `json:"path"`
	Version                       string `json:"version"`
	BinaryCount                   int32  `json:"binary_count"`
	CollectedBinaryCount          int32  `json:"collected_binary_count"`
	RuleCount                     int32  `json:"rule_count"`
	Complete                      bool   `json:"complete"`
}

func (q *Queries) ListSantaRuleTargets(ctx context.Context, arg ListSantaRuleTargetsParams) ([]ListSantaRuleTargetsRow, error) {
	rows, err := q.db.Query(ctx, listSantaRuleTargets, arg.Q, arg.TargetType, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSantaRuleTargetsRow{}
	for rows.Next() {
		var i ListSantaRuleTargetsRow
		if err := rows.Scan(
			&i.TargetType,
			&i.Identifier,
			&i.DisplayName,
			&i.CertificateCommonName,
			&i.CertificateOrganization,
			&i.CertificateOrganizationalUnit,
			&i.FileName,
			&i.BundleIdentifier,
			&i.Path,
			&i.Version,
			&i.BinaryCount,
			&i.CollectedBinaryCount,
			&i.RuleCount,
			&i.Complete,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSantaRulesForHost = `-- name: ListSantaRulesForHost :many
WITH host_labels AS (
    SELECT label_id
    FROM label_membership
    WHERE host_id = $1
),
matching_includes AS (
    SELECT
        r.id AS rule_id,
        r.rule_type,
        r.identifier,
        r.name,
        r.description,
        i.policy,
        COALESCE(i.cel_expression, '') AS cel_expression,
        r.custom_message,
        r.custom_url,
        i.id AS matched_include_id,
        CASE r.rule_type
            WHEN 'cdhash' THEN 1
            WHEN 'binary' THEN 2
            WHEN 'signingid' THEN 3
            WHEN 'certificate' THEN 4
            WHEN 'teamid' THEN 5
            WHEN 'bundle' THEN 6
            ELSE 7
        END AS rule_type_sort,
        row_number() OVER (PARTITION BY r.id ORDER BY i.position, i.id) AS include_rank
    FROM santa_rules r
    JOIN santa_rule_includes i ON i.rule_id = r.id
    JOIN host_labels include_hl ON include_hl.label_id = i.label_id
    WHERE NOT EXISTS (
        SELECT 1
        FROM santa_rule_exclude_labels el
        JOIN host_labels hl ON hl.label_id = el.label_id
        WHERE el.rule_id = r.id
    )
),
selected_includes AS (
    SELECT rule_id, rule_type, identifier, name, description, policy, cel_expression, custom_message, custom_url, matched_include_id, rule_type_sort, include_rank
    FROM matching_includes
    WHERE include_rank = 1
),
expanded_rules AS (
    SELECT
        rule_id,
        rule_type,
        identifier,
        name,
        description,
        policy,
        cel_expression,
        custom_message,
        custom_url,
        ''::text AS notification_app_name,
        matched_include_id,
        rule_type_sort
    FROM selected_includes
    WHERE rule_type <> 'bundle'
    UNION ALL
    SELECT
        si.rule_id,
        'binary'::santa_rule_type AS rule_type,
        e.sha256 AS identifier,
        si.name,
        si.description,
        si.policy,
        si.cel_expression,
        si.custom_message,
        si.custom_url,
        COALESCE(NULLIF(b.name, ''), NULLIF(b.bundle_id, ''), b.sha256) AS notification_app_name,
        si.matched_include_id,
        2 AS rule_type_sort
    FROM selected_includes si
    JOIN santa_bundles b ON b.sha256 = si.identifier AND b.uploaded_at IS NOT NULL
    JOIN santa_bundle_executables be ON be.bundle_id = b.id
    JOIN santa_executables e ON e.id = be.executable_id
    WHERE si.rule_type = 'bundle'
      AND e.sha256 <> ''
)
SELECT
    rule_id,
    rule_type::text,
    identifier,
    name,
    description,
    policy::text,
    cel_expression,
    custom_message,
    custom_url,
    notification_app_name,
    matched_include_id,
    rule_type_sort
FROM expanded_rules
ORDER BY rule_type_sort, identifier, rule_id
`

type ListSantaRulesForHostParams struct {
	HostID int64 `json:"host_id"`
}

type ListSantaRulesForHostRow struct {
	RuleID              int64  `json:"rule_id"`
	RuleType            string `json:"rule_type"`
	Identifier          string `json:"identifier"`
	Name                string `json:"name"`
	Description         string `json:"description"`
	Policy              string `json:"policy"`
	CelExpression       string `json:"cel_expression"`
	CustomMessage       string `json:"custom_message"`
	CustomURL           string `json:"custom_url"`
	NotificationAppName string `json:"notification_app_name"`
	MatchedIncludeID    int64  `json:"matched_include_id"`
	RuleTypeSort        int32  `json:"rule_type_sort"`
}

func (q *Queries) ListSantaRulesForHost(ctx context.Context, arg ListSantaRulesForHostParams) ([]ListSantaRulesForHostRow, error) {
	rows, err := q.db.Query(ctx, listSantaRulesForHost, arg.HostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSantaRulesForHostRow{}
	for rows.Next() {
		var i ListSantaRulesForHostRow
		if err := rows.Scan(
			&i.RuleID,
			&i.RuleType,
			&i.Identifier,
			&i.Name,
			&i.Description,
			&i.Policy,
			&i.CelExpression,
			&i.CustomMessage,
			&i.CustomURL,
			&i.NotificationAppName,
			&i.MatchedIncludeID,
			&i.RuleTypeSort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSantaRulesForHostPage = `-- name: ListSantaRulesForHostPage :many
WITH host_labels AS (
    SELECT label_id
    FROM label_membership
    WHERE host_id = $3
),
matching_includes AS (
    SELECT
        r.id AS rule_id,
        r.rule_type,
        r.identifier,
        r.name,
        r.description,
        i.policy,
        COALESCE(i.cel_expression, '') AS cel_expression,
        r.custom_message,
        r.custom_url,
        i.id AS matched_include_id,
        CASE r.rule_type
            WHEN 'cdhash' THEN 1
            WHEN 'binary' THEN 2
            WHEN 'signingid' THEN 3
            WHEN 'certificate' THEN 4
            WHEN 'teamid' THEN 5
            WHEN 'bundle' THEN 6
            ELSE 7
        END AS rule_type_sort,
        row_number() OVER (PARTITION BY r.id ORDER BY i.position, i.id) AS include_rank
    FROM santa_rules r
    JOIN santa_rule_includes i ON i.rule_id = r.id
    JOIN host_labels include_hl ON include_hl.label_id = i.label_id
    WHERE NOT EXISTS (
        SELECT 1
        FROM santa_rule_exclude_labels el
        JOIN host_labels hl ON hl.label_id = el.label_id
        WHERE el.rule_id = r.id
    )
),
selected_includes AS (
    SELECT rule_id, rule_type, identifier, name, description, policy, cel_expression, custom_message, custom_url, matched_include_id, rule_type_sort, include_rank
    FROM matching_includes
    WHERE include_rank = 1
),
expanded_rules AS (
    SELECT
        rule_id,
        rule_type,
        identifier,
        name,
        description,
        policy,
        cel_expression,
        custom_message,
        custom_url,
        ''::text AS notification_app_name,
        matched_include_id,
        rule_type_sort
    FROM selected_includes
    WHERE rule_type <> 'bundle'
    UNION ALL
    SELECT
        si.rule_id,
        'binary'::santa_rule_type AS rule_type,
        e.sha256 AS identifier,
        si.name,
        si.description,
        si.policy,
        si.cel_expression,
        si.custom_message,
        si.custom_url,
        COALESCE(NULLIF(b.name, ''), NULLIF(b.bundle_id, ''), b.sha256) AS notification_app_name,
        si.matched_include_id,
        2 AS rule_type_sort
    FROM selected_includes si
    JOIN santa_bundles b ON b.sha256 = si.identifier AND b.uploaded_at IS NOT NULL
    JOIN santa_bundle_executables be ON be.bundle_id = b.id
    JOIN santa_executables e ON e.id = be.executable_id
    WHERE si.rule_type = 'bundle'
      AND e.sha256 <> ''
)
SELECT
    rule_id,
    rule_type::text,
    identifier,
    name,
    description,
    policy::text,
    cel_expression,
    custom_message,
    custom_url,
    notification_app_name,
    matched_include_id,
    rule_type_sort
FROM expanded_rules
ORDER BY rule_type_sort, identifier, rule_id
LIMIT $2 OFFSET $1
`

type ListSantaRulesForHostPageParams struct {
	OffsetCount int32 `json:"offset_count"`
	LimitCount  int32 `json:"limit_count"`
	HostID      int64 `json:"host_id"`
}

type ListSantaRulesForHostPageRow struct {
	RuleID              int64  `json:"rule_id"`
	RuleType            string `json:"rule_type"`
	Identifier          string `json:"identifier"`
	Name                string `json:"name"`
	Description         string `json:"description"`
	Policy              string `json:"policy"`
	CelExpression       string `json:"cel_expression"`
	CustomMessage       string `json:"custom_message"`
	CustomURL           string `json:"custom_url"`
	NotificationAppName string `json:"notification_app_name"`
	MatchedIncludeID    int64  `json:"matched_include_id"`
	RuleTypeSort        int32  `json:"rule_type_sort"`
}

func (q *Queries) ListSantaRulesForHostPage(ctx context.Context, arg ListSantaRulesForHostPageParams) ([]ListSantaRulesForHostPageRow, error) {
	rows, err := q.db.Query(ctx, listSantaRulesForHostPage, arg.OffsetCount, arg.LimitCount, arg.HostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSantaRulesForHostPageRow{}
	for rows.Next() {
		var i ListSantaRulesForHostPageRow
		if err := rows.Scan(
			&i.RuleID,
			&i.RuleType,
			&i.Identifier,
			&i.Name,
			&i.Description,
			&i.Policy,
			&i.CelExpression,
			&i.CustomMessage,
			&i.CustomURL,
			&i.NotificationAppName,
			&i.MatchedIncludeID,
			&i.RuleTypeSort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const normalizeSantaConfigurationPositions = `-- name: NormalizeSantaConfigurationPositions :exec
UPDATE santa_configurations
SET position = -position - 1
`

func (q *Queries) NormalizeSantaConfigurationPositions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, normalizeSantaConfigurationPositions)
	return err
}

const normalizeSantaRuleIncludePositions = `-- name: NormalizeSantaRuleIncludePositions :exec
UPDATE santa_rule_includes
SET position = -position - 1
WHERE rule_id = $1
`

type NormalizeSantaRuleIncludePositionsParams struct {
	RuleID int64 `json:"rule_id"`
}

func (q *Queries) NormalizeSantaRuleIncludePositions(ctx context.Context, arg NormalizeSantaRuleIncludePositionsParams) error {
	_, err := q.db.Exec(ctx, normalizeSantaRuleIncludePositions, arg.RuleID)
	return err
}

const resolveSantaConfigurationForHost = `-- name: ResolveSantaConfigurationForHost :one
SELECT
    c.id, c.name, c.description, c.position, c.client_mode, c.enable_bundles, c.enable_transitive_rules, c.enable_all_event_upload, c.full_sync_interval_seconds, c.batch_size, c.allowed_path_regex, c.blocked_path_regex, c.removable_media_action, c.removable_media_remount_flags, c.encrypted_removable_media_action, c.encrypted_removable_media_remount_flags, c.event_detail_url, c.event_detail_text, c.created_at, c.updated_at,
    l.id AS label_id,
    l.name AS label_name
FROM santa_configurations c
JOIN LATERAL (
    SELECT
        include_label.id,
        include_label.name
    FROM santa_configuration_targets t
    JOIN label_membership lm ON lm.label_id = t.label_id AND lm.host_id = $1
    JOIN labels include_label ON include_label.id = t.label_id
    WHERE t.configuration_id = c.id
      AND t.effect = 'include'
    ORDER BY include_label.name, include_label.id
    LIMIT 1
) l ON true
WHERE NOT EXISTS (
    SELECT 1
    FROM santa_configuration_targets t
    JOIN label_membership lm ON lm.label_id = t.label_id AND lm.host_id = $1
    WHERE t.configuration_id = c.id
      AND t.effect = 'exclude'
)
ORDER BY c.position, c.id
LIMIT 1
`

type ResolveSantaConfigurationForHostParams struct {
	HostID int64 `json:"host_id"`
}

type ResolveSantaConfigurationForHostRow struct {
	SantaConfiguration SantaConfiguration `json:"santa_configuration"`
	LabelID            int64              `json:"label_id"`
	LabelName          string             `json:"label_name"`
}

func (q *Queries) ResolveSantaConfigurationForHost(ctx context.Context, arg ResolveSantaConfigurationForHostParams) (ResolveSantaConfigurationForHostRow, error) {
	row := q.db.QueryRow(ctx, resolveSantaConfigurationForHost, arg.HostID)
	var i ResolveSantaConfigurationForHostRow
	err := row.Scan(
		&i.SantaConfiguration.ID,
		&i.SantaConfiguration.Name,
		&i.SantaConfiguration.Description,
		&i.SantaConfiguration.Position,
		&i.SantaConfiguration.ClientMode,
		&i.SantaConfiguration.EnableBundles,
		&i.SantaConfiguration.EnableTransitiveRules,
		&i.SantaConfiguration.EnableAllEventUpload,
		&i.SantaConfiguration.FullSyncIntervalSeconds,
		&i.SantaConfiguration.BatchSize,
		&i.SantaConfiguration.AllowedPathRegex,
		&i.SantaConfiguration.BlockedPathRegex,
		&i.SantaConfiguration.RemovableMediaAction,
		&i.SantaConfiguration.RemovableMediaRemountFlags,
		&i.SantaConfiguration.EncryptedRemovableMediaAction,
		&i.SantaConfiguration.EncryptedRemovableMediaRemountFlags,
		&i.SantaConfiguration.EventDetailURL,
		&i.SantaConfiguration.EventDetailText,
		&i.SantaConfiguration.CreatedAt,
		&i.SantaConfiguration.UpdatedAt,
		&i.LabelID,
		&i.LabelName,
	)
	return i, err
}

const santaRuleExists = `-- name: SantaRuleExists :one
SELECT EXISTS (
    SELECT 1
    FROM santa_rules
    WHERE id = $1
)
`

type SantaRuleExistsParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) SantaRuleExists(ctx context.Context, arg SantaRuleExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, santaRuleExists, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setSantaConfigurationPositions = `-- name: SetSantaConfigurationPositions :exec
UPDATE santa_configurations c
SET position = -ordered.position
FROM unnest($1::bigint[]) WITH ORDINALITY AS ordered(id, position)
WHERE c.id = ordered.id
`

type SetSantaConfigurationPositionsParams struct {
	OrderedIds []int64 `json:"ordered_ids"`
}

func (q *Queries) SetSantaConfigurationPositions(ctx context.Context, arg SetSantaConfigurationPositionsParams) error {
	_, err := q.db.Exec(ctx, setSantaConfigurationPositions, arg.OrderedIds)
	return err
}

const setSantaRuleIncludePositions = `-- name: SetSantaRuleIncludePositions :exec
UPDATE santa_rule_includes i
SET position = -ordered.position
FROM unnest($2::bigint[]) WITH ORDINALITY AS ordered(id, position)
WHERE i.id = ordered.id AND i.rule_id = $1
`

type SetSantaRuleIncludePositionsParams struct {
	RuleID     int64   `json:"rule_id"`
	OrderedIds []int64 `json:"ordered_ids"`
}

func (q *Queries) SetSantaRuleIncludePositions(ctx context.Context, arg SetSantaRuleIncludePositionsParams) error {
	_, err := q.db.Exec(ctx, setSantaRuleIncludePositions, arg.RuleID, arg.OrderedIds)
	return err
}

const updateSantaConfiguration = `-- name: UpdateSantaConfiguration :one
UPDATE santa_configurations
SET
    name = $1,
    description = $2,
    client_mode = $3::santa_client_mode,
    enable_bundles = $4,
    enable_transitive_rules = $5,
    enable_all_event_upload = $6,
    full_sync_interval_seconds = $7::integer,
    batch_size = $8::integer,
    allowed_path_regex = $9,
    blocked_path_regex = $10,
    removable_media_action = $11::santa_removable_media_action,
    removable_media_remount_flags = $12::text[],
    encrypted_removable_media_action = $13::santa_removable_media_action,
    encrypted_removable_media_remount_flags = $14::text[],
    event_detail_url = $15,
    event_detail_text = $16,
    updated_at = now()
WHERE id = $17
RETURNING id, name, description, position, client_mode, enable_bundles, enable_transitive_rules, enable_all_event_upload, full_sync_interval_seconds, batch_size, allowed_path_regex, blocked_path_regex, removable_media_action, removable_media_remount_flags, encrypted_removable_media_action, encrypted_removable_media_remount_flags, event_detail_url, event_detail_text, created_at, updated_at
`

type UpdateSantaConfigurationParams struct {
	Name                                string                     `json:"name"`
	Description                         string                     `json:"description"`
	ClientMode                          SantaClientMode            `json:"client_mode"`
	EnableBundles                       bool                       `json:"enable_bundles"`
	EnableTransitiveRules               bool                       `json:"enable_transitive_rules"`
	EnableAllEventUpload                bool                       `json:"enable_all_event_upload"`
	FullSyncIntervalSeconds             int32                      `json:"full_sync_interval_seconds"`
	BatchSize                           int32                      `json:"batch_size"`
	AllowedPathRegex                    string                     `json:"allowed_path_regex"`
	BlockedPathRegex                    string                     `json:"blocked_path_regex"`
	RemovableMediaAction                *SantaRemovableMediaAction `json:"removable_media_action"`
	RemovableMediaRemountFlags          []string                   `json:"removable_media_remount_flags"`
	EncryptedRemovableMediaAction       *SantaRemovableMediaAction `json:"encrypted_removable_media_action"`
	EncryptedRemovableMediaRemountFlags []string                   `json:"encrypted_removable_media_remount_flags"`
	EventDetailURL                      string                     `json:"event_detail_url"`
	EventDetailText                     string                     `json:"event_detail_text"`
	ID                                  int64                      `json:"id"`
}

func (q *Queries) UpdateSantaConfiguration(ctx context.Context, arg UpdateSantaConfigurationParams) (SantaConfiguration, error) {
	row := q.db.QueryRow(ctx, updateSantaConfiguration,
		arg.Name,
		arg.Description,
		arg.ClientMode,
		arg.EnableBundles,
		arg.EnableTransitiveRules,
		arg.EnableAllEventUpload,
		arg.FullSyncIntervalSeconds,
		arg.BatchSize,
		arg.AllowedPathRegex,
		arg.BlockedPathRegex,
		arg.RemovableMediaAction,
		arg.RemovableMediaRemountFlags,
		arg.EncryptedRemovableMediaAction,
		arg.EncryptedRemovableMediaRemountFlags,
		arg.EventDetailURL,
		arg.EventDetailText,
		arg.ID,
	)
	var i SantaConfiguration
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.ClientMode,
		&i.EnableBundles,
		&i.EnableTransitiveRules,
		&i.EnableAllEventUpload,
		&i.FullSyncIntervalSeconds,
		&i.BatchSize,
		&i.AllowedPathRegex,
		&i.BlockedPathRegex,
		&i.RemovableMediaAction,
		&i.RemovableMediaRemountFlags,
		&i.EncryptedRemovableMediaAction,
		&i.EncryptedRemovableMediaRemountFlags,
		&i.EventDetailURL,
		&i.EventDetailText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSantaRule = `-- name: UpdateSantaRule :one
UPDATE santa_rules
SET
    rule_type = $1::santa_rule_type,
    identifier = $2,
    name = $3,
    description = $4,
    custom_message = $5,
    custom_url = $6,
    updated_at = now()
WHERE id = $7
RETURNING id, rule_type, identifier, name, description, custom_message, custom_url, created_at, updated_at
`

type UpdateSantaRuleParams struct {
	RuleType      SantaRuleType `json:"rule_type"`
	Identifier    string        `json:"identifier"`
	Name          string        `json:"name"`
	Description   string        `json:"description"`
	CustomMessage string        `json:"custom_message"`
	CustomURL     string        `json:"custom_url"`
	ID            int64         `json:"id"`
}

func (q *Queries) UpdateSantaRule(ctx context.Context, arg UpdateSantaRuleParams) (SantaRule, error) {
	row := q.db.QueryRow(ctx, updateSantaRule,
		arg.RuleType,
		arg.Identifier,
		arg.Name,
		arg.Description,
		arg.CustomMessage,
		arg.CustomURL,
		arg.ID,
	)
	var i SantaRule
	err := row.Scan(
		&i.ID,
		&i.RuleType,
		&i.Identifier,
		&i.Name,
		&i.Description,
		&i.CustomMessage,
		&i.CustomURL,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSantaHostObservation = `-- name: UpsertSantaHostObservation :exec
INSERT INTO santa_hosts (
    host_id,
    machine_id,
    serial_number,
    santa_version,
    client_mode_reported,
    primary_user,
    primary_user_groups,
    sip_status,
    os_build,
    model_identifier,
    last_seen_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5::santa_client_mode,
    $6,
    $7,
    $8,
    $9,
    $10,
    COALESCE($11::timestamptz, now())
)
ON CONFLICT (host_id) DO UPDATE SET
    machine_id = EXCLUDED.machine_id,
    serial_number = EXCLUDED.serial_number,
    santa_version = EXCLUDED.santa_version,
    client_mode_reported = EXCLUDED.client_mode_reported,
    primary_user = EXCLUDED.primary_user,
    primary_user_groups = EXCLUDED.primary_user_groups,
    sip_status = EXCLUDED.sip_status,
    os_build = EXCLUDED.os_build,
    model_identifier = EXCLUDED.model_identifier,
    last_seen_at = EXCLUDED.last_seen_at,
    updated_at = now()
`

type UpsertSantaHostObservationParams struct {
	HostID             int64           `json:"host_id"`
	MachineID          string          `json:"machine_id"`
	SerialNumber       string          `json:"serial_number"`
	SantaVersion       string          `json:"santa_version"`
	ClientModeReported SantaClientMode `json:"client_mode_reported"`
	PrimaryUser        string          `json:"primary_user"`
	PrimaryUserGroups  []string        `json:"primary_user_groups"`
	SipStatus          *int16          `json:"sip_status"`
	OSBuild            string          `json:"os_build"`
	ModelIdentifier    string          `json:"model_identifier"`
	LastSeenAt         *time.Time      `json:"last_seen_at"`
}

func (q *Queries) UpsertSantaHostObservation(ctx context.Context, arg UpsertSantaHostObservationParams) error {
	_, err := q.db.Exec(ctx, upsertSantaHostObservation,
		arg.HostID,
		arg.MachineID,
		arg.SerialNumber,
		arg.SantaVersion,
		arg.ClientModeReported,
		arg.PrimaryUser,
		arg.PrimaryUserGroups,
		arg.SipStatus,
		arg.OSBuild,
		arg.ModelIdentifier,
		arg.LastSeenAt,
	)
	return err
}
