// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: software.sql

package sqlc

import (
	"context"
	"time"
)

const deleteHostSoftware = `-- name: DeleteHostSoftware :exec
DELETE FROM host_software
WHERE host_id = $1
`

type DeleteHostSoftwareParams struct {
	HostID int64 `json:"host_id"`
}

func (q *Queries) DeleteHostSoftware(ctx context.Context, arg DeleteHostSoftwareParams) error {
	_, err := q.db.Exec(ctx, deleteHostSoftware, arg.HostID)
	return err
}

const listSoftwareForHost = `-- name: ListSoftwareForHost :many
SELECT
    software.id,
    software.name,
    software.version,
    software.source,
    software.bundle_identifier,
    host_software.last_seen_at,
    host_software.last_opened_at
FROM host_software
JOIN software ON software.id = host_software.software_id
WHERE host_software.host_id = $1
ORDER BY lower(software.name), software.version, software.source
`

type ListSoftwareForHostParams struct {
	HostID int64 `json:"host_id"`
}

type ListSoftwareForHostRow struct {
	ID               int64      `json:"id"`
	Name             string     `json:"name"`
	Version          string     `json:"version"`
	Source           string     `json:"source"`
	BundleIdentifier string     `json:"bundle_identifier"`
	LastSeenAt       time.Time  `json:"last_seen_at"`
	LastOpenedAt     *time.Time `json:"last_opened_at"`
}

func (q *Queries) ListSoftwareForHost(ctx context.Context, arg ListSoftwareForHostParams) ([]ListSoftwareForHostRow, error) {
	rows, err := q.db.Query(ctx, listSoftwareForHost, arg.HostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSoftwareForHostRow{}
	for rows.Next() {
		var i ListSoftwareForHostRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Source,
			&i.BundleIdentifier,
			&i.LastSeenAt,
			&i.LastOpenedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSoftwareTitlesWithHostCount = `-- name: ListSoftwareTitlesWithHostCount :many
SELECT
    software.id,
    software.name,
    software.version,
    software.source,
    software.bundle_identifier,
    count(host_software.host_id)::integer AS host_count,
    software.created_at
FROM software
LEFT JOIN host_software ON host_software.software_id = software.id
GROUP BY software.id
ORDER BY count(host_software.host_id) DESC, lower(software.name), software.version
`

type ListSoftwareTitlesWithHostCountRow struct {
	ID               int64     `json:"id"`
	Name             string    `json:"name"`
	Version          string    `json:"version"`
	Source           string    `json:"source"`
	BundleIdentifier string    `json:"bundle_identifier"`
	HostCount        int32     `json:"host_count"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) ListSoftwareTitlesWithHostCount(ctx context.Context) ([]ListSoftwareTitlesWithHostCountRow, error) {
	rows, err := q.db.Query(ctx, listSoftwareTitlesWithHostCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSoftwareTitlesWithHostCountRow{}
	for rows.Next() {
		var i ListSoftwareTitlesWithHostCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Source,
			&i.BundleIdentifier,
			&i.HostCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHostSoftware = `-- name: UpsertHostSoftware :exec
INSERT INTO host_software (
    host_id,
    software_id,
    last_seen_at,
    last_opened_at
)
VALUES (
    $1,
    $2,
    now(),
    $3
)
ON CONFLICT (host_id, software_id) DO UPDATE SET
    last_seen_at = now(),
    last_opened_at = EXCLUDED.last_opened_at
`

type UpsertHostSoftwareParams struct {
	HostID       int64      `json:"host_id"`
	SoftwareID   int64      `json:"software_id"`
	LastOpenedAt *time.Time `json:"last_opened_at"`
}

func (q *Queries) UpsertHostSoftware(ctx context.Context, arg UpsertHostSoftwareParams) error {
	_, err := q.db.Exec(ctx, upsertHostSoftware, arg.HostID, arg.SoftwareID, arg.LastOpenedAt)
	return err
}

const upsertSoftwareTitle = `-- name: UpsertSoftwareTitle :one
INSERT INTO software (
    name,
    version,
    source,
    bundle_identifier
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (name, version, source, bundle_identifier) DO UPDATE SET
    name = EXCLUDED.name
RETURNING id
`

type UpsertSoftwareTitleParams struct {
	Name             string `json:"name"`
	Version          string `json:"version"`
	Source           string `json:"source"`
	BundleIdentifier string `json:"bundle_identifier"`
}

func (q *Queries) UpsertSoftwareTitle(ctx context.Context, arg UpsertSoftwareTitleParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertSoftwareTitle,
		arg.Name,
		arg.Version,
		arg.Source,
		arg.BundleIdentifier,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
