// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT count(*)::integer
FROM users
WHERE role = 'admin' AND deleted_at IS NULL
`

func (q *Queries) CountAdminUsers(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countAdminUsers)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    name,
    password_hash,
    role
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING
    id,
    email,
    name,
    password_hash,
    role,
    created_at,
    updated_at,
    deleted_at
`

type CreateUserParams struct {
	Email        string   `json:"email"`
	Name         string   `json:"name"`
	PasswordHash string   `json:"password_hash"`
	Role         UserRole `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    email,
    name,
    password_hash,
    role,
    created_at,
    updated_at,
    deleted_at
FROM users
WHERE email = $1 AND deleted_at IS NULL
`

type GetUserByEmailParams struct {
	Email string `json:"email"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    email,
    name,
    password_hash,
    role,
    created_at,
    updated_at,
    deleted_at
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

type GetUserByIDParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
    id,
    email,
    name,
    password_hash,
    role,
    created_at,
    updated_at,
    deleted_at
FROM users
WHERE deleted_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :one
UPDATE users
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteUserParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, softDeleteUser, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    name = COALESCE($1, name),
    role = COALESCE($2::user_role, role),
    password_hash = COALESCE($3, password_hash),
    updated_at = now()
WHERE id = $4 AND deleted_at IS NULL
RETURNING
    id,
    email,
    name,
    password_hash,
    role,
    created_at,
    updated_at,
    deleted_at
`

type UpdateUserParams struct {
	Name         *string   `json:"name"`
	Role         *UserRole `json:"role"`
	PasswordHash *string   `json:"password_hash"`
	ID           int64     `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Role,
		arg.PasswordHash,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE deleted_at IS NULL
)
`

func (q *Queries) UserExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, userExists)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
