// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const clearUserAPIKey = `-- name: ClearUserAPIKey :one
UPDATE users
SET
    api_key = NULL,
    api_key_created_at = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, email, name, password_hash, role, api_key, api_key_created_at, created_at, updated_at
`

type ClearUserAPIKeyParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) ClearUserAPIKey(ctx context.Context, arg ClearUserAPIKeyParams) (User, error) {
	row := q.db.QueryRow(ctx, clearUserAPIKey, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.APIKey,
		&i.APIKeyCreatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    name,
    password_hash,
    role
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, email, name, password_hash, role, api_key, api_key_created_at, created_at, updated_at
`

type CreateUserParams struct {
	Email        string   `json:"email"`
	Name         string   `json:"name"`
	PasswordHash string   `json:"password_hash"`
	Role         UserRole `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.APIKey,
		&i.APIKeyCreatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users
WHERE id = $1
RETURNING id
`

type DeleteUserParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteUser, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUserByAPIKey = `-- name: GetUserByAPIKey :one
SELECT id, email, name, password_hash, role, api_key, api_key_created_at, created_at, updated_at
FROM users
WHERE api_key = $1
`

type GetUserByAPIKeyParams struct {
	APIKey *string `json:"api_key"`
}

func (q *Queries) GetUserByAPIKey(ctx context.Context, arg GetUserByAPIKeyParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAPIKey, arg.APIKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.APIKey,
		&i.APIKeyCreatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, role, api_key, api_key_created_at, created_at, updated_at
FROM users
WHERE email = $1
`

type GetUserByEmailParams struct {
	Email string `json:"email"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.APIKey,
		&i.APIKeyCreatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, role, api_key, api_key_created_at, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.APIKey,
		&i.APIKeyCreatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, password_hash, role, api_key, api_key_created_at, created_at, updated_at
FROM users
ORDER BY created_at
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.Role,
			&i.APIKey,
			&i.APIKeyCreatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserAPIKey = `-- name: SetUserAPIKey :one
UPDATE users
SET
    api_key = $1,
    api_key_created_at = now(),
    updated_at = now()
WHERE id = $2
RETURNING id, email, name, password_hash, role, api_key, api_key_created_at, created_at, updated_at
`

type SetUserAPIKeyParams struct {
	APIKey *string `json:"api_key"`
	ID     int64   `json:"id"`
}

func (q *Queries) SetUserAPIKey(ctx context.Context, arg SetUserAPIKeyParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserAPIKey, arg.APIKey, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.APIKey,
		&i.APIKeyCreatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    name = $1,
    role = $2::user_role,
    password_hash = COALESCE($3, password_hash),
    updated_at = now()
WHERE id = $4
RETURNING id, email, name, password_hash, role, api_key, api_key_created_at, created_at, updated_at
`

type UpdateUserParams struct {
	Name         string   `json:"name"`
	Role         UserRole `json:"role"`
	PasswordHash *string  `json:"password_hash"`
	ID           int64    `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Role,
		arg.PasswordHash,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.APIKey,
		&i.APIKeyCreatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS (
    SELECT 1
    FROM users
)
`

func (q *Queries) UserExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, userExists)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
