// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: directory.sql

package sqlc

import (
	"context"
)

const attachDirectoryUserByEmail = `-- name: AttachDirectoryUserByEmail :exec
UPDATE users
SET
    source = $1::directory_source,
    external_id = $2::text,
    deleted_at = NULL,
    updated_at = now()
WHERE (
      (source = 'local' AND deleted_at IS NULL)
      OR (source = $1::directory_source AND deleted_at IS NOT NULL)
  )
  AND (
      lower(email) = lower(COALESCE($3::text, $4::text))
      OR lower(COALESCE(user_principal_name, '')) = lower($4::text)
  )
`

type AttachDirectoryUserByEmailParams struct {
	Source            DirectorySource `json:"source"`
	ExternalID        string          `json:"external_id"`
	Mail              *string         `json:"mail"`
	UserPrincipalName string          `json:"user_principal_name"`
}

func (q *Queries) AttachDirectoryUserByEmail(ctx context.Context, arg AttachDirectoryUserByEmailParams) error {
	_, err := q.db.Exec(ctx, attachDirectoryUserByEmail,
		arg.Source,
		arg.ExternalID,
		arg.Mail,
		arg.UserPrincipalName,
	)
	return err
}

const clearUserAPIKey = `-- name: ClearUserAPIKey :one
UPDATE users
SET
    api_key = NULL,
    api_key_created_at = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, email, name, password_hash, role, api_key, api_key_created_at, source, external_id, user_principal_name, mail_nickname, given_name, family_name, department, deleted_at, created_at, updated_at
`

type ClearUserAPIKeyParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) ClearUserAPIKey(ctx context.Context, arg ClearUserAPIKeyParams) (User, error) {
	row := q.db.QueryRow(ctx, clearUserAPIKey, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.APIKey,
		&i.APIKeyCreatedAt,
		&i.Source,
		&i.ExternalID,
		&i.UserPrincipalName,
		&i.MailNickname,
		&i.GivenName,
		&i.FamilyName,
		&i.Department,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    name,
    password_hash,
    role,
    source
)
VALUES (
    $1,
    $2,
    $3,
    $4::user_role,
    'local'
)
RETURNING id, email, name, password_hash, role, api_key, api_key_created_at, source, external_id, user_principal_name, mail_nickname, given_name, family_name, department, deleted_at, created_at, updated_at
`

type CreateUserParams struct {
	Email        string   `json:"email"`
	Name         string   `json:"name"`
	PasswordHash *string  `json:"password_hash"`
	Role         UserRole `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.APIKey,
		&i.APIKeyCreatedAt,
		&i.Source,
		&i.ExternalID,
		&i.UserPrincipalName,
		&i.MailNickname,
		&i.GivenName,
		&i.FamilyName,
		&i.Department,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users
WHERE id = $1
  AND source = 'local'
  AND deleted_at IS NULL
RETURNING id
`

type DeleteUserParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteUser, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getLoginUserByEmail = `-- name: GetLoginUserByEmail :one
SELECT id, email, name, password_hash, role, api_key, api_key_created_at, source, external_id, user_principal_name, mail_nickname, given_name, family_name, department, deleted_at, created_at, updated_at
FROM users
WHERE deleted_at IS NULL
  AND source = 'local'
  AND role IS NOT NULL
  AND password_hash IS NOT NULL
  AND (
      lower(email) = lower($1)
      OR lower(COALESCE(user_principal_name, '')) = lower($1)
  )
ORDER BY CASE WHEN lower(email) = lower($1) THEN 0 ELSE 1 END, id
LIMIT 1
`

type GetLoginUserByEmailParams struct {
	Email string `json:"email"`
}

func (q *Queries) GetLoginUserByEmail(ctx context.Context, arg GetLoginUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getLoginUserByEmail, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.APIKey,
		&i.APIKeyCreatedAt,
		&i.Source,
		&i.ExternalID,
		&i.UserPrincipalName,
		&i.MailNickname,
		&i.GivenName,
		&i.FamilyName,
		&i.Department,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSSOUserByEmail = `-- name: GetSSOUserByEmail :one
SELECT id, email, name, password_hash, role, api_key, api_key_created_at, source, external_id, user_principal_name, mail_nickname, given_name, family_name, department, deleted_at, created_at, updated_at
FROM users
WHERE deleted_at IS NULL
  AND role IS NOT NULL
  AND (
      lower(email) = lower($1)
      OR lower(COALESCE(user_principal_name, '')) = lower($1)
  )
ORDER BY CASE WHEN lower(email) = lower($1) THEN 0 ELSE 1 END, id
LIMIT 1
`

type GetSSOUserByEmailParams struct {
	Email string `json:"email"`
}

func (q *Queries) GetSSOUserByEmail(ctx context.Context, arg GetSSOUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getSSOUserByEmail, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.APIKey,
		&i.APIKeyCreatedAt,
		&i.Source,
		&i.ExternalID,
		&i.UserPrincipalName,
		&i.MailNickname,
		&i.GivenName,
		&i.FamilyName,
		&i.Department,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByAPIKey = `-- name: GetUserByAPIKey :one
SELECT id, email, name, password_hash, role, api_key, api_key_created_at, source, external_id, user_principal_name, mail_nickname, given_name, family_name, department, deleted_at, created_at, updated_at
FROM users
WHERE api_key = $1
  AND deleted_at IS NULL
  AND role IS NOT NULL
`

type GetUserByAPIKeyParams struct {
	APIKey *string `json:"api_key"`
}

func (q *Queries) GetUserByAPIKey(ctx context.Context, arg GetUserByAPIKeyParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAPIKey, arg.APIKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.APIKey,
		&i.APIKeyCreatedAt,
		&i.Source,
		&i.ExternalID,
		&i.UserPrincipalName,
		&i.MailNickname,
		&i.GivenName,
		&i.FamilyName,
		&i.Department,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, role, api_key, api_key_created_at, source, external_id, user_principal_name, mail_nickname, given_name, family_name, department, deleted_at, created_at, updated_at
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

type GetUserByIDParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.APIKey,
		&i.APIKeyCreatedAt,
		&i.Source,
		&i.ExternalID,
		&i.UserPrincipalName,
		&i.MailNickname,
		&i.GivenName,
		&i.FamilyName,
		&i.Department,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, password_hash, role, api_key, api_key_created_at, source, external_id, user_principal_name, mail_nickname, given_name, family_name, department, deleted_at, created_at, updated_at
FROM users
ORDER BY lower(name), id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.Role,
			&i.APIKey,
			&i.APIKeyCreatedAt,
			&i.Source,
			&i.ExternalID,
			&i.UserPrincipalName,
			&i.MailNickname,
			&i.GivenName,
			&i.FamilyName,
			&i.Department,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserAPIKey = `-- name: SetUserAPIKey :one
UPDATE users
SET
    api_key = $1,
    api_key_created_at = now(),
    updated_at = now()
WHERE id = $2
  AND deleted_at IS NULL
  AND role IS NOT NULL
RETURNING id, email, name, password_hash, role, api_key, api_key_created_at, source, external_id, user_principal_name, mail_nickname, given_name, family_name, department, deleted_at, created_at, updated_at
`

type SetUserAPIKeyParams struct {
	APIKey *string `json:"api_key"`
	ID     int64   `json:"id"`
}

func (q *Queries) SetUserAPIKey(ctx context.Context, arg SetUserAPIKeyParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserAPIKey, arg.APIKey, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.APIKey,
		&i.APIKeyCreatedAt,
		&i.Source,
		&i.ExternalID,
		&i.UserPrincipalName,
		&i.MailNickname,
		&i.GivenName,
		&i.FamilyName,
		&i.Department,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteDirectoryUser = `-- name: SoftDeleteDirectoryUser :one
UPDATE users
SET
    deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND source <> 'local'
  AND deleted_at IS NULL
RETURNING id, email, name, password_hash, role, api_key, api_key_created_at, source, external_id, user_principal_name, mail_nickname, given_name, family_name, department, deleted_at, created_at, updated_at
`

type SoftDeleteDirectoryUserParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) SoftDeleteDirectoryUser(ctx context.Context, arg SoftDeleteDirectoryUserParams) (User, error) {
	row := q.db.QueryRow(ctx, softDeleteDirectoryUser, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.APIKey,
		&i.APIKeyCreatedAt,
		&i.Source,
		&i.ExternalID,
		&i.UserPrincipalName,
		&i.MailNickname,
		&i.GivenName,
		&i.FamilyName,
		&i.Department,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteDirectoryUsersNotIn = `-- name: SoftDeleteDirectoryUsersNotIn :exec
UPDATE users
SET
    deleted_at = now(),
    updated_at = now()
WHERE source = $1::directory_source
  AND deleted_at IS NULL
  AND external_id <> ALL($2::text[])
`

type SoftDeleteDirectoryUsersNotInParams struct {
	Source      DirectorySource `json:"source"`
	ExternalIds []string        `json:"external_ids"`
}

func (q *Queries) SoftDeleteDirectoryUsersNotIn(ctx context.Context, arg SoftDeleteDirectoryUsersNotInParams) error {
	_, err := q.db.Exec(ctx, softDeleteDirectoryUsersNotIn, arg.Source, arg.ExternalIds)
	return err
}

const updateAccountByID = `-- name: UpdateAccountByID :one
UPDATE users
SET
    name = CASE WHEN source = 'local' THEN $1 ELSE name END,
    password_hash = CASE
        WHEN source = 'local' THEN COALESCE($2, password_hash)
        ELSE password_hash
    END,
    updated_at = now()
WHERE id = $3
RETURNING id, email, name, password_hash, role, api_key, api_key_created_at, source, external_id, user_principal_name, mail_nickname, given_name, family_name, department, deleted_at, created_at, updated_at
`

type UpdateAccountByIDParams struct {
	Name         string  `json:"name"`
	PasswordHash *string `json:"password_hash"`
	ID           int64   `json:"id"`
}

func (q *Queries) UpdateAccountByID(ctx context.Context, arg UpdateAccountByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, updateAccountByID, arg.Name, arg.PasswordHash, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.APIKey,
		&i.APIKeyCreatedAt,
		&i.Source,
		&i.ExternalID,
		&i.UserPrincipalName,
		&i.MailNickname,
		&i.GivenName,
		&i.FamilyName,
		&i.Department,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    name = CASE WHEN source = 'local' THEN $1 ELSE name END,
    role = $2::user_role,
    password_hash = CASE
        WHEN source = 'local' THEN COALESCE($3, password_hash)
        ELSE password_hash
    END,
    updated_at = now()
WHERE id = $4
RETURNING id, email, name, password_hash, role, api_key, api_key_created_at, source, external_id, user_principal_name, mail_nickname, given_name, family_name, department, deleted_at, created_at, updated_at
`

type UpdateUserParams struct {
	Name         string    `json:"name"`
	Role         *UserRole `json:"role"`
	PasswordHash *string   `json:"password_hash"`
	ID           int64     `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Role,
		arg.PasswordHash,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.APIKey,
		&i.APIKeyCreatedAt,
		&i.Source,
		&i.ExternalID,
		&i.UserPrincipalName,
		&i.MailNickname,
		&i.GivenName,
		&i.FamilyName,
		&i.Department,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDirectoryUser = `-- name: UpsertDirectoryUser :one
INSERT INTO users (
    email,
    name,
    source,
    external_id,
    user_principal_name,
    mail_nickname,
    given_name,
    family_name,
    department,
    deleted_at
)
VALUES (
    COALESCE($1::text, $2::text),
    $3::text,
    $4::directory_source,
    $5::text,
    $2::text,
    $6::text,
    $7::text,
    $8::text,
    $9::text,
    CASE WHEN $10::boolean THEN NULL ELSE now() END
)
ON CONFLICT (source, external_id) DO UPDATE SET
    email = EXCLUDED.email,
    name = EXCLUDED.name,
    user_principal_name = EXCLUDED.user_principal_name,
    mail_nickname = EXCLUDED.mail_nickname,
    given_name = EXCLUDED.given_name,
    family_name = EXCLUDED.family_name,
    department = EXCLUDED.department,
    deleted_at = EXCLUDED.deleted_at,
    updated_at = now()
RETURNING id, email, name, password_hash, role, api_key, api_key_created_at, source, external_id, user_principal_name, mail_nickname, given_name, family_name, department, deleted_at, created_at, updated_at
`

type UpsertDirectoryUserParams struct {
	Mail              *string         `json:"mail"`
	UserPrincipalName string          `json:"user_principal_name"`
	DisplayName       string          `json:"display_name"`
	Source            DirectorySource `json:"source"`
	ExternalID        string          `json:"external_id"`
	MailNickname      *string         `json:"mail_nickname"`
	GivenName         *string         `json:"given_name"`
	FamilyName        *string         `json:"family_name"`
	Department        *string         `json:"department"`
	Enabled           bool            `json:"enabled"`
}

func (q *Queries) UpsertDirectoryUser(ctx context.Context, arg UpsertDirectoryUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertDirectoryUser,
		arg.Mail,
		arg.UserPrincipalName,
		arg.DisplayName,
		arg.Source,
		arg.ExternalID,
		arg.MailNickname,
		arg.GivenName,
		arg.FamilyName,
		arg.Department,
		arg.Enabled,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.APIKey,
		&i.APIKeyCreatedAt,
		&i.Source,
		&i.ExternalID,
		&i.UserPrincipalName,
		&i.MailNickname,
		&i.GivenName,
		&i.FamilyName,
		&i.Department,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS (
    SELECT 1
    FROM users
)
`

func (q *Queries) UserExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, userExists)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
