/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSoftwareRouteImport } from './routes/_authenticated/software'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedLabelsRouteImport } from './routes/_authenticated/labels'
import { Route as AuthenticatedHostsRouteImport } from './routes/_authenticated/hosts'
import { Route as AuthenticatedSoftwareIndexRouteImport } from './routes/_authenticated/software.index'
import { Route as AuthenticatedHostsIndexRouteImport } from './routes/_authenticated/hosts.index'
import { Route as AuthenticatedHostsHostIdRouteImport } from './routes/_authenticated/hosts.$hostId'
import { Route as AuthenticatedSoftwareTitlesSoftwareIdRouteImport } from './routes/_authenticated/software.titles.$softwareId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSoftwareRoute = AuthenticatedSoftwareRouteImport.update({
  id: '/software',
  path: '/software',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLabelsRoute = AuthenticatedLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHostsRoute = AuthenticatedHostsRouteImport.update({
  id: '/hosts',
  path: '/hosts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSoftwareIndexRoute =
  AuthenticatedSoftwareIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSoftwareRoute,
  } as any)
const AuthenticatedHostsIndexRoute = AuthenticatedHostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedHostsRoute,
} as any)
const AuthenticatedHostsHostIdRoute =
  AuthenticatedHostsHostIdRouteImport.update({
    id: '/$hostId',
    path: '/$hostId',
    getParentRoute: () => AuthenticatedHostsRoute,
  } as any)
const AuthenticatedSoftwareTitlesSoftwareIdRoute =
  AuthenticatedSoftwareTitlesSoftwareIdRouteImport.update({
    id: '/titles/$softwareId',
    path: '/titles/$softwareId',
    getParentRoute: () => AuthenticatedSoftwareRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/hosts': typeof AuthenticatedHostsRouteWithChildren
  '/labels': typeof AuthenticatedLabelsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/software': typeof AuthenticatedSoftwareRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/hosts/$hostId': typeof AuthenticatedHostsHostIdRoute
  '/hosts/': typeof AuthenticatedHostsIndexRoute
  '/software/': typeof AuthenticatedSoftwareIndexRoute
  '/software/titles/$softwareId': typeof AuthenticatedSoftwareTitlesSoftwareIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/labels': typeof AuthenticatedLabelsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/hosts/$hostId': typeof AuthenticatedHostsHostIdRoute
  '/hosts': typeof AuthenticatedHostsIndexRoute
  '/software': typeof AuthenticatedSoftwareIndexRoute
  '/software/titles/$softwareId': typeof AuthenticatedSoftwareTitlesSoftwareIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_authenticated/hosts': typeof AuthenticatedHostsRouteWithChildren
  '/_authenticated/labels': typeof AuthenticatedLabelsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/software': typeof AuthenticatedSoftwareRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/hosts/$hostId': typeof AuthenticatedHostsHostIdRoute
  '/_authenticated/hosts/': typeof AuthenticatedHostsIndexRoute
  '/_authenticated/software/': typeof AuthenticatedSoftwareIndexRoute
  '/_authenticated/software/titles/$softwareId': typeof AuthenticatedSoftwareTitlesSoftwareIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/hosts'
    | '/labels'
    | '/settings'
    | '/software'
    | '/users'
    | '/hosts/$hostId'
    | '/hosts/'
    | '/software/'
    | '/software/titles/$softwareId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/labels'
    | '/settings'
    | '/users'
    | '/hosts/$hostId'
    | '/hosts'
    | '/software'
    | '/software/titles/$softwareId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/setup'
    | '/_authenticated/hosts'
    | '/_authenticated/labels'
    | '/_authenticated/settings'
    | '/_authenticated/software'
    | '/_authenticated/users'
    | '/_authenticated/hosts/$hostId'
    | '/_authenticated/hosts/'
    | '/_authenticated/software/'
    | '/_authenticated/software/titles/$softwareId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/software': {
      id: '/_authenticated/software'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof AuthenticatedSoftwareRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/labels': {
      id: '/_authenticated/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof AuthenticatedLabelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hosts': {
      id: '/_authenticated/hosts'
      path: '/hosts'
      fullPath: '/hosts'
      preLoaderRoute: typeof AuthenticatedHostsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/software/': {
      id: '/_authenticated/software/'
      path: '/'
      fullPath: '/software/'
      preLoaderRoute: typeof AuthenticatedSoftwareIndexRouteImport
      parentRoute: typeof AuthenticatedSoftwareRoute
    }
    '/_authenticated/hosts/': {
      id: '/_authenticated/hosts/'
      path: '/'
      fullPath: '/hosts/'
      preLoaderRoute: typeof AuthenticatedHostsIndexRouteImport
      parentRoute: typeof AuthenticatedHostsRoute
    }
    '/_authenticated/hosts/$hostId': {
      id: '/_authenticated/hosts/$hostId'
      path: '/$hostId'
      fullPath: '/hosts/$hostId'
      preLoaderRoute: typeof AuthenticatedHostsHostIdRouteImport
      parentRoute: typeof AuthenticatedHostsRoute
    }
    '/_authenticated/software/titles/$softwareId': {
      id: '/_authenticated/software/titles/$softwareId'
      path: '/titles/$softwareId'
      fullPath: '/software/titles/$softwareId'
      preLoaderRoute: typeof AuthenticatedSoftwareTitlesSoftwareIdRouteImport
      parentRoute: typeof AuthenticatedSoftwareRoute
    }
  }
}

interface AuthenticatedHostsRouteChildren {
  AuthenticatedHostsHostIdRoute: typeof AuthenticatedHostsHostIdRoute
  AuthenticatedHostsIndexRoute: typeof AuthenticatedHostsIndexRoute
}

const AuthenticatedHostsRouteChildren: AuthenticatedHostsRouteChildren = {
  AuthenticatedHostsHostIdRoute: AuthenticatedHostsHostIdRoute,
  AuthenticatedHostsIndexRoute: AuthenticatedHostsIndexRoute,
}

const AuthenticatedHostsRouteWithChildren =
  AuthenticatedHostsRoute._addFileChildren(AuthenticatedHostsRouteChildren)

interface AuthenticatedSoftwareRouteChildren {
  AuthenticatedSoftwareIndexRoute: typeof AuthenticatedSoftwareIndexRoute
  AuthenticatedSoftwareTitlesSoftwareIdRoute: typeof AuthenticatedSoftwareTitlesSoftwareIdRoute
}

const AuthenticatedSoftwareRouteChildren: AuthenticatedSoftwareRouteChildren = {
  AuthenticatedSoftwareIndexRoute: AuthenticatedSoftwareIndexRoute,
  AuthenticatedSoftwareTitlesSoftwareIdRoute:
    AuthenticatedSoftwareTitlesSoftwareIdRoute,
}

const AuthenticatedSoftwareRouteWithChildren =
  AuthenticatedSoftwareRoute._addFileChildren(
    AuthenticatedSoftwareRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedHostsRoute: typeof AuthenticatedHostsRouteWithChildren
  AuthenticatedLabelsRoute: typeof AuthenticatedLabelsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSoftwareRoute: typeof AuthenticatedSoftwareRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHostsRoute: AuthenticatedHostsRouteWithChildren,
  AuthenticatedLabelsRoute: AuthenticatedLabelsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSoftwareRoute: AuthenticatedSoftwareRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
