/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSoftwareRouteImport } from './routes/_authenticated/software'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSecretsRouteImport } from './routes/_authenticated/secrets'
import { Route as AuthenticatedSantaRouteImport } from './routes/_authenticated/santa'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedLabelsRouteImport } from './routes/_authenticated/labels'
import { Route as AuthenticatedHostsRouteImport } from './routes/_authenticated/hosts'
import { Route as AuthenticatedChecksRouteImport } from './routes/_authenticated/checks'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users.index'
import { Route as AuthenticatedSoftwareIndexRouteImport } from './routes/_authenticated/software.index'
import { Route as AuthenticatedSantaIndexRouteImport } from './routes/_authenticated/santa.index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports.index'
import { Route as AuthenticatedLabelsIndexRouteImport } from './routes/_authenticated/labels.index'
import { Route as AuthenticatedHostsIndexRouteImport } from './routes/_authenticated/hosts.index'
import { Route as AuthenticatedChecksIndexRouteImport } from './routes/_authenticated/checks.index'
import { Route as AuthenticatedSantaRulesRouteImport } from './routes/_authenticated/santa.rules'
import { Route as AuthenticatedSantaEventsRouteImport } from './routes/_authenticated/santa.events'
import { Route as AuthenticatedSantaConfigurationsRouteImport } from './routes/_authenticated/santa.configurations'
import { Route as AuthenticatedReportsNewRouteImport } from './routes/_authenticated/reports.new'
import { Route as AuthenticatedReportsReportIdRouteImport } from './routes/_authenticated/reports.$reportId'
import { Route as AuthenticatedLabelsNewRouteImport } from './routes/_authenticated/labels.new'
import { Route as AuthenticatedHostsHostIdRouteImport } from './routes/_authenticated/hosts.$hostId'
import { Route as AuthenticatedChecksNewRouteImport } from './routes/_authenticated/checks.new'
import { Route as AuthenticatedChecksCheckIdRouteImport } from './routes/_authenticated/checks.$checkId'
import { Route as AuthenticatedSantaRulesIndexRouteImport } from './routes/_authenticated/santa.rules.index'
import { Route as AuthenticatedSantaConfigurationsIndexRouteImport } from './routes/_authenticated/santa.configurations.index'
import { Route as AuthenticatedReportsReportIdIndexRouteImport } from './routes/_authenticated/reports.$reportId.index'
import { Route as AuthenticatedChecksCheckIdIndexRouteImport } from './routes/_authenticated/checks.$checkId.index'
import { Route as AuthenticatedUsersUserIdEditRouteImport } from './routes/_authenticated/users.$userId.edit'
import { Route as AuthenticatedSoftwareTitlesSoftwareIdRouteImport } from './routes/_authenticated/software.titles.$softwareId'
import { Route as AuthenticatedSantaRulesNewRouteImport } from './routes/_authenticated/santa.rules.new'
import { Route as AuthenticatedSantaConfigurationsNewRouteImport } from './routes/_authenticated/santa.configurations.new'
import { Route as AuthenticatedReportsReportIdLiveRouteImport } from './routes/_authenticated/reports.$reportId.live'
import { Route as AuthenticatedReportsReportIdEditRouteImport } from './routes/_authenticated/reports.$reportId.edit'
import { Route as AuthenticatedLabelsLabelIdEditRouteImport } from './routes/_authenticated/labels.$labelId.edit'
import { Route as AuthenticatedChecksCheckIdLiveRouteImport } from './routes/_authenticated/checks.$checkId.live'
import { Route as AuthenticatedChecksCheckIdEditRouteImport } from './routes/_authenticated/checks.$checkId.edit'
import { Route as AuthenticatedSantaRulesRuleIdEditRouteImport } from './routes/_authenticated/santa.rules.$ruleId.edit'
import { Route as AuthenticatedSantaConfigurationsConfigurationIdEditRouteImport } from './routes/_authenticated/santa.configurations.$configurationId.edit'
import { Route as AuthenticatedHostsHostIdReportsReportIdRouteImport } from './routes/_authenticated/hosts.$hostId.reports.$reportId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSoftwareRoute = AuthenticatedSoftwareRouteImport.update({
  id: '/software',
  path: '/software',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecretsRoute = AuthenticatedSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSantaRoute = AuthenticatedSantaRouteImport.update({
  id: '/santa',
  path: '/santa',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLabelsRoute = AuthenticatedLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHostsRoute = AuthenticatedHostsRouteImport.update({
  id: '/hosts',
  path: '/hosts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChecksRoute = AuthenticatedChecksRouteImport.update({
  id: '/checks',
  path: '/checks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedUsersRoute,
} as any)
const AuthenticatedSoftwareIndexRoute =
  AuthenticatedSoftwareIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSoftwareRoute,
  } as any)
const AuthenticatedSantaIndexRoute = AuthenticatedSantaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSantaRoute,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedLabelsIndexRoute =
  AuthenticatedLabelsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLabelsRoute,
  } as any)
const AuthenticatedHostsIndexRoute = AuthenticatedHostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedHostsRoute,
} as any)
const AuthenticatedChecksIndexRoute =
  AuthenticatedChecksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedChecksRoute,
  } as any)
const AuthenticatedSantaRulesRoute = AuthenticatedSantaRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AuthenticatedSantaRoute,
} as any)
const AuthenticatedSantaEventsRoute =
  AuthenticatedSantaEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedSantaRoute,
  } as any)
const AuthenticatedSantaConfigurationsRoute =
  AuthenticatedSantaConfigurationsRouteImport.update({
    id: '/configurations',
    path: '/configurations',
    getParentRoute: () => AuthenticatedSantaRoute,
  } as any)
const AuthenticatedReportsNewRoute = AuthenticatedReportsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedReportsRoute,
} as any)
const AuthenticatedReportsReportIdRoute =
  AuthenticatedReportsReportIdRouteImport.update({
    id: '/$reportId',
    path: '/$reportId',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedLabelsNewRoute = AuthenticatedLabelsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedLabelsRoute,
} as any)
const AuthenticatedHostsHostIdRoute =
  AuthenticatedHostsHostIdRouteImport.update({
    id: '/$hostId',
    path: '/$hostId',
    getParentRoute: () => AuthenticatedHostsRoute,
  } as any)
const AuthenticatedChecksNewRoute = AuthenticatedChecksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedChecksRoute,
} as any)
const AuthenticatedChecksCheckIdRoute =
  AuthenticatedChecksCheckIdRouteImport.update({
    id: '/$checkId',
    path: '/$checkId',
    getParentRoute: () => AuthenticatedChecksRoute,
  } as any)
const AuthenticatedSantaRulesIndexRoute =
  AuthenticatedSantaRulesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSantaRulesRoute,
  } as any)
const AuthenticatedSantaConfigurationsIndexRoute =
  AuthenticatedSantaConfigurationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSantaConfigurationsRoute,
  } as any)
const AuthenticatedReportsReportIdIndexRoute =
  AuthenticatedReportsReportIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsReportIdRoute,
  } as any)
const AuthenticatedChecksCheckIdIndexRoute =
  AuthenticatedChecksCheckIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedChecksCheckIdRoute,
  } as any)
const AuthenticatedUsersUserIdEditRoute =
  AuthenticatedUsersUserIdEditRouteImport.update({
    id: '/$userId/edit',
    path: '/$userId/edit',
    getParentRoute: () => AuthenticatedUsersRoute,
  } as any)
const AuthenticatedSoftwareTitlesSoftwareIdRoute =
  AuthenticatedSoftwareTitlesSoftwareIdRouteImport.update({
    id: '/titles/$softwareId',
    path: '/titles/$softwareId',
    getParentRoute: () => AuthenticatedSoftwareRoute,
  } as any)
const AuthenticatedSantaRulesNewRoute =
  AuthenticatedSantaRulesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSantaRulesRoute,
  } as any)
const AuthenticatedSantaConfigurationsNewRoute =
  AuthenticatedSantaConfigurationsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSantaConfigurationsRoute,
  } as any)
const AuthenticatedReportsReportIdLiveRoute =
  AuthenticatedReportsReportIdLiveRouteImport.update({
    id: '/live',
    path: '/live',
    getParentRoute: () => AuthenticatedReportsReportIdRoute,
  } as any)
const AuthenticatedReportsReportIdEditRoute =
  AuthenticatedReportsReportIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedReportsReportIdRoute,
  } as any)
const AuthenticatedLabelsLabelIdEditRoute =
  AuthenticatedLabelsLabelIdEditRouteImport.update({
    id: '/$labelId/edit',
    path: '/$labelId/edit',
    getParentRoute: () => AuthenticatedLabelsRoute,
  } as any)
const AuthenticatedChecksCheckIdLiveRoute =
  AuthenticatedChecksCheckIdLiveRouteImport.update({
    id: '/live',
    path: '/live',
    getParentRoute: () => AuthenticatedChecksCheckIdRoute,
  } as any)
const AuthenticatedChecksCheckIdEditRoute =
  AuthenticatedChecksCheckIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedChecksCheckIdRoute,
  } as any)
const AuthenticatedSantaRulesRuleIdEditRoute =
  AuthenticatedSantaRulesRuleIdEditRouteImport.update({
    id: '/$ruleId/edit',
    path: '/$ruleId/edit',
    getParentRoute: () => AuthenticatedSantaRulesRoute,
  } as any)
const AuthenticatedSantaConfigurationsConfigurationIdEditRoute =
  AuthenticatedSantaConfigurationsConfigurationIdEditRouteImport.update({
    id: '/$configurationId/edit',
    path: '/$configurationId/edit',
    getParentRoute: () => AuthenticatedSantaConfigurationsRoute,
  } as any)
const AuthenticatedHostsHostIdReportsReportIdRoute =
  AuthenticatedHostsHostIdReportsReportIdRouteImport.update({
    id: '/reports/$reportId',
    path: '/reports/$reportId',
    getParentRoute: () => AuthenticatedHostsHostIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/account': typeof AuthenticatedAccountRoute
  '/checks': typeof AuthenticatedChecksRouteWithChildren
  '/hosts': typeof AuthenticatedHostsRouteWithChildren
  '/labels': typeof AuthenticatedLabelsRouteWithChildren
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/santa': typeof AuthenticatedSantaRouteWithChildren
  '/secrets': typeof AuthenticatedSecretsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/software': typeof AuthenticatedSoftwareRouteWithChildren
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/checks/$checkId': typeof AuthenticatedChecksCheckIdRouteWithChildren
  '/checks/new': typeof AuthenticatedChecksNewRoute
  '/hosts/$hostId': typeof AuthenticatedHostsHostIdRouteWithChildren
  '/labels/new': typeof AuthenticatedLabelsNewRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdRouteWithChildren
  '/reports/new': typeof AuthenticatedReportsNewRoute
  '/santa/configurations': typeof AuthenticatedSantaConfigurationsRouteWithChildren
  '/santa/events': typeof AuthenticatedSantaEventsRoute
  '/santa/rules': typeof AuthenticatedSantaRulesRouteWithChildren
  '/checks/': typeof AuthenticatedChecksIndexRoute
  '/hosts/': typeof AuthenticatedHostsIndexRoute
  '/labels/': typeof AuthenticatedLabelsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/santa/': typeof AuthenticatedSantaIndexRoute
  '/software/': typeof AuthenticatedSoftwareIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/checks/$checkId/edit': typeof AuthenticatedChecksCheckIdEditRoute
  '/checks/$checkId/live': typeof AuthenticatedChecksCheckIdLiveRoute
  '/labels/$labelId/edit': typeof AuthenticatedLabelsLabelIdEditRoute
  '/reports/$reportId/edit': typeof AuthenticatedReportsReportIdEditRoute
  '/reports/$reportId/live': typeof AuthenticatedReportsReportIdLiveRoute
  '/santa/configurations/new': typeof AuthenticatedSantaConfigurationsNewRoute
  '/santa/rules/new': typeof AuthenticatedSantaRulesNewRoute
  '/software/titles/$softwareId': typeof AuthenticatedSoftwareTitlesSoftwareIdRoute
  '/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
  '/checks/$checkId/': typeof AuthenticatedChecksCheckIdIndexRoute
  '/reports/$reportId/': typeof AuthenticatedReportsReportIdIndexRoute
  '/santa/configurations/': typeof AuthenticatedSantaConfigurationsIndexRoute
  '/santa/rules/': typeof AuthenticatedSantaRulesIndexRoute
  '/hosts/$hostId/reports/$reportId': typeof AuthenticatedHostsHostIdReportsReportIdRoute
  '/santa/configurations/$configurationId/edit': typeof AuthenticatedSantaConfigurationsConfigurationIdEditRoute
  '/santa/rules/$ruleId/edit': typeof AuthenticatedSantaRulesRuleIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/account': typeof AuthenticatedAccountRoute
  '/secrets': typeof AuthenticatedSecretsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/checks/new': typeof AuthenticatedChecksNewRoute
  '/hosts/$hostId': typeof AuthenticatedHostsHostIdRouteWithChildren
  '/labels/new': typeof AuthenticatedLabelsNewRoute
  '/reports/new': typeof AuthenticatedReportsNewRoute
  '/santa/events': typeof AuthenticatedSantaEventsRoute
  '/checks': typeof AuthenticatedChecksIndexRoute
  '/hosts': typeof AuthenticatedHostsIndexRoute
  '/labels': typeof AuthenticatedLabelsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/santa': typeof AuthenticatedSantaIndexRoute
  '/software': typeof AuthenticatedSoftwareIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/checks/$checkId/edit': typeof AuthenticatedChecksCheckIdEditRoute
  '/checks/$checkId/live': typeof AuthenticatedChecksCheckIdLiveRoute
  '/labels/$labelId/edit': typeof AuthenticatedLabelsLabelIdEditRoute
  '/reports/$reportId/edit': typeof AuthenticatedReportsReportIdEditRoute
  '/reports/$reportId/live': typeof AuthenticatedReportsReportIdLiveRoute
  '/santa/configurations/new': typeof AuthenticatedSantaConfigurationsNewRoute
  '/santa/rules/new': typeof AuthenticatedSantaRulesNewRoute
  '/software/titles/$softwareId': typeof AuthenticatedSoftwareTitlesSoftwareIdRoute
  '/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
  '/checks/$checkId': typeof AuthenticatedChecksCheckIdIndexRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdIndexRoute
  '/santa/configurations': typeof AuthenticatedSantaConfigurationsIndexRoute
  '/santa/rules': typeof AuthenticatedSantaRulesIndexRoute
  '/hosts/$hostId/reports/$reportId': typeof AuthenticatedHostsHostIdReportsReportIdRoute
  '/santa/configurations/$configurationId/edit': typeof AuthenticatedSantaConfigurationsConfigurationIdEditRoute
  '/santa/rules/$ruleId/edit': typeof AuthenticatedSantaRulesRuleIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/checks': typeof AuthenticatedChecksRouteWithChildren
  '/_authenticated/hosts': typeof AuthenticatedHostsRouteWithChildren
  '/_authenticated/labels': typeof AuthenticatedLabelsRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/santa': typeof AuthenticatedSantaRouteWithChildren
  '/_authenticated/secrets': typeof AuthenticatedSecretsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/software': typeof AuthenticatedSoftwareRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRouteWithChildren
  '/_authenticated/checks/$checkId': typeof AuthenticatedChecksCheckIdRouteWithChildren
  '/_authenticated/checks/new': typeof AuthenticatedChecksNewRoute
  '/_authenticated/hosts/$hostId': typeof AuthenticatedHostsHostIdRouteWithChildren
  '/_authenticated/labels/new': typeof AuthenticatedLabelsNewRoute
  '/_authenticated/reports/$reportId': typeof AuthenticatedReportsReportIdRouteWithChildren
  '/_authenticated/reports/new': typeof AuthenticatedReportsNewRoute
  '/_authenticated/santa/configurations': typeof AuthenticatedSantaConfigurationsRouteWithChildren
  '/_authenticated/santa/events': typeof AuthenticatedSantaEventsRoute
  '/_authenticated/santa/rules': typeof AuthenticatedSantaRulesRouteWithChildren
  '/_authenticated/checks/': typeof AuthenticatedChecksIndexRoute
  '/_authenticated/hosts/': typeof AuthenticatedHostsIndexRoute
  '/_authenticated/labels/': typeof AuthenticatedLabelsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/santa/': typeof AuthenticatedSantaIndexRoute
  '/_authenticated/software/': typeof AuthenticatedSoftwareIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/checks/$checkId/edit': typeof AuthenticatedChecksCheckIdEditRoute
  '/_authenticated/checks/$checkId/live': typeof AuthenticatedChecksCheckIdLiveRoute
  '/_authenticated/labels/$labelId/edit': typeof AuthenticatedLabelsLabelIdEditRoute
  '/_authenticated/reports/$reportId/edit': typeof AuthenticatedReportsReportIdEditRoute
  '/_authenticated/reports/$reportId/live': typeof AuthenticatedReportsReportIdLiveRoute
  '/_authenticated/santa/configurations/new': typeof AuthenticatedSantaConfigurationsNewRoute
  '/_authenticated/santa/rules/new': typeof AuthenticatedSantaRulesNewRoute
  '/_authenticated/software/titles/$softwareId': typeof AuthenticatedSoftwareTitlesSoftwareIdRoute
  '/_authenticated/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
  '/_authenticated/checks/$checkId/': typeof AuthenticatedChecksCheckIdIndexRoute
  '/_authenticated/reports/$reportId/': typeof AuthenticatedReportsReportIdIndexRoute
  '/_authenticated/santa/configurations/': typeof AuthenticatedSantaConfigurationsIndexRoute
  '/_authenticated/santa/rules/': typeof AuthenticatedSantaRulesIndexRoute
  '/_authenticated/hosts/$hostId/reports/$reportId': typeof AuthenticatedHostsHostIdReportsReportIdRoute
  '/_authenticated/santa/configurations/$configurationId/edit': typeof AuthenticatedSantaConfigurationsConfigurationIdEditRoute
  '/_authenticated/santa/rules/$ruleId/edit': typeof AuthenticatedSantaRulesRuleIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/account'
    | '/checks'
    | '/hosts'
    | '/labels'
    | '/reports'
    | '/santa'
    | '/secrets'
    | '/settings'
    | '/software'
    | '/users'
    | '/checks/$checkId'
    | '/checks/new'
    | '/hosts/$hostId'
    | '/labels/new'
    | '/reports/$reportId'
    | '/reports/new'
    | '/santa/configurations'
    | '/santa/events'
    | '/santa/rules'
    | '/checks/'
    | '/hosts/'
    | '/labels/'
    | '/reports/'
    | '/santa/'
    | '/software/'
    | '/users/'
    | '/checks/$checkId/edit'
    | '/checks/$checkId/live'
    | '/labels/$labelId/edit'
    | '/reports/$reportId/edit'
    | '/reports/$reportId/live'
    | '/santa/configurations/new'
    | '/santa/rules/new'
    | '/software/titles/$softwareId'
    | '/users/$userId/edit'
    | '/checks/$checkId/'
    | '/reports/$reportId/'
    | '/santa/configurations/'
    | '/santa/rules/'
    | '/hosts/$hostId/reports/$reportId'
    | '/santa/configurations/$configurationId/edit'
    | '/santa/rules/$ruleId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/account'
    | '/secrets'
    | '/settings'
    | '/checks/new'
    | '/hosts/$hostId'
    | '/labels/new'
    | '/reports/new'
    | '/santa/events'
    | '/checks'
    | '/hosts'
    | '/labels'
    | '/reports'
    | '/santa'
    | '/software'
    | '/users'
    | '/checks/$checkId/edit'
    | '/checks/$checkId/live'
    | '/labels/$labelId/edit'
    | '/reports/$reportId/edit'
    | '/reports/$reportId/live'
    | '/santa/configurations/new'
    | '/santa/rules/new'
    | '/software/titles/$softwareId'
    | '/users/$userId/edit'
    | '/checks/$checkId'
    | '/reports/$reportId'
    | '/santa/configurations'
    | '/santa/rules'
    | '/hosts/$hostId/reports/$reportId'
    | '/santa/configurations/$configurationId/edit'
    | '/santa/rules/$ruleId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/setup'
    | '/_authenticated/account'
    | '/_authenticated/checks'
    | '/_authenticated/hosts'
    | '/_authenticated/labels'
    | '/_authenticated/reports'
    | '/_authenticated/santa'
    | '/_authenticated/secrets'
    | '/_authenticated/settings'
    | '/_authenticated/software'
    | '/_authenticated/users'
    | '/_authenticated/checks/$checkId'
    | '/_authenticated/checks/new'
    | '/_authenticated/hosts/$hostId'
    | '/_authenticated/labels/new'
    | '/_authenticated/reports/$reportId'
    | '/_authenticated/reports/new'
    | '/_authenticated/santa/configurations'
    | '/_authenticated/santa/events'
    | '/_authenticated/santa/rules'
    | '/_authenticated/checks/'
    | '/_authenticated/hosts/'
    | '/_authenticated/labels/'
    | '/_authenticated/reports/'
    | '/_authenticated/santa/'
    | '/_authenticated/software/'
    | '/_authenticated/users/'
    | '/_authenticated/checks/$checkId/edit'
    | '/_authenticated/checks/$checkId/live'
    | '/_authenticated/labels/$labelId/edit'
    | '/_authenticated/reports/$reportId/edit'
    | '/_authenticated/reports/$reportId/live'
    | '/_authenticated/santa/configurations/new'
    | '/_authenticated/santa/rules/new'
    | '/_authenticated/software/titles/$softwareId'
    | '/_authenticated/users/$userId/edit'
    | '/_authenticated/checks/$checkId/'
    | '/_authenticated/reports/$reportId/'
    | '/_authenticated/santa/configurations/'
    | '/_authenticated/santa/rules/'
    | '/_authenticated/hosts/$hostId/reports/$reportId'
    | '/_authenticated/santa/configurations/$configurationId/edit'
    | '/_authenticated/santa/rules/$ruleId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/software': {
      id: '/_authenticated/software'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof AuthenticatedSoftwareRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/secrets': {
      id: '/_authenticated/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof AuthenticatedSecretsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/santa': {
      id: '/_authenticated/santa'
      path: '/santa'
      fullPath: '/santa'
      preLoaderRoute: typeof AuthenticatedSantaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/labels': {
      id: '/_authenticated/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof AuthenticatedLabelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hosts': {
      id: '/_authenticated/hosts'
      path: '/hosts'
      fullPath: '/hosts'
      preLoaderRoute: typeof AuthenticatedHostsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checks': {
      id: '/_authenticated/checks'
      path: '/checks'
      fullPath: '/checks'
      preLoaderRoute: typeof AuthenticatedChecksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/software/': {
      id: '/_authenticated/software/'
      path: '/'
      fullPath: '/software/'
      preLoaderRoute: typeof AuthenticatedSoftwareIndexRouteImport
      parentRoute: typeof AuthenticatedSoftwareRoute
    }
    '/_authenticated/santa/': {
      id: '/_authenticated/santa/'
      path: '/'
      fullPath: '/santa/'
      preLoaderRoute: typeof AuthenticatedSantaIndexRouteImport
      parentRoute: typeof AuthenticatedSantaRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/labels/': {
      id: '/_authenticated/labels/'
      path: '/'
      fullPath: '/labels/'
      preLoaderRoute: typeof AuthenticatedLabelsIndexRouteImport
      parentRoute: typeof AuthenticatedLabelsRoute
    }
    '/_authenticated/hosts/': {
      id: '/_authenticated/hosts/'
      path: '/'
      fullPath: '/hosts/'
      preLoaderRoute: typeof AuthenticatedHostsIndexRouteImport
      parentRoute: typeof AuthenticatedHostsRoute
    }
    '/_authenticated/checks/': {
      id: '/_authenticated/checks/'
      path: '/'
      fullPath: '/checks/'
      preLoaderRoute: typeof AuthenticatedChecksIndexRouteImport
      parentRoute: typeof AuthenticatedChecksRoute
    }
    '/_authenticated/santa/rules': {
      id: '/_authenticated/santa/rules'
      path: '/rules'
      fullPath: '/santa/rules'
      preLoaderRoute: typeof AuthenticatedSantaRulesRouteImport
      parentRoute: typeof AuthenticatedSantaRoute
    }
    '/_authenticated/santa/events': {
      id: '/_authenticated/santa/events'
      path: '/events'
      fullPath: '/santa/events'
      preLoaderRoute: typeof AuthenticatedSantaEventsRouteImport
      parentRoute: typeof AuthenticatedSantaRoute
    }
    '/_authenticated/santa/configurations': {
      id: '/_authenticated/santa/configurations'
      path: '/configurations'
      fullPath: '/santa/configurations'
      preLoaderRoute: typeof AuthenticatedSantaConfigurationsRouteImport
      parentRoute: typeof AuthenticatedSantaRoute
    }
    '/_authenticated/reports/new': {
      id: '/_authenticated/reports/new'
      path: '/new'
      fullPath: '/reports/new'
      preLoaderRoute: typeof AuthenticatedReportsNewRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/$reportId': {
      id: '/_authenticated/reports/$reportId'
      path: '/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof AuthenticatedReportsReportIdRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/labels/new': {
      id: '/_authenticated/labels/new'
      path: '/new'
      fullPath: '/labels/new'
      preLoaderRoute: typeof AuthenticatedLabelsNewRouteImport
      parentRoute: typeof AuthenticatedLabelsRoute
    }
    '/_authenticated/hosts/$hostId': {
      id: '/_authenticated/hosts/$hostId'
      path: '/$hostId'
      fullPath: '/hosts/$hostId'
      preLoaderRoute: typeof AuthenticatedHostsHostIdRouteImport
      parentRoute: typeof AuthenticatedHostsRoute
    }
    '/_authenticated/checks/new': {
      id: '/_authenticated/checks/new'
      path: '/new'
      fullPath: '/checks/new'
      preLoaderRoute: typeof AuthenticatedChecksNewRouteImport
      parentRoute: typeof AuthenticatedChecksRoute
    }
    '/_authenticated/checks/$checkId': {
      id: '/_authenticated/checks/$checkId'
      path: '/$checkId'
      fullPath: '/checks/$checkId'
      preLoaderRoute: typeof AuthenticatedChecksCheckIdRouteImport
      parentRoute: typeof AuthenticatedChecksRoute
    }
    '/_authenticated/santa/rules/': {
      id: '/_authenticated/santa/rules/'
      path: '/'
      fullPath: '/santa/rules/'
      preLoaderRoute: typeof AuthenticatedSantaRulesIndexRouteImport
      parentRoute: typeof AuthenticatedSantaRulesRoute
    }
    '/_authenticated/santa/configurations/': {
      id: '/_authenticated/santa/configurations/'
      path: '/'
      fullPath: '/santa/configurations/'
      preLoaderRoute: typeof AuthenticatedSantaConfigurationsIndexRouteImport
      parentRoute: typeof AuthenticatedSantaConfigurationsRoute
    }
    '/_authenticated/reports/$reportId/': {
      id: '/_authenticated/reports/$reportId/'
      path: '/'
      fullPath: '/reports/$reportId/'
      preLoaderRoute: typeof AuthenticatedReportsReportIdIndexRouteImport
      parentRoute: typeof AuthenticatedReportsReportIdRoute
    }
    '/_authenticated/checks/$checkId/': {
      id: '/_authenticated/checks/$checkId/'
      path: '/'
      fullPath: '/checks/$checkId/'
      preLoaderRoute: typeof AuthenticatedChecksCheckIdIndexRouteImport
      parentRoute: typeof AuthenticatedChecksCheckIdRoute
    }
    '/_authenticated/users/$userId/edit': {
      id: '/_authenticated/users/$userId/edit'
      path: '/$userId/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof AuthenticatedUsersUserIdEditRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/software/titles/$softwareId': {
      id: '/_authenticated/software/titles/$softwareId'
      path: '/titles/$softwareId'
      fullPath: '/software/titles/$softwareId'
      preLoaderRoute: typeof AuthenticatedSoftwareTitlesSoftwareIdRouteImport
      parentRoute: typeof AuthenticatedSoftwareRoute
    }
    '/_authenticated/santa/rules/new': {
      id: '/_authenticated/santa/rules/new'
      path: '/new'
      fullPath: '/santa/rules/new'
      preLoaderRoute: typeof AuthenticatedSantaRulesNewRouteImport
      parentRoute: typeof AuthenticatedSantaRulesRoute
    }
    '/_authenticated/santa/configurations/new': {
      id: '/_authenticated/santa/configurations/new'
      path: '/new'
      fullPath: '/santa/configurations/new'
      preLoaderRoute: typeof AuthenticatedSantaConfigurationsNewRouteImport
      parentRoute: typeof AuthenticatedSantaConfigurationsRoute
    }
    '/_authenticated/reports/$reportId/live': {
      id: '/_authenticated/reports/$reportId/live'
      path: '/live'
      fullPath: '/reports/$reportId/live'
      preLoaderRoute: typeof AuthenticatedReportsReportIdLiveRouteImport
      parentRoute: typeof AuthenticatedReportsReportIdRoute
    }
    '/_authenticated/reports/$reportId/edit': {
      id: '/_authenticated/reports/$reportId/edit'
      path: '/edit'
      fullPath: '/reports/$reportId/edit'
      preLoaderRoute: typeof AuthenticatedReportsReportIdEditRouteImport
      parentRoute: typeof AuthenticatedReportsReportIdRoute
    }
    '/_authenticated/labels/$labelId/edit': {
      id: '/_authenticated/labels/$labelId/edit'
      path: '/$labelId/edit'
      fullPath: '/labels/$labelId/edit'
      preLoaderRoute: typeof AuthenticatedLabelsLabelIdEditRouteImport
      parentRoute: typeof AuthenticatedLabelsRoute
    }
    '/_authenticated/checks/$checkId/live': {
      id: '/_authenticated/checks/$checkId/live'
      path: '/live'
      fullPath: '/checks/$checkId/live'
      preLoaderRoute: typeof AuthenticatedChecksCheckIdLiveRouteImport
      parentRoute: typeof AuthenticatedChecksCheckIdRoute
    }
    '/_authenticated/checks/$checkId/edit': {
      id: '/_authenticated/checks/$checkId/edit'
      path: '/edit'
      fullPath: '/checks/$checkId/edit'
      preLoaderRoute: typeof AuthenticatedChecksCheckIdEditRouteImport
      parentRoute: typeof AuthenticatedChecksCheckIdRoute
    }
    '/_authenticated/santa/rules/$ruleId/edit': {
      id: '/_authenticated/santa/rules/$ruleId/edit'
      path: '/$ruleId/edit'
      fullPath: '/santa/rules/$ruleId/edit'
      preLoaderRoute: typeof AuthenticatedSantaRulesRuleIdEditRouteImport
      parentRoute: typeof AuthenticatedSantaRulesRoute
    }
    '/_authenticated/santa/configurations/$configurationId/edit': {
      id: '/_authenticated/santa/configurations/$configurationId/edit'
      path: '/$configurationId/edit'
      fullPath: '/santa/configurations/$configurationId/edit'
      preLoaderRoute: typeof AuthenticatedSantaConfigurationsConfigurationIdEditRouteImport
      parentRoute: typeof AuthenticatedSantaConfigurationsRoute
    }
    '/_authenticated/hosts/$hostId/reports/$reportId': {
      id: '/_authenticated/hosts/$hostId/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/hosts/$hostId/reports/$reportId'
      preLoaderRoute: typeof AuthenticatedHostsHostIdReportsReportIdRouteImport
      parentRoute: typeof AuthenticatedHostsHostIdRoute
    }
  }
}

interface AuthenticatedChecksCheckIdRouteChildren {
  AuthenticatedChecksCheckIdEditRoute: typeof AuthenticatedChecksCheckIdEditRoute
  AuthenticatedChecksCheckIdLiveRoute: typeof AuthenticatedChecksCheckIdLiveRoute
  AuthenticatedChecksCheckIdIndexRoute: typeof AuthenticatedChecksCheckIdIndexRoute
}

const AuthenticatedChecksCheckIdRouteChildren: AuthenticatedChecksCheckIdRouteChildren =
  {
    AuthenticatedChecksCheckIdEditRoute: AuthenticatedChecksCheckIdEditRoute,
    AuthenticatedChecksCheckIdLiveRoute: AuthenticatedChecksCheckIdLiveRoute,
    AuthenticatedChecksCheckIdIndexRoute: AuthenticatedChecksCheckIdIndexRoute,
  }

const AuthenticatedChecksCheckIdRouteWithChildren =
  AuthenticatedChecksCheckIdRoute._addFileChildren(
    AuthenticatedChecksCheckIdRouteChildren,
  )

interface AuthenticatedChecksRouteChildren {
  AuthenticatedChecksCheckIdRoute: typeof AuthenticatedChecksCheckIdRouteWithChildren
  AuthenticatedChecksNewRoute: typeof AuthenticatedChecksNewRoute
  AuthenticatedChecksIndexRoute: typeof AuthenticatedChecksIndexRoute
}

const AuthenticatedChecksRouteChildren: AuthenticatedChecksRouteChildren = {
  AuthenticatedChecksCheckIdRoute: AuthenticatedChecksCheckIdRouteWithChildren,
  AuthenticatedChecksNewRoute: AuthenticatedChecksNewRoute,
  AuthenticatedChecksIndexRoute: AuthenticatedChecksIndexRoute,
}

const AuthenticatedChecksRouteWithChildren =
  AuthenticatedChecksRoute._addFileChildren(AuthenticatedChecksRouteChildren)

interface AuthenticatedHostsHostIdRouteChildren {
  AuthenticatedHostsHostIdReportsReportIdRoute: typeof AuthenticatedHostsHostIdReportsReportIdRoute
}

const AuthenticatedHostsHostIdRouteChildren: AuthenticatedHostsHostIdRouteChildren =
  {
    AuthenticatedHostsHostIdReportsReportIdRoute:
      AuthenticatedHostsHostIdReportsReportIdRoute,
  }

const AuthenticatedHostsHostIdRouteWithChildren =
  AuthenticatedHostsHostIdRoute._addFileChildren(
    AuthenticatedHostsHostIdRouteChildren,
  )

interface AuthenticatedHostsRouteChildren {
  AuthenticatedHostsHostIdRoute: typeof AuthenticatedHostsHostIdRouteWithChildren
  AuthenticatedHostsIndexRoute: typeof AuthenticatedHostsIndexRoute
}

const AuthenticatedHostsRouteChildren: AuthenticatedHostsRouteChildren = {
  AuthenticatedHostsHostIdRoute: AuthenticatedHostsHostIdRouteWithChildren,
  AuthenticatedHostsIndexRoute: AuthenticatedHostsIndexRoute,
}

const AuthenticatedHostsRouteWithChildren =
  AuthenticatedHostsRoute._addFileChildren(AuthenticatedHostsRouteChildren)

interface AuthenticatedLabelsRouteChildren {
  AuthenticatedLabelsNewRoute: typeof AuthenticatedLabelsNewRoute
  AuthenticatedLabelsIndexRoute: typeof AuthenticatedLabelsIndexRoute
  AuthenticatedLabelsLabelIdEditRoute: typeof AuthenticatedLabelsLabelIdEditRoute
}

const AuthenticatedLabelsRouteChildren: AuthenticatedLabelsRouteChildren = {
  AuthenticatedLabelsNewRoute: AuthenticatedLabelsNewRoute,
  AuthenticatedLabelsIndexRoute: AuthenticatedLabelsIndexRoute,
  AuthenticatedLabelsLabelIdEditRoute: AuthenticatedLabelsLabelIdEditRoute,
}

const AuthenticatedLabelsRouteWithChildren =
  AuthenticatedLabelsRoute._addFileChildren(AuthenticatedLabelsRouteChildren)

interface AuthenticatedReportsReportIdRouteChildren {
  AuthenticatedReportsReportIdEditRoute: typeof AuthenticatedReportsReportIdEditRoute
  AuthenticatedReportsReportIdLiveRoute: typeof AuthenticatedReportsReportIdLiveRoute
  AuthenticatedReportsReportIdIndexRoute: typeof AuthenticatedReportsReportIdIndexRoute
}

const AuthenticatedReportsReportIdRouteChildren: AuthenticatedReportsReportIdRouteChildren =
  {
    AuthenticatedReportsReportIdEditRoute:
      AuthenticatedReportsReportIdEditRoute,
    AuthenticatedReportsReportIdLiveRoute:
      AuthenticatedReportsReportIdLiveRoute,
    AuthenticatedReportsReportIdIndexRoute:
      AuthenticatedReportsReportIdIndexRoute,
  }

const AuthenticatedReportsReportIdRouteWithChildren =
  AuthenticatedReportsReportIdRoute._addFileChildren(
    AuthenticatedReportsReportIdRouteChildren,
  )

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsReportIdRoute: typeof AuthenticatedReportsReportIdRouteWithChildren
  AuthenticatedReportsNewRoute: typeof AuthenticatedReportsNewRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsReportIdRoute:
    AuthenticatedReportsReportIdRouteWithChildren,
  AuthenticatedReportsNewRoute: AuthenticatedReportsNewRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedSantaConfigurationsRouteChildren {
  AuthenticatedSantaConfigurationsNewRoute: typeof AuthenticatedSantaConfigurationsNewRoute
  AuthenticatedSantaConfigurationsIndexRoute: typeof AuthenticatedSantaConfigurationsIndexRoute
  AuthenticatedSantaConfigurationsConfigurationIdEditRoute: typeof AuthenticatedSantaConfigurationsConfigurationIdEditRoute
}

const AuthenticatedSantaConfigurationsRouteChildren: AuthenticatedSantaConfigurationsRouteChildren =
  {
    AuthenticatedSantaConfigurationsNewRoute:
      AuthenticatedSantaConfigurationsNewRoute,
    AuthenticatedSantaConfigurationsIndexRoute:
      AuthenticatedSantaConfigurationsIndexRoute,
    AuthenticatedSantaConfigurationsConfigurationIdEditRoute:
      AuthenticatedSantaConfigurationsConfigurationIdEditRoute,
  }

const AuthenticatedSantaConfigurationsRouteWithChildren =
  AuthenticatedSantaConfigurationsRoute._addFileChildren(
    AuthenticatedSantaConfigurationsRouteChildren,
  )

interface AuthenticatedSantaRulesRouteChildren {
  AuthenticatedSantaRulesNewRoute: typeof AuthenticatedSantaRulesNewRoute
  AuthenticatedSantaRulesIndexRoute: typeof AuthenticatedSantaRulesIndexRoute
  AuthenticatedSantaRulesRuleIdEditRoute: typeof AuthenticatedSantaRulesRuleIdEditRoute
}

const AuthenticatedSantaRulesRouteChildren: AuthenticatedSantaRulesRouteChildren =
  {
    AuthenticatedSantaRulesNewRoute: AuthenticatedSantaRulesNewRoute,
    AuthenticatedSantaRulesIndexRoute: AuthenticatedSantaRulesIndexRoute,
    AuthenticatedSantaRulesRuleIdEditRoute:
      AuthenticatedSantaRulesRuleIdEditRoute,
  }

const AuthenticatedSantaRulesRouteWithChildren =
  AuthenticatedSantaRulesRoute._addFileChildren(
    AuthenticatedSantaRulesRouteChildren,
  )

interface AuthenticatedSantaRouteChildren {
  AuthenticatedSantaConfigurationsRoute: typeof AuthenticatedSantaConfigurationsRouteWithChildren
  AuthenticatedSantaEventsRoute: typeof AuthenticatedSantaEventsRoute
  AuthenticatedSantaRulesRoute: typeof AuthenticatedSantaRulesRouteWithChildren
  AuthenticatedSantaIndexRoute: typeof AuthenticatedSantaIndexRoute
}

const AuthenticatedSantaRouteChildren: AuthenticatedSantaRouteChildren = {
  AuthenticatedSantaConfigurationsRoute:
    AuthenticatedSantaConfigurationsRouteWithChildren,
  AuthenticatedSantaEventsRoute: AuthenticatedSantaEventsRoute,
  AuthenticatedSantaRulesRoute: AuthenticatedSantaRulesRouteWithChildren,
  AuthenticatedSantaIndexRoute: AuthenticatedSantaIndexRoute,
}

const AuthenticatedSantaRouteWithChildren =
  AuthenticatedSantaRoute._addFileChildren(AuthenticatedSantaRouteChildren)

interface AuthenticatedSoftwareRouteChildren {
  AuthenticatedSoftwareIndexRoute: typeof AuthenticatedSoftwareIndexRoute
  AuthenticatedSoftwareTitlesSoftwareIdRoute: typeof AuthenticatedSoftwareTitlesSoftwareIdRoute
}

const AuthenticatedSoftwareRouteChildren: AuthenticatedSoftwareRouteChildren = {
  AuthenticatedSoftwareIndexRoute: AuthenticatedSoftwareIndexRoute,
  AuthenticatedSoftwareTitlesSoftwareIdRoute:
    AuthenticatedSoftwareTitlesSoftwareIdRoute,
}

const AuthenticatedSoftwareRouteWithChildren =
  AuthenticatedSoftwareRoute._addFileChildren(
    AuthenticatedSoftwareRouteChildren,
  )

interface AuthenticatedUsersRouteChildren {
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedUsersUserIdEditRoute: typeof AuthenticatedUsersUserIdEditRoute
}

const AuthenticatedUsersRouteChildren: AuthenticatedUsersRouteChildren = {
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedUsersUserIdEditRoute: AuthenticatedUsersUserIdEditRoute,
}

const AuthenticatedUsersRouteWithChildren =
  AuthenticatedUsersRoute._addFileChildren(AuthenticatedUsersRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedChecksRoute: typeof AuthenticatedChecksRouteWithChildren
  AuthenticatedHostsRoute: typeof AuthenticatedHostsRouteWithChildren
  AuthenticatedLabelsRoute: typeof AuthenticatedLabelsRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedSantaRoute: typeof AuthenticatedSantaRouteWithChildren
  AuthenticatedSecretsRoute: typeof AuthenticatedSecretsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSoftwareRoute: typeof AuthenticatedSoftwareRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedChecksRoute: AuthenticatedChecksRouteWithChildren,
  AuthenticatedHostsRoute: AuthenticatedHostsRouteWithChildren,
  AuthenticatedLabelsRoute: AuthenticatedLabelsRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedSantaRoute: AuthenticatedSantaRouteWithChildren,
  AuthenticatedSecretsRoute: AuthenticatedSecretsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSoftwareRoute: AuthenticatedSoftwareRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
