/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedUsersRouteImport } from './routes/_authed/users'
import { Route as AuthedSoftwareRouteImport } from './routes/_authed/software'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedSantaRouteImport } from './routes/_authed/santa'
import { Route as AuthedReportsRouteImport } from './routes/_authed/reports'
import { Route as AuthedMunkiRouteImport } from './routes/_authed/munki'
import { Route as AuthedLabelsRouteImport } from './routes/_authed/labels'
import { Route as AuthedChecksRouteImport } from './routes/_authed/checks'
import { Route as AuthedHostsIndexRouteImport } from './routes/_authed/hosts/index'
import { Route as AuthedHostsHostIdRouteImport } from './routes/_authed/hosts/$hostId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedUsersRoute = AuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSoftwareRoute = AuthedSoftwareRouteImport.update({
  id: '/software',
  path: '/software',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSantaRoute = AuthedSantaRouteImport.update({
  id: '/santa',
  path: '/santa',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportsRoute = AuthedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMunkiRoute = AuthedMunkiRouteImport.update({
  id: '/munki',
  path: '/munki',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLabelsRoute = AuthedLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedChecksRoute = AuthedChecksRouteImport.update({
  id: '/checks',
  path: '/checks',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHostsIndexRoute = AuthedHostsIndexRouteImport.update({
  id: '/hosts/',
  path: '/hosts/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHostsHostIdRoute = AuthedHostsHostIdRouteImport.update({
  id: '/hosts/$hostId',
  path: '/hosts/$hostId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/checks': typeof AuthedChecksRoute
  '/labels': typeof AuthedLabelsRoute
  '/munki': typeof AuthedMunkiRoute
  '/reports': typeof AuthedReportsRoute
  '/santa': typeof AuthedSantaRoute
  '/settings': typeof AuthedSettingsRoute
  '/software': typeof AuthedSoftwareRoute
  '/users': typeof AuthedUsersRoute
  '/hosts/$hostId': typeof AuthedHostsHostIdRoute
  '/hosts/': typeof AuthedHostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/checks': typeof AuthedChecksRoute
  '/labels': typeof AuthedLabelsRoute
  '/munki': typeof AuthedMunkiRoute
  '/reports': typeof AuthedReportsRoute
  '/santa': typeof AuthedSantaRoute
  '/settings': typeof AuthedSettingsRoute
  '/software': typeof AuthedSoftwareRoute
  '/users': typeof AuthedUsersRoute
  '/hosts/$hostId': typeof AuthedHostsHostIdRoute
  '/hosts': typeof AuthedHostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_authed/checks': typeof AuthedChecksRoute
  '/_authed/labels': typeof AuthedLabelsRoute
  '/_authed/munki': typeof AuthedMunkiRoute
  '/_authed/reports': typeof AuthedReportsRoute
  '/_authed/santa': typeof AuthedSantaRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/software': typeof AuthedSoftwareRoute
  '/_authed/users': typeof AuthedUsersRoute
  '/_authed/hosts/$hostId': typeof AuthedHostsHostIdRoute
  '/_authed/hosts/': typeof AuthedHostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/checks'
    | '/labels'
    | '/munki'
    | '/reports'
    | '/santa'
    | '/settings'
    | '/software'
    | '/users'
    | '/hosts/$hostId'
    | '/hosts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/checks'
    | '/labels'
    | '/munki'
    | '/reports'
    | '/santa'
    | '/settings'
    | '/software'
    | '/users'
    | '/hosts/$hostId'
    | '/hosts'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/setup'
    | '/_authed/checks'
    | '/_authed/labels'
    | '/_authed/munki'
    | '/_authed/reports'
    | '/_authed/santa'
    | '/_authed/settings'
    | '/_authed/software'
    | '/_authed/users'
    | '/_authed/hosts/$hostId'
    | '/_authed/hosts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/users': {
      id: '/_authed/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/software': {
      id: '/_authed/software'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof AuthedSoftwareRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/santa': {
      id: '/_authed/santa'
      path: '/santa'
      fullPath: '/santa'
      preLoaderRoute: typeof AuthedSantaRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports': {
      id: '/_authed/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedReportsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/munki': {
      id: '/_authed/munki'
      path: '/munki'
      fullPath: '/munki'
      preLoaderRoute: typeof AuthedMunkiRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/labels': {
      id: '/_authed/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof AuthedLabelsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/checks': {
      id: '/_authed/checks'
      path: '/checks'
      fullPath: '/checks'
      preLoaderRoute: typeof AuthedChecksRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/hosts/': {
      id: '/_authed/hosts/'
      path: '/hosts'
      fullPath: '/hosts/'
      preLoaderRoute: typeof AuthedHostsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/hosts/$hostId': {
      id: '/_authed/hosts/$hostId'
      path: '/hosts/$hostId'
      fullPath: '/hosts/$hostId'
      preLoaderRoute: typeof AuthedHostsHostIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedChecksRoute: typeof AuthedChecksRoute
  AuthedLabelsRoute: typeof AuthedLabelsRoute
  AuthedMunkiRoute: typeof AuthedMunkiRoute
  AuthedReportsRoute: typeof AuthedReportsRoute
  AuthedSantaRoute: typeof AuthedSantaRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedSoftwareRoute: typeof AuthedSoftwareRoute
  AuthedUsersRoute: typeof AuthedUsersRoute
  AuthedHostsHostIdRoute: typeof AuthedHostsHostIdRoute
  AuthedHostsIndexRoute: typeof AuthedHostsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedChecksRoute: AuthedChecksRoute,
  AuthedLabelsRoute: AuthedLabelsRoute,
  AuthedMunkiRoute: AuthedMunkiRoute,
  AuthedReportsRoute: AuthedReportsRoute,
  AuthedSantaRoute: AuthedSantaRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedSoftwareRoute: AuthedSoftwareRoute,
  AuthedUsersRoute: AuthedUsersRoute,
  AuthedHostsHostIdRoute: AuthedHostsHostIdRoute,
  AuthedHostsIndexRoute: AuthedHostsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
