import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

import generatedApiSidebar from "./content/api/sidebar";

type ApiSidebar = Extract<NonNullable<SidebarsConfig["apiSidebar"]>, unknown[]>;
type ApiItem = ApiSidebar[number];
const apiSidebarItems = generatedApiSidebar as ApiItem[];

// The plugin repeats its info page inside every tag group. Keep the page
// generated so operation authentication links still resolve, but use the
// hand-written overview as the visible API landing page.
function removeGeneratedInfoItem(item: ApiItem): ApiItem | null {
  if (
    typeof item === "object" &&
    "type" in item &&
    item.type === "doc" &&
    "id" in item &&
    item.id === "api/woodstar-api"
  ) {
    return null;
  }
  if (
    typeof item === "object" &&
    "type" in item &&
    item.type === "category" &&
    Array.isArray(item.items)
  ) {
    return {
      ...item,
      items: item.items
        .map((child) => removeGeneratedInfoItem(child as ApiItem))
        .filter((child): child is ApiItem => child !== null),
    };
  }
  return item;
}

// tagGroup always emits group -> tag -> operation. Collapse the redundant
// tag level when a top-level resource is its own single tag.
function collapseSingletonTagGroup(item: ApiItem): ApiItem {
  if (
    typeof item !== "object" ||
    !("type" in item) ||
    item.type !== "category" ||
    !Array.isArray(item.items) ||
    item.items.length !== 1
  ) {
    return item;
  }
  const child = item.items[0];
  if (
    typeof child !== "object" ||
    !("type" in child) ||
    child.type !== "category" ||
    child.label !== item.label
  ) {
    return item;
  }
  return child;
}

const apiGroups = apiSidebarItems
  .map(removeGeneratedInfoItem)
  .filter((item): item is ApiItem => item !== null)
  .map(collapseSingletonTagGroup);

const sidebars: SidebarsConfig = {
  docsSidebar: [
    { type: "doc", id: "intro" },
    {
      type: "category",
      label: "Getting Started",
      items: [{ type: "autogenerated", dirName: "getting-started" }],
    },
    {
      type: "category",
      label: "Concepts",
      items: [{ type: "autogenerated", dirName: "concepts" }],
    },
    {
      type: "category",
      label: "Using Woodstar",
      items: [{ type: "autogenerated", dirName: "admin" }],
    },
    {
      type: "category",
      label: "Agent Protocols",
      items: [{ type: "autogenerated", dirName: "agent-protocols" }],
    },
    {
      type: "category",
      label: "AutoPkg",
      items: [{ type: "autogenerated", dirName: "autopkg" }],
    },
    {
      type: "category",
      label: "Configuration",
      items: [{ type: "autogenerated", dirName: "configuration" }],
    },
    {
      type: "category",
      label: "Development",
      items: [{ type: "autogenerated", dirName: "development" }],
    },
  ],
  apiSidebar: [{ type: "doc", id: "api/overview" }, ...apiGroups],
};

export default sidebars;
